### PR TITLE
Fix for Issue #2143 False Duplication of Items

### PR DESCRIPTION
**Pull request by jezznar**
* **Addressed Issue(s)**: #2143 

* **Server Mode**: Both

* **Description of Pull Request**: Added trade check on @refresh command and cancels it before doing the refresh itself

### CODE REVIEW

**Comment by jezznar** [comment]
After @refresh
image

**Comment by Jeybla** [comment]
How about adding it to `clif_refresh`? Buying stores are closed in it, too:
```C
// unlike vending, resuming buyingstore crashes the client.
buyingstore_close(sd);
```
Thanks for the PR!

**Comment by jezznar** [comment]
Alright. I thought this was only specific to player-to-player trade.

**Comment by jezznar** [comment]
Moved trade check to clif_refresh as per recommendation of @Jeybla 
Added check on buy/sell state.

**Pull request merged**
