### PR TITLE
Battle.cpp Adjusted item drop minimum value limit

### PR DESCRIPTION
**Pull request by mazvi**
Adjusted item drop minimum value limit

Lowered the item drop minimum value limits to be able to be set to 0.

Revision from: #2561 

* **Addressed Issue(s)**: 

* **Server Mode**: 

* **Description of Pull Request**:

### CODE REVIEW

**Comment by Atemo** [comment]
Isn't it the same config in https://github.com/rathena/rathena/pull/2561 ?

**Comment by mazvi** [comment]
No 2561 is battle.c on my PR is battle.cpp

**Comment by Atemo** [comment]
battle.c was remaned in battle.cpp in https://github.com/rathena/rathena/commit/c4a364be2c7f9f443d479639e3422a4ce00b6268 for c++. We just need to update the branch https://github.com/rathena/rathena/pull/2561 and resolve the potential conflicts, no need to make another PR :)

**Comment by mazvi** [comment]
okay iam sory, so i close this PR... Sorry once again..

**Pull request closed without merging**
