### PR TITLE
Fixed Cash Shop NPC

### PR DESCRIPTION
**Pull request by officialronode**
This update fix the cash shop npc error ( The Purchase has failed because the NPC does not exist. ) Tried & Tested for 2012-04-10 and 2013-08-07 client.

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
Do you mind to link the corresponding bug report(s)? Thank you for your contribution!

**Comment by officialronode** [comment]
When trying to buy a item on cash shop npc it says ( The Purchase has failed because the NPC does not exist. )

Screenshots:
http://prntscr.com/8uobv0
http://prntscr.com/8uobzg
http://prntscr.com/8uoc0q

Thread: 
https://rathena.org/board/topic/103572-2013-08-07-cashshop-purchase-failed-svngit-cannot-determine/

**Comment by cydh** [comment]
**DO NOT** merge this. What he does is not totally correct, he just reverted 11f42f27ab4b9eb54c6b12e95b4ff8ec077fa157

**Comment by Lemongrass3110** [comment]
Okay so I guess there is no github issue yet?
Well your fix, creates a issue for other clients though. Could you open up an issue and we will have a look at this? Thanks!

@cydh
confirmed. :)

**Comment by officialronode** [comment]
@cydh @Lemongrass3110 I'm very sorry about that. But is there a fix on that issue? Aside from reverting that code from the old one.

**Comment by hnomkeng** [comment]
@officialronode Reverted https://github.com/rathena/rathena/commit/11f42f27ab4b9eb54c6b12e95b4ff8ec077fa157

**Pull request merged**
