### PR TITLE
Added battle config autoloot_adjust

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: #2540

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Added battle config autoloot_adjust that allows autoloot to take player drop penalties and bonuses into account.
Thanks to @ecdarreola!

### CODE REVIEW

**Comment by ecdarreola** [comment]
Tried the PR, and its work great! 1 question though, does bubble gum reflect on @mi command?

**Comment by aleos89** [comment]
No, the only modifier for `@mi` is VIP.

**Comment by ecdarreola** [comment]
Thanks @aleos89 , the PR is working as intended now. <3

**Comment by ecdarreola** [comment]
Hi, somehow after using this pull-request prior migration to c++ i'm having a problem of sudden mob freeze. Before this PR I didn't have any problem of sudden mob freeze. 

How do I check/verify it? No errors spit out on the console. All are normal.

**Pull request merged**
