### PR TITLE
Jobmaster: Third Class Non Trans Option

### PR DESCRIPTION
**Pull request by mazvi**
// .ThirdClassNonTrans
//	= Disable it if you want player MUST BE rebirth class first to get job 3
//	= Enable it if you want player with job 2 have choice get job 3 or job Rebirth

This feature is for server need long story line so people must became rebirth first if want to get job 3

* **Addressed Issue(s)**: 

* **Server Mode**: 

* **Description of Pull Request**:

### CODE REVIEW

**Comment by Akkarinage** [comment]
This file has received a alot of attention over the last few weeks. Considering its a custom script and has nothing to do with the official job scripts, perhaps attention would be better utilised elsewhere.

**Comment by mazvi** [comment]
i just want to help. because there are also private servers who want to use long stories in the journey job. but if it is felt this is not necessary I apologize. because it's too excited.

So what sould i do? Detete this pull? Iam sory for my fault..

**Comment by Jeybla** [comment]
https://github.com/rathena/rathena/commit/2676d05394008288a882c8966a4d6da3865d0eaa#commitcomment-24824085

Already told here that I don't see this option needed in our repository. If anyone else is asking for it, we may add it later, but I think you're current the only one who's looking for this option. So for everyone else this is just confusing.
Anyway, thanks for your contributions :)

**Comment by mazvi** [comment]
Don't we need this? Because job 4 can't be with regular job 3, it has to be job 3 trans :D

**Pull request closed without merging**
