### PR TITLE
Update jobmaster.txt

### PR DESCRIPTION
**Pull request by mazvi**
Added feature Enable/Disable Rebirth Class (By: Maz-V)

* **Addressed Issue(s)**: 

* **Server Mode**: 

* **Description of Pull Request**:

### CODE REVIEW

**Comment by Atemo** [comment]
What about a condition in the menu like for 3rd class restriction? https://github.com/rathena/rathena/pull/2327/files#diff-5a3baaecdcaf1c909de82f146e48434cR66

**Comment by mazvi** [comment]
yes i think if there was disable rebirth the people also dont like job 3... for example ragnarok restart or ragnarok indonesia gravindo, or ragnarok with use Revo-Classic mechanism there was only Job 2-2

**Comment by Atemo** [comment]
For me the owner should be able to choose

**Comment by mazvi** [comment]
anyone to help me? to change about this for better use

**Comment by sader1992** [comment]
i would start by removing the changes fro here
`		//if (.RebirthClass == 0) {
		//	mes "No more jobs are available.";
		//	close;
		//}
`
and edit here
`.@i = select(" ~ ^0055FFRebirth^000000:" + ((.ThirdClass) ? " ~ ^FF0000Third Class^000000" : "") + ": ~ ^777777Cancel^000000");`
to be 
`.@i = select(((.RebirthClass) ? " ~ ^0055FFRebirth^000000:" : "" ) + ((.ThirdClass) ? " ~ ^FF0000Third Class^000000" : "") + ": ~ ^777777Cancel^000000");`
and i change the result of .@i 
i may need to rewrite the select from the start

**Comment by Jeybla** [comment]
Closing this pr and continuing with #2369. I opened a new pr because I'd like to rewrite some parts in the jobmaster to improve the readability.
Thanks @mazvi for the idea.

**Pull request closed without merging**
