### PR TITLE
Job Improvement Project - Super Novice

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: #4427

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * kRO Changelog: http://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=7081
Thanks to @Rytech2!

### CODE REVIEW

**Comment by OptimusM** [comment]
(tested on a 20180919a client)
Skills
NV_BREAKTHROUGH (Can ve leveled up and u will reciebe the bonuses, but it will shown as lvl0 consuming skills points)
NV_HELPANGEL (it will consume the skill point but u cant use it.
NV_TRANSCENDENCE (Can ve leveled up and u will reciebe the bonuses, but it will shown as lvl0 consuming skills points)

i think those skills cant be assigned by clients below march2019 like Rytech told me, but, U can still use it by @useskill commands but u cant assign that on skilltree.

**Comment by aleos89** [comment]
It would seem just a LUB adjustment. I don't see why the skills won't stick as all you have to do is confirm the skilltreeview.lub file contains those skills for that class.

**Comment by Badarosk0** [comment]
> (tested on a 20180919a client)
> Skills
> NV_BREAKTHROUGH (Can be leveled up and u will reciebe the bonuses, but it will shown as lvl0 consuming skills points)
> NV_HELPANGEL (it will consume the skill point but u cant use it.
> NV_TRANSCENDENCE (Can be leveled up and u will reciebe the bonuses, but it will shown as lvl0 consuming skills points)
> 
> i think those skills cant be assigned by clients below march2019 like Rytech told me, but, U can still use it by @useskill commands but u cant assign that on skilltree.
> 
> 

This problem is real. I needed to change the skill ID to another unused ID to work.

**Comment by admkakaroto** [comment]
> > (tested on a 20180919a client)
> > Skills
> > NV_BREAKTHROUGH (Can be leveled up and u will reciebe the bonuses, but it will shown as lvl0 consuming skills points)
> > NV_HELPANGEL (it will consume the skill point but u cant use it.
> > NV_TRANSCENDENCE (Can be leveled up and u will reciebe the bonuses, but it will shown as lvl0 consuming skills points)
> > i think those skills cant be assigned by clients below march2019 like Rytech told me, but, U can still use it by @useskill commands but u cant assign that on skilltree.
> > 
> 
> This problem is real. I needed to change the skill ID to another unused ID to work.

Well I couldn't put any points on any skills either.

**Comment by edwardlucian** [comment]
> (tested on a 20180919a client)
> Skills
> NV_BREAKTHROUGH (Can be leveled up and u will reciebe the bonuses, but it will shown as lvl0 consuming skills points)
> NV_HELPANGEL (it will consume the skill point but u cant use it.
> NV_TRANSCENDENCE (Can be leveled up and u will reciebe the bonuses, but it will shown as lvl0 consuming skills points)
> 
> i think those skills cant be assigned by clients below march2019 like Rytech told me, but, U can still use it by @useskill commands but u cant assign that on skilltree.
> 
> 

Help

**Comment by edwardlucian** [comment]
> It would seem just a LUB adjustment. I don't see why the skills won't stick as all you have to do is confirm the skilltreeview.lub file contains those skills for that class.

i do already but it don't work

**Comment by samers1** [comment]
> 
> 
> > (tested on a 20180919a client)
> > Skills
> > NV_BREAKTHROUGH (Can be leveled up and u will reciebe the bonuses, but it will shown as lvl0 consuming skills points)
> > NV_HELPANGEL (it will consume the skill point but u cant use it.
> > NV_TRANSCENDENCE (Can be leveled up and u will reciebe the bonuses, but it will shown as lvl0 consuming skills points)
> > i think those skills cant be assigned by clients below march2019 like Rytech told me, but, U can still use it by @useskill commands but u cant assign that on skilltree.
> > 
> 
> This problem is real. I needed to change the skill ID to another unused ID to work.

I tryed that solution, but not worked.

**Comment by SeravySensei** [comment]
> 
> 
> > (tested on a 20180919a client)
> > Skills
> > NV_BREAKTHROUGH (Can be leveled up and u will reciebe the bonuses, but it will shown as lvl0 consuming skills points)
> > NV_HELPANGEL (it will consume the skill point but u cant use it.
> > NV_TRANSCENDENCE (Can be leveled up and u will reciebe the bonuses, but it will shown as lvl0 consuming skills points)
> > i think those skills cant be assigned by clients below march2019 like Rytech told me, but, U can still use it by @useskill commands but u cant assign that on skilltree.
> > 
> 
> This problem is real. I needed to change the skill ID to another unused ID to work.

Confirmed, I can level up all 3 skills, the skill points are spent, and the skill is set to learned in the server database but in the client it still shows up as if I didn't have the skill. Did anyone find a solution?

**Comment by qwerty7vp** [comment]
> Confirmed, I can level up all 3 skills, the skill points are spent, and the skill is set to learned in the server database but in the client it still shows up as if I didn't have the skill. Did anyone find a solution?

this is a client limitation. you just need to wait for support of newer clients.
#4918

**Pull request merged**
