### PR TITLE
Fixed secure timeout triggering npc_scriptcont debug messages

### PR DESCRIPTION
**Pull request by Daegaladh**
* **Addressed Issue(s)**: #5235

* **Server Mode**: Both

* **Description of Pull Request**: Fixes secure timeout triggering npc_scriptcont debug messages

### CODE REVIEW

**Comment by ecdarreola** [comment]
Causes geffen magic tournament to stuck at 1st dialog on the match.

**Comment by Daegaladh** [comment]
> Causes geffen magic tournament to stuck at 1st dialog on the match.
Which dialog exactly?
Does this happen always with this script at the same point?

**Comment by ecdarreola** [comment]
> > Causes geffen magic tournament to stuck at 1st dialog on the match.
> > Which dialog exactly?
> > Does this happen always with this script at the same point?

This happens on `line 1356` of the script for the `NPC Geffen Academy Master#s` without this PR script has no problem.

**Comment by Daegaladh** [comment]
> This happens on `line 1356` of the script for the `NPC Geffen Academy Master#s` without this PR script has no problem.
Try now ;)

**Comment by ecdarreola** [comment]
@Daegaladh works fine now. Thanks!

**Pull request merged**
