### PR TITLE
Implemented new items up to january 5, 2022

### PR DESCRIPTION
**Pull request by Atemo**
* **Addressed Issue(s)**: -

* **Server Mode**: renewal

* **Description of Pull Request**: 

Implemented new items up to january 5, 2022 according to KRO description.

### CODE REVIEW

**Comment by attackjom** [comment]
is it good if we write weapon lv5 Patk bonus / armor lv2 res,mres bonus  at item script ?

**Comment by Atemo** [comment]
What do you mean? I don't get the idea

**Comment by Lemongrass3110** [comment]
> is it good if we write weapon lv5 Patk bonus / armor lv2 res,mres bonus at item script ?

@attackjom this is already in status.cpp
```cpp
if( wlv == 5 ){
    base_status->patk += sd->inventory.u.items_inventory[index].refine * 2;
    base_status->smatk += sd->inventory.u.items_inventory[index].refine * 2;
}
```

```cpp
if( sd->inventory_data[index]->armor_level == 2 ){
	base_status->res += sd->inventory.u.items_inventory[index].refine * 2;
	base_status->mres += sd->inventory.u.items_inventory[index].refine * 2;
}
```

**Comment by attackjom** [comment]
> > is it good if we write weapon lv5 Patk bonus / armor lv2 res,mres bonus at item script ?
> 
> @attackjom this is already in status.cpp
> 
> ```c++
> if( wlv == 5 ){
> 	base_status->patk += sd->inventory.u.items_inventory[index].refine * 2;
> 	base_status->smatk += sd->inventory.u.items_inventory[index].refine * 2;
> }
> ```
> 
> ```c++
> if( sd->inventory_data[index]->armor_level == 2 ){
> 	base_status->res += sd->inventory.u.items_inventory[index].refine * 2;
> 	base_status->mres += sd->inventory.u.items_inventory[index].refine * 2;
> }
> ```

oh sorry, I didn't see its. T^T

**Comment by Lemongrass3110** [comment]
@Atemo please add AEGIS names that are already on divine pride.

**Comment by Atemo** [comment]
> @Atemo please add AEGIS names that are already on divine pride.

I did, 'unfortunately' some name have been updated on DP after the initial commit

**Pull request merged**
