### PR TITLE
Fixed #139 Vacuum Extreme effect

### LINKED ISSUE #139: Vacum extreme
Git Version: **12628 - 2014-12-04 05:04:30 (luciar)**
Client Date: **2012-04-10**
Src Mods: **NONE**
General settings: 
- **Full Renewal**
- **1/1/1/1/1 rate**
- **PK server (not in towns, above lvl 30)**
- **PVP ATK/Skill modifers: 100%**
- **WOE ATK/Skill modifers: rA default**
- **Official walk path and stacking**
- **Exp and drop penalty table values below 100% set to 100%**
- **Party and attacker exp bonus: +40%**
- More at (Hungarian, use translate): http://wiki.ragna.ro/

How to reproduce: **Use the skill**
Description:

The recurring issue has returned once again. Latest vers, re, pk server, 20140410 client, vacuum extreme does not stop monsters. Neither moving ones, nor static ones from starting to move.

### PR DESCRIPTION
**Pull request by cydh**
Signed-off-by: Cydh Ramdh <house.bad@gmail.com>

### CODE REVIEW

**Comment by cydh** [comment]
I need testers

**Comment by reigneil** [comment]
can you also modified the duration of this to reflect with the official.
https://docs.google.com/document/pub?id=1I2byIqDij02jwl6Tn4ekgHff0E501JP16iwYLc9vhDE
it is stated that the duration is only affected by BASE str.
Duration: [(2 + 2 * Skill Level) - (Target’s Base STR / 20)] seconds
something like this...
tick -= (max(status_get_base_status(bl)->str,1) / 20) * 1000;
correct me if i'm wrong.

**Comment by RagnarokNova** [comment]
You can currently keep players and enemies permanently under the status effect, which ends up being pretty broken as a mechanic.

**Comment by cydh** [comment]
merged manually @ cb2ffa24c8fbd4c0170fc4325683beffe0a7d4d8

**Pull request closed without merging**
