### PR TITLE
Updated the monster mob db drop

### PR DESCRIPTION
**Pull request by Atemo**
* **Addressed Issue(s)**: https://github.com/rathena/rathena/issues/6050, #3410

* **Server Mode**: renewal

* **Description of Pull Request**: 

Updated the monsters drop according to Divine Pride. Thanks to @Lemongrass3110 !

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
#3410 could also be linked?

**Comment by Lemongrass3110** [comment]
grafik

Noone is going to review or comment it in PR state anyway.
Maybe we get feedback once it is in master. ;-)

**Comment by Everade** [comment]
image
Looks good to me.
Master it is!

**Comment by Everade** [comment]
Anyone sponsoring a new mouse wheel?

Overall it looks solid. I didn't bother comparing anything to Divine-Pride, since it's a Divine-Pride scan xD
Looks like a major drop rate nerf. Only a handful of items actualy recieved a drop increase.

LHZ Dungeon monsters now drop 3D_Glasses_Box instead of Evil_Mind.
Not so sure about that... Seems a little off.
That's monster id 1805 - 1810

Added empty "Drops:" entries on the following lines (probably unintended):
Line 80842
Line 80810
Line 80778
Line 80746
Line 80714
Line 80682
Line 80650
Line 79946
Line 79914
Line 79882
Line 79850
Line 79818
Line 79786
Line 31144
Line 31106
Line 29917

**Comment by killerdark16** [comment]
hello sir, is it true "ghost chill" drop rate from monster bio level 4 now only 0.01?
or some mistake ?

**Pull request merged**
