### PR TITLE
Fixed clif_sendfakenpc

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: #8321

* **Server Mode**: Both

* **Description of Pull Request**: 
Updated packet to the latest version.

Thanks to @kaninhot004

### CODE REVIEW

**Comment by Beginerxx** [comment]
> @kaninhot004 and @datawulf can you please test, if this fixes your problems?

It's works fine thank you.

**Comment by datawulf** [comment]
> @kaninhot004 and @datawulf can you please test, if this fixes your problems?

NPC Script is starting now, menu pops up, but it breaks immediately if i try to continue with failed npc_checknear warning.

```
[13/May 10:57][Debug]: npc_scriptcont: hallo3#cnpc (sd->npc_id=110028101) is not 'Unknown NPC' (id=0).
[13/May 10:57][Warning]: npc_scriptcont: failed npc_checknear test.
[13/May 10:58][Warning]: npc_scriptcont: failed npc_checknear test.
```

**Comment by datawulf** [comment]
> @kaninhot004 and @datawulf can you please test, if this fixes your problems?

It works fine, thank you.

**Comment by jasonch35** [comment]
This PR fixed this [issue](https://github.com/rathena/rathena/issues/8328) as well.

**Pull request merged**
