### PR TITLE
Fixes Brandish Spear hit count

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: #4826

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Brandish Spear damage should be calculated separately for each hit.
Thanks to @Masao87!

### CODE REVIEW

**Comment by Latiosu** [comment]
@aleos89 I can confirm this fix works. Tested on 4a3dac6c93cb015bccee7bfe361fa4d7b5b6004c.
**Before**
before-brandish

**After**
after-brandish

**Comment by akiyamamio16** [comment]
> Confirmed working. See [#4830 (comment)](https://github.com/rathena/rathena/pull/4830#issuecomment-618960731)

did you try this? can you confirm please.
Hit : Single
HitCount : 1

**Comment by Latiosu** [comment]
> did you try this? can you confirm please. i think this is how it works on kRO
> Hit : Single
> HitCount : 1

I tested it, the damage output comes out correct but it no longer has the multi-hit effect (large yellow summary number) like in the following GIF: http://imgc.gnjoy.com/ufile/common/2018/08/16/045153_KKaeA3MC.gif

**Comment by akiyamamio16** [comment]
> > did you try this? can you confirm please. i think this is how it works on kRO
> > Hit : Single
> > HitCount : 1
> 
> I tested it, the damage output comes out correct but it no longer has the multi-hit effect (large yellow summary number) like in the following GIF: http://imgc.gnjoy.com/ufile/common/2018/08/16/045153_KKaeA3MC.gif

yes. that's how kRO works right now. it doesn't have the multi effect right.

**Comment by Latiosu** [comment]
@akiyamamio16 Happy to update the PR if this is the correct client display. Can confirm damage:
singlehit-brandish

**Comment by aleos89** [comment]
image

Just tested on kRO. It's 3 hits.

**Comment by teededung** [comment]
I believe this fix is wrong, please revert it. The brandish spear dame too large because damage stacking, it has been fixed in https://github.com/rathena/rathena/commit/75070658856b957806e9d422195863f3f3b3f2c4

Take a closer look at this photo http://imgc.gnjoy.com/ufile/common/2018/08/16/045153_KKaeA3MC.gif, you see it's a knight and deals 22k damage.

Another kRO video: https://www.youtube.com/watch?v=yEn26awc26Q&t=11s

**Comment by aleos89** [comment]
With a HitCount of -3 my hits are 3k~ each. With HitCount of 3 my hits are 9k~ each.

**Pull request merged**
