### PR TITLE
Initial support for enchantgrade

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: None

* **Server Mode**: Both

* **Description of Pull Request**: 
Adds initial support for the enchantgrade feature and updates all necessary packets to support newer clients.

Thanks to @LunarSHINING for his help

### CODE REVIEW

**Comment by idk-whoami** [comment]
enchantgrade

2020-08-19aRagexeRE
view equipment

**Comment by Lemongrass3110** [comment]
> 
> 
> enchantgrade
> 
> 2020-08-19aRagexeRE
> view equipment

@idk-whoami mind telling us what this should show...? Beside your LUA problem?

**Comment by Lemongrass3110** [comment]
Ok understood it now. Will check the missing packet on kRO.

**Comment by attackjom** [comment]
PACKET_ZC_ADD_ITEM_TO_CART and PACKET_ZC_PC_PURCHASE_MYITEMLIST_sub

also has uint8 refine;  above  uint8 enchantgrade;

**Pull request merged**
