### PR TITLE
Proposal to change the default packet version

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: None

* **Server Mode**: Both

* **Description of Pull Request**: 
We support all required features or have them ready in some pull requests.
The packet version after this will require a huge overhaul since item id sizes have been changed in all packets.

### CODE REVIEW

**Comment by anacondaqq** [comment]
Strongly against this (2018) Client version is SUPER bad and weak. You will have hell a lot of complaints.
Please leave 20170614 exe as default one, because it is MUCH stable. I telling you as a guy which supported hell a lot of people with this game (2017) client and have a lot of troubles with 2018 game clients.
2018 clients are not production ready at all, they need some time to make them good,  there is hell a lot of problems with 2018 clients mostly because of not supported features, because of removed content (AI support is a mega critical problem for RE and PRE servers), etc. Also, there is no stable client-base for these clients, so this packetver will be useless. 20150411 pretty stable and not bad game client (yes it has some bugs and problems). But better to pick something really stable, and as for me, something really stable is 2016-2017 game clients.

**Comment by Lemongrass3110** [comment]
@anacondaqq I regret having to tell you that rAthena is a server software and has nothing to do with the client side. If you do not want to use the default settings you are free to override/change them. But I have not found a lot of client diffs that are still broken.

**Comment by admkakaroto** [comment]
Does it make any difference to use the version defined in the emulator after this one?

`#elif PACKETVER > 20180307`

after this date all the clients use the same packages, so I think if it is to change it should be for this date.

**Comment by Lemongrass3110** [comment]
@admkakaroto private airship is 03-21 for example.

**Comment by MathReaper** [comment]
20180620 isn't too far?

**Comment by secretdataz** [comment]
@MathReaper Any reason why you consider it "too far"?

**Comment by anacondaqq** [comment]
@secretdataz go ahead, at least you (not personally you, but dev team) will face tons of negative here at on board too because it's too early add as default packetver a client which does not work well at all for now.

**Comment by Lemongrass3110** [comment]
@anacondaqq it is okay. I will take the blame. This way we will get feedback for the new clients at least. Sorry to say this, but we need to stay up to date and not intentionally stay behind for 3 years just because some features were dropped that some pre-renewal servers still want. That might be hard to accept, but as long as there is no open source client we will always have to accept the changes Gravity does to the client.

**Comment by zackdreaver** [comment]
Well I don't mind really if you guys changed the default packetserver to this,
Anything for the greater good of community, I'll try to support it.
If you guys don't mind, can you guys make or update the announcement regarding this?
Either minimum version or where to download the client?
https://rathena.org/board/topic/86650-officially-supported-client-versions/

p.s: The new Archbishop skills now can't be used normally if you use older client without hack,
like 2015-11-04aRagexe.

**Pull request merged**
