### PR TITLE
Corrected AegisName for some item

### PR DESCRIPTION
**Pull request by idk-whoami**
* **Addressed Issue(s)**: 

* **Server Mode**: re

* **Description of Pull Request**: 
`````
Fixed AegisName: aegis_xxx
``````
Capture

### CODE REVIEW

**Comment by limitro** [comment]
Where did the Aegis names come from? Leaks?

Example:
`  - Id: 15391
    AegisName: aegis_15391
    AegisName: DragonA_Red`

is wrong, it should be Dragenergy_Red
image

**Review by Atemo — APPROVED** [review]
Please note some names may have been auto-generated to fill the missing one!

**Comment by idk-whoami** [comment]
> Please note some names may have been auto-generated to fill the missing one!

Thanks

Do you need to fix anything?

**Comment by Atemo** [comment]
Thanks!

**Pull request merged**
