### PR TITLE
[FEATURE] restore amotion from sonicblow/vulcan arrow/cross impact removed from ragexe 20181128+ 

### PR DESCRIPTION
**Pull request by AoShinRO**
* **Addressed Issue(s)**:  https://github.com/Neo-Mind/WARP/issues/63

* **Server Mode**:  Both

* **Description of Pull Request**:  Add a feature config to force src send packets to restore hardcoded animation from sonicblow and vulcan arrow removed from ragexe 20181128+ using pre-renewal mode
https://ragnarok.fandom.com/wiki/RO_Patch_(2018_Nov._28)
maybe it's a work from 4144 😄 client sided hex edit but still without solution from years 
-> Added Cross Impact Amotion removed at 2019/10/16
https://ragnarok.fandom.com/wiki/RO_Patch_(2019_Oct._16)
-> Changed to be used on renewal too
-> Pre-Renewal stop attack call added

### CODE REVIEW

**Comment by AoShinRO** [comment]
project closed due to ingratitude

**Comment by elanosilveira** [comment]
It was a cool thing you were doing @AoShinRO. Keep it up.

**Comment by NexoMMORPG** [comment]
@AoShinRO  It's very well done, little by little you improved it and there was just a little left for it to look like the original.

**Comment by AoShinRO** [comment]
> @AoShinRO It's very well done, little by little you improved it and there was just a little left for it to look like the original.

The problem is that I don't play assassins job, i'm main alchemist haha, and the people who come to me to tell it is wrong don't know how to explain what's missing :/

**Comment by NexoMMORPG** [comment]
@AoShinRO I use assassins, if you want I can tell you what's missing, we can talk privately on discord
Can you add me with the id jinyuichi

**Pull request closed without merging**
