### PR TITLE
Custom woe controller update

### PR DESCRIPTION
**Pull request by Atemo**
* **Addressed Issue(s)**: -

* **Server Mode**: -

* **Description of Pull Request**: 

Content
--------------------------------------------
This PR adds the woe TE castle in the custom woe controller.
The setting format has been changed.

Note
--------------------------------------------
This update doesn't broke your woe session defined.

### CODE REVIEW

**Comment by RagnaWay** [comment]
@Atemo 
You could add an option **WoE Random**? to generate a castle to be opened on the day.
Example: Tuesday - Geffen / Thursday - Payon and Prontera / Saturday - WoE 2.0 (hence it will open only 1 or more castle of this feud according to the administrator, and the other castles and feuds are automatically disabled)

**Comment by mazvi** [comment]
Woe warper not work

**Comment by Atemo** [comment]
@RagnaWay I prefer to add one change at a time. Maybe in another PR?

**Comment by RagnaWay** [comment]
@Atemo Okay <3

**Pull request merged**
