### PR TITLE
Fixed #652 #818

### LINKED ISSUE #652: NPC: callshop "shop_name",1; end; -> freewalk, can talk to another npc, etc bugs.
### Related to: https://github.com/rathena/rathena/issues/503
**This bug not fixed.** 

### Let me Explain a bug:

**END;** command after any "callshop" in scripts will open this bug.

### How reproduce
```
/*
 * 1. Callshop Bugs 
 * ANY shops opened via callshop, and what have at the end "end", these shops will have this bug described
 * on the screenshot (freewalking, clicking another npc, do anything)
 */


prontera,155,180,5	script	CallShopBug	89,{
	
	switch(select("Open Shop", "Something", "Something2 "))
	{
		case 1:
			callshop "someshop",1;	// open shomeshop with buy list
			break;
		case 2:
			mes "doesnot matter what";
			break;
		case 3:
			mes "dummy data";
			break;
	}
	end;

}

-	shop	someshop	89,505:10000,506:6000,507:7000
```

## OR 

try to use any script based shops ([Euphy's Quest](https://github.com/rathena/rathena/blob/master/npc/custom/quests/quest_shop.txt) Shop for example)

## Refference
1. https://rathena.org/board/topic/96389-callshop-bug/
2. https://rathena.org/board/tracker/issue-8012-player-in-shop-state-npc-script-able-to-move-and-execute-other-npc-script/
3. https://www.youtube.com/watch?v=wn7XztJCHgg
#### 1. 
Regarding to this: https://github.com/rathena/rathena/issues/503
@aleos89 suggest to use ignoretimeout, but sorry, this is not working.
I can use 
> ignoretimeout 1; 

or
 
> ignoretimeout 0;

at any part of the script (i have enabled by default SECURE_TIMEOUT in sources)

and nothing will be happened, this will not help against this bug.

#### 2.
i was try totally to disable SECURE_TIMEOUT -> the bug still exist

#### 3.
i was try to add "sleep 1;" between callshop "something",1; and end; and it's works, but not on all scripts. + i found another funny bug.

#### Funny Bug related to **3.**

How reproduce:
1. Load Euphy Quest Shop
2. Find these lines
```
	dispbottom "Select one item at a time.";
	callshop "qshop"+@shop_index,1;
	npcshopattach "qshop"+@shop_index;
	end;
```
3. Replace to these lines:
```
	dispbottom "Select one item at a time.";
	callshop "qshop"+@shop_index,1;
	npcshopattach "qshop"+@shop_index;
	sleep 1;
	end;
```
4. You will see this bug (on gif) (you can't walk while you in shop, or you can't talk to NPC, and after closing shop, and again clicking on NPC, npc will hide, and after @refresh we will see it again)

## Technical Information
1. **Client Date**: 2012-04-10
2. **Rathena revision**: https://github.com/rathena/rathena/commit/230811c8abab0b1162b4409e3e6936dd75bdc8e5
3. **Mechanic**: Pre-re
4. Packet_ver: 30
5. without source modifications or client modifications

### PR DESCRIPTION
**Pull request by CairoLee**
Fixed the npc shop problem, already test in 2013-08-07 and 2015-05-13.
Thanks to @admkakaroto @Dark8008 @anacondaqq

Signed-off-by: CairoLee <cairoliyu@gmail.com>

### CODE REVIEW

**Comment by CairoLee** [comment]
Hi @cydh 
Could you review this commit?

**Comment by anacondaqq** [comment]
@CairoLee Hello:)
Thank you very much!
It's works.
Tested on 2012-04-10 exe at pre-re mode.
rAthena hash: d6343fba9e7c571c86e5504ec6e5345b5ae975aa

Which parts tested (and all works fine (can't move or touch other npc, and do not stuck / freez)) :
* OK Normal Zeny Shops
* OK Item shops
* OK Points Shops
* OK Items / points / zeny shops called with "callshop "shopname",1; end;
* OK calls from item bonus script

**Comment by lighta** [comment]
Won't this create an issue if we don't go trough "end", say with timeout, or warped ?
I understand that you really want to move the 
"sd->state.callshop = 0;"
But I don't get the need of the followup, (the invalid call check seem unrelated to where we close it)
I'd move the reset into clif_scriptclose() seem more robust.

**Comment by anacondaqq** [comment]
@lighta i though about the same thing, and it's really break my logic why this commit works, but it's works without issues.

**Comment by lighta** [comment]
Hmm so just to be sure, should we be able to move or not when callshop cause I'm quite confuse now.
Context:
Tested with client:2015-09-14 and merge master at (22a9a74d0c97e8ef7b4e98807275405ffc3b0318)
test_npc :
https://gist.github.com/lighta/ee1e0f99dfa0928a9363

Result:
npc1 : Couldn't move, nor talk to other npc before quit.
npc2 : Func wall called, (act like close2 then)
npc3 : Was able to move and talk to other npc
npc4 : same as npc3

Summary:
So maybe I didn't get it but I tought the goal was to prevent it to move, or basically to stop the script execution a bit like menu till we choose or I'm I completly wrong ?
If that was the goal then it's not reach yet. I'm wondering if putting it in state RERUNLINE then restarting script when we have the answer isn't a best option ?

**Comment by CairoLee** [comment]
My English is bad, I will reply in Chinese, I hope to have a friend to help translate into English, thank you.

若在执行到 callshop 之前，不调用任何 mes、menu、select等指令，那么客户端并不知道玩家现在进入了一个“与NPC对话中”的状态，所以客户端不会去禁止玩家的移动。

这一点我在3Ceam上进行测试，只要在脚本的开头立刻调用callshop，也是一样会存在问题的（玩家可以移动和与其他NPC对话），但我并不知道如何解决，若 @lighta 能修复的话，感激不尽！

我的英文糟糕透了，太过复杂的表述我怕会严重错译，能否请 @Angelmelody 或其他会英文的中国朋友帮忙翻译一下？谢谢。

**Pull request merged**
