### PR TITLE
Fix bDelayrate not working.

### PR DESCRIPTION
**Pull request by kaninhot004**
* **Addressed Issue(s)**: 

https://github.com/rathena/rathena/issues/6232

* **Server Mode**: 

Renewal

* **Description of Pull Request**: 

Fix bonus bDelayrate,n; not reduce skill delay.

### CODE REVIEW

**Comment by Everade** [comment]
This would revert the intended fix.
Swapping it up with a minus to properly deduct time would be more apropriate rather than revertig it to the custom behavior we've had before.

**Comment by kaninhot004** [comment]
> This would revert the intended fix.
> Swapping it up with a minus to properly deduct time would be more apropriate rather than revertig it to the custom behavior we've had before.

Will try that, thanks!

**Comment by kaninhot004** [comment]
> This would revert the intended fix.
> Swapping it up with a minus to properly deduct time would be more apropriate rather than revertig it to the custom behavior we've had before.

Please help me, this is what I've tried.

```
time += -(time * sd->delayrate / 100);
time += -time * sd->delayrate / 100;
time -= sd->delayrate / 100;
time -= time * sd->delayrate / 100;
```

All of these are not working.

**Comment by randell1993** [comment]
Okay I fixed it

`		if (sd->delayrate != 100) // bonus bDelayRate
			time += time * sd->delayrate / 100;`

this became a problematic statement as this is read as 
time = time + time *  sd->delayrate / 100

so just remove the + in time **+**= time * sd->delayrate / 100;`

`time = time * sd->delayrate / 100`

now time will now be equal to time multiplied to your delay rate

I hope this make sense.

**Comment by kaninhot004** [comment]
> Okay I fixed it
> 
> ` if (sd->delayrate != 100) // bonus bDelayRate time += time * sd->delayrate / 100;`
> 
> this became a problematic statement as this is read as
> time = time + time * sd->delayrate / 100
> 
> so just remove the + in time **+**= time * sd->delayrate / 100;`
> 
> `time = time * sd->delayrate / 100`
> 
> now time will now be equal to time multiplied to your delay rate
> 
> I hope this make sense.

I already code it like that. You can see in File Changed section.

**Comment by randell1993** [comment]
oh didnt see it ahahahaha

welp.

**Comment by Daegaladh** [comment]
Will be fixed in #6240

**Pull request closed without merging**
