### PR TITLE
groups.conf import support

### PR DESCRIPTION
**Pull request by cydh**
* Moved hardcoded groups.conf filename on `src/map/pc_groups.c` to `conf/map_athena.conf`
* Defined the path with `groups_conf_file: conf/groups.conf`. So in `conf/import/maps_conf.txt` file (imported map_athena.conf file) can be used to redefine the path, `groups_conf_file: conf/import/groups.conf`

Signed-off-by: Cydh Ramdh <house.bad@gmail.com>

### CODE REVIEW

**Comment by cydh** [comment]
somehow the comment in `conf/import-tmpl/groups.conf` is weird

**Comment by aleos89** [comment]
Is a comment really needed in it since all the other import files are empty?

**Comment by cydh** [comment]
xD I like comments.
I'll remove it and add import for atcommand_athena.conf

**Comment by aleos89** [comment]
:) Sounds good.

**Comment by cydh** [comment]
I'll drop this. lol
I'll include this change with #252

**Comment by cydh** [comment]
cloossseee

**Pull request closed without merging**
