### PR TITLE
Basic RODEX support

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: #1567 

* **Server Mode**: Both

* **Description of Pull Request**: 

Adds basic support for the new mail UI RODEX.
Thanks to @RagnarokNova, @Atemo, @aleos89  and everyone else that helped me with this.

### CODE REVIEW

**Comment by jezznar** [comment]
AWESOME! :D I'll test this out

**Comment by jezznar** [comment]
Tested Scenarios (Default configuration)
A. Sending Mails
- [x] Blank Mails
- [x] Text Mails
- [x] Zeny Mails
- [x] Item Mails
- [x] Item + Zeny Mails
- [x] Item + Zeny + Text Mails

B. Receiving Mails
- [x] Blank Mails
- [x] Zeny Mails
- [x] Text Mails
- [x] Item Mails
- [ ] Item + Zeny Mails
- [ ] Item + Zeny + Text Mails
- [ ] Notification
Bugs:
1. Users can send mails when mail_daily_count is < 0 (e.g. -1)
2. Users can't send mails when mail_daily_count is 0
3. In Receiving Mails [Item + Zeny or Item + Zeny + Mail], if the users claim the zeny first, they will not be able to receive the item and it disappears permanently.
4. In Receiving Mails [All types], Users do not get any notification when they receive mails while they are offline when mail_show_status is set to 2. They start receiving notifications when they login then relogin.

**Comment by hazimjauhari90** [comment]
just done quick testing... testing done by using 2017-03-15cRagexeRE client.
i also experienced & encountered bugs as reported by @jezznar (no 3 & 4).

3. In Receiving Mails [Item + Zeny or Item + Zeny + Mail], if the users claim the zeny first, they will not be able to receive the item and it disappears permanently.
4. In Receiving Mails [All types], Users do not get any notification when they receive mails while they are offline when mail_show_status is set to 2. They start receiving notifications when they login then relogin.

**Comment by jenkijo** [comment]
I only can send mail to other players if they are online. Is it a bug?

**Comment by jezznar** [comment]
@jenkijo maybe you can specify your client version so we can also check from our side

**Comment by jenkijo** [comment]
@jezznar I use 2015-11-04 client

**Comment by Lemongrass3110** [comment]
Since the name lookup is done via character server you should be able to send even if the player is offline.
I dont know what causes the problem for you, it works perfectly fine for me.

**Comment by jezznar** [comment]
@Lemongrass3110 is the latest commit meant to resolve these? :)
Bugs:
- [ ] Users can send mails when mail_daily_count is < 0 (e.g. -1)
- [ ] Users can't send mails when mail_daily_count is 0
- [ ] In Receiving Mails [Item + Zeny or Item + Zeny + Mail], if the users claim the zeny first, they will not be able to receive the item and it disappears permanently.
- [ ] In Receiving Mails [All types], Users do not get any notification when they receive mails while they are offline when mail_show_status is set to 2. They start receiving notifications when they login then relogin.

**Comment by Lemongrass3110** [comment]
It just fixes auto-merging to master and resolves conflicts from recent master updates. I will try to resolve the issues soon.

**Comment by Lemongrass3110** [comment]
Negative value for mail_daily_count is not possible:
```
[Warning]: Value for setting 'mail_daily_count': -1 is invalid (min:0 max:214748
3647)! Defaulting to 100...
```

**Comment by Lemongrass3110** [comment]
Since I was asked how to revert your database from RODEX to the old mail system when you accidently updated the wrong database(seriously please make backups before applying such changes).
Here is a little guide:

Check all mails with more than one attachment(this is not supported by the old mail system):
```
select `id`
from `mail_attachments`
group by `id`
having count(`id`) > 1;
```

Revert the structure and insert the data from the new structue back into the old one:
```
RENAME TABLE `mail` TO `mail_rodex`;

 --
 -- Table structure for table `mail`
 --
 
 CREATE TABLE `mail` (
   `id` bigint(20) unsigned NOT NULL auto_increment,
   `send_name` varchar(30) NOT NULL default '',
   `send_id` int(11) unsigned NOT NULL default '0',
   `dest_name` varchar(30) NOT NULL default '',
   `dest_id` int(11) unsigned NOT NULL default '0',
   `title` varchar(45) NOT NULL default '',
   `message` varchar(255) NOT NULL default '',
   `time` int(11) unsigned NOT NULL default '0',
   `status` tinyint(2) NOT NULL default '0',
   `zeny` int(11) unsigned NOT NULL default '0',
   `nameid` smallint(5) unsigned NOT NULL default '0',
   `amount` int(11) unsigned NOT NULL default '0',
   `refine` tinyint(3) unsigned NOT NULL default '0',
   `attribute` tinyint(4) unsigned NOT NULL default '0',
   `identify` smallint(6) NOT NULL default '0',
   `card0` smallint(5) unsigned NOT NULL default '0',
   `card1` smallint(5) unsigned NOT NULL default '0',
   `card2` smallint(5) unsigned NOT NULL default '0',
   `card3` smallint(5) unsigned NOT NULL default '0',
   `option_id0` smallint(5) unsigned NOT NULL default '0',
   `option_val0` smallint(5) unsigned NOT NULL default '0',
   `option_parm0` tinyint(3) unsigned NOT NULL default '0',
   `option_id1` smallint(5) unsigned NOT NULL default '0',
   `option_val1` smallint(5) unsigned NOT NULL default '0',
   `option_parm1` tinyint(3) unsigned NOT NULL default '0',
   `option_id2` smallint(5) unsigned NOT NULL default '0',
   `option_val2` smallint(5) unsigned NOT NULL default '0',
   `option_parm2` tinyint(3) unsigned NOT NULL default '0',
   `option_id3` smallint(5) unsigned NOT NULL default '0',
   `option_val3` smallint(5) unsigned NOT NULL default '0',
   `option_parm3` tinyint(3) unsigned NOT NULL default '0',
   `option_id4` smallint(5) unsigned NOT NULL default '0',
   `option_val4` smallint(5) unsigned NOT NULL default '0',
   `option_parm4` tinyint(3) unsigned NOT NULL default '0',
   `unique_id` bigint(20) unsigned NOT NULL default '0',
   `bound` tinyint(1) unsigned NOT NULL default '0',
   PRIMARY KEY  (`id`)
 ) ENGINE=MyISAM;

insert into `mail`
(`id`,`send_name`,`send_id`,`dest_name`,`dest_id`,`title`,`message`,`time`,`status`,`zeny`,`nameid`,`amount`,`refine`,`attribute`,`identify`,`card0`,`card1`,`card2`,`card3`,`option_id0`,`option_val0`,`option_parm0`,`option_id1`,`option_val1`,`option_parm1`,`option_id2`,`option_val2`,`option_parm2`,`option_id3`,`option_val3`,`option_parm3`,`option_id4`,`option_val4`,`option_parm4`,`unique_id`,`bound`)
select
`m`.`id`,`send_name`,`send_id`,`dest_name`,`dest_id`,`title`,`message`,`time`,`status`,`zeny`,`nameid`,`amount`,`refine`,`attribute`,`identify`,`card0`,`card1`,`card2`,`card3`,`option_id0`,`option_val0`,`option_parm0`,`option_id1`,`option_val1`,`option_parm1`,`option_id2`,`option_val2`,`option_parm2`,`option_id3`,`option_val3`,`option_parm3`,`option_id4`,`option_val4`,`option_parm4`,`unique_id`,`bound`
from `mail_rodex` `m`
left join `mail_attachments` `ma`
on `m`.`id` = `ma`.`id`;
```

If everything is fine and you do not want to keep the tables:
```
-- Make sure all your data is safe before dropping the source tables
-- drop table `mail_rodex`;
-- drop table `mail_attachments`;
```

Hope this can help you guys with testing.

**Comment by jezznar** [comment]
@Lemongrass3110 or they can just add this at the top of the SQL query during table creation
`ALTER TABLE `mail_backup`
  RENAME TO `mail`;`

**Comment by Lemongrass3110** [comment]
Of course that would be the better option, but I got some PMs of people who accidently migrated their live data without creating a backup first.

**Comment by sikiro** [comment]
latest revision is showing the following. 

image

**Comment by V0rr** [comment]
I'm using **2016-02-03a** and it works perfectly. Thank you Lemon

**Comment by jezznar** [comment]
Client: 2015-11-04
Hash: 264af55
- [x] Users can send mails when mail_daily_count is < 0 (e.g. -1)
- [x] Users can't send mails when mail_daily_count is 0
- [x] In Receiving Mails [Item + Zeny or Item + Zeny + Mail], if the users claim the zeny first, they will not be able to receive the item and it disappears permanently.
~- [ ] In Receiving Mails [All types], Users do not get any notification when they receive mails while they are offline when mail_show_status is set to 2. They start receiving notifications when they login then relogin.~

Awesome and good to go from my side :)

**Comment by admkakaroto** [comment]
@jezznar The player receiving offline email has not yet been fixed.

**Comment by jezznar** [comment]
@admkakaroto Yes, I crossed it out as it only happens when mail_show_status is set to 2. A very minor bug. I've edited my previous post to "All major bugs fixed."

**Comment by admkakaroto** [comment]
I use mail_show_status: 1 and even then the problem happens. But of course it's not a serious problem, that's the least.

Congratulations @Lemongrass3110 .

**Comment by V0rr** [comment]
@jezznar after you pick the zeny, making the item disappears, if you close the mail and click on **Update** icon the item will be there.
I'll change my *mail_show_status* as well . Thank you for the reports

**Comment by sikiro** [comment]
i can confirm the following:

on Client 2017-03-15cRagexeRE i am able to 
A. Sending Mails

-  Blank Mails
-  Text Mails
-  Zeny Mails
-  Item Mails
-  Item + Zeny Mails
-  Item + Zeny + Text Mails

- B. Receiving Mails
-  Blank Mails
-  Zeny Mails
-  Text Mails
-  Item Mails
-  Item + Zeny Mails
-  Item + Zeny + Text Mail

i am using this patch [20170315.zip](https://github.com/rathena/rathena/files/1079395/20170315.zip) on my server i am also using this alongside achievements for testing purposes.

Link to Client [https://ragemu.org/index.php](url)

**Comment by Lemongrass3110** [comment]
Any further bugs and 2017 support will be added later on at master. So please report every issue you find in the future!

**Comment by jezznar** [comment]
Awesome!!!

**Pull request merged**
