### PR TITLE
Web token feature

### PR DESCRIPTION
**Pull request by secretdataz**
* **Addressed Issue(s)**: 
* **Server Mode**: Irrelevant
* **Description of Pull Request**: 
The login server will now send randomized authentication token with AC_ACCEPT_LOGIN3 packet for use with various web services recent clients use.
Please note that this implementation does not use a secure random string generator to generate the token.

### CODE REVIEW

**Comment by cahya1992** [comment]
just want to know this pull request have related with new function for emblem guild?

**Comment by LolyAll** [comment]
Let's face it, this PR is useless.

**Comment by Lemongrass3110** [comment]
> 
> 
> Let's face it, this PR is useless.

@LolyAll any reason for a comment like this?
This is required for some of the 2020 client features. So personally I would not consider it useless.

**Comment by attackjom** [comment]
> Let's face it, this PR is useless.

without this  you can't use guild emblem in 2020 clients.

**Comment by makuexile** [comment]
still can't use guild emblem after update my database using 20200401 client.

**Comment by secretdataz** [comment]
Guild emblem requires an external REST service. This PR is just a part that rAthena need to handle.

**Pull request merged**
