### PR TITLE
Added support for RODEX 2017

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: None

* **Server Mode**: Both

* **Description of Pull Request**: 
Adds support for the 2017 version of RODEX.
Thanks to everyone that donated towards the feature goal. 👍

### CODE REVIEW

**Comment by hazimjauhari90** [comment]
Finally.. the kraken is released. Heh. xD

**Comment by Lemongrass3110** [comment]
One of the krakens :-P
Another one is about to emerge soon as well. :-)

**Comment by hazimjauhari90** [comment]
I think rodex 2017 was released by gravity on 2017-04-19bRagexeRE client.

**Comment by admkakaroto** [comment]
Working fine on 2017-05-31bRagexeRE

**Comment by jenkijo** [comment]
Working fine on 2017-06-14bRagexeRE

**Comment by Lemongrass3110** [comment]
Working fine on 2017-06-28bRagexeRE as well :-)

**Pull request merged**
