### PR TITLE
Fix Rock Ridge enchantment stones

### PR DESCRIPTION
**Pull request by teededung**
* **Addressed Issue(s)**: none

* **Server Mode**: Renewal

* **Description of Pull Request**: 

Missing item id 29026 - Def20
Corrected item bonus for 4893 - Def15

### CODE REVIEW

**Comment by Atemo** [comment]
hmm anything else?

**Comment by teededung** [comment]
@Atemo I don't know if this item 4815 is correct. Please check it.
The other enchantment stones are right.

**Comment by Atemo** [comment]
Our 4815 seems fine according to the description `MATK + 6, 변동 캐스팅 시간 4% 단축. `

**Comment by Atemo** [comment]
Thanks !

**Pull request merged**
