### PR TITLE
Fix soulball packet in client 20200724ragexeRE+

### PR DESCRIPTION
**Pull request by attackjom**
* **Addressed Issue(s)**: -

* **Server Mode**: Renewal

* **Description of Pull Request**: 
In client 20200724ragexeRE+  soulball visual packet is seperated from spiritball visual packet
so, this will fix thats.

seperate soulball packet from spiritball packet in client 20200724ragexeRE+

### CODE REVIEW

**Comment by sianromantic** [comment]
cccc

**Comment by attackjom** [comment]
@sianromantic  Did you define PACKETVER_RE_NUM ?

**Comment by sianromantic** [comment]
> @sianromantic Did you define PACKETVER_RE_NUM ?
> 
> in where you define PACKETVER.

src\custom\defines_pre.hpp
<details>
  <summary>content</summary>

// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

#ifndef CONFIG_CUSTOM_DEFINES_PRE_HPP
#define CONFIG_CUSTOM_DEFINES_PRE_HPP

/**
 * rAthena configuration file (http://rathena.org)
 * For detailed guidance on these check http://rathena.org/wiki/SRC/config/
 **/



#endif /* CONFIG_CUSTOM_DEFINES_PRE_HPP */
#define PACKETVER 20200724


</details>

**Comment by attackjom** [comment]
> > @sianromantic Did you define PACKETVER_RE_NUM ?
> > in where you define PACKETVER.
> 
> @attackjom
> src\custom\defines_pre.hpp
> 
> defines_pre content
> // Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
> // For more information, see LICENCE in the main folder
> 
> #ifndef CONFIG_CUSTOM_DEFINES_PRE_HPP
> #define CONFIG_CUSTOM_DEFINES_PRE_HPP
> 
> /**
> 
> * rAthena configuration file (http://rathena.org)
> * For detailed guidance on these check http://rathena.org/wiki/SRC/config/
>   **/
> 
> #endif /* CONFIG_CUSTOM_DEFINES_PRE_HPP */
> #define PACKETVER 20200724
> 
> digression
> did enchantgrade#5445 it work !?
> i dont know how to open enchantgrade UI...

put this to define_pre.hp

#define PACKETVER_RE_NUM 20200724

**Comment by sianromantic** [comment]
it same

**Review by aleos89 — APPROVED** [review]

**Review by Lemongrass3110 — APPROVED** [review]

**Review by aleos89 — APPROVED** [review]

**Pull request merged**
