### PR TITLE
Lasagna Boss Missing

### PR DESCRIPTION
**Pull request by admkakaroto**
* **Addressed Issue(s)**: 
* **Server Mode**: RE
* **Description of Pull Request**: Added spawn of lasagna boss who was missing.
* **Font**: https://www.divine-pride.net/database/monster/3505

### CODE REVIEW

**Comment by Atemo** [comment]
`Big Eggring`'s monster stats and the slaves's stats need to be updated (mob_db) as well

**Comment by admkakaroto** [comment]
Sorry for the delay, I'll update this PR.

**Comment by Lemongrass3110** [comment]
@admkakaroto any update on this?

**Comment by Atemo** [comment]
User deleted the branch.

**Comment by admkakaroto** [comment]
Sorry I was traveling to work.

**Pull request closed without merging**
