### PR TITLE
Fixed dead monsters stuck after killed

### PR DESCRIPTION
**Pull request by Daegaladh**
*Thanks to @Hope8888

* **Addressed Issue(s)**: #5064 

* **Server Mode**: Both

* **Description of Pull Request**:  Avoids monsters moving after dead so they don't get stuck on screen

### CODE REVIEW

**Comment by Daegaladh** [comment]
Still happens on some cases (when the monster dies while you're moving and the monsters gets momentarily out of sight range), we'll need to dig deeper and find the ultimate cause

**Comment by saya9200** [comment]
I just tested this. Before applying the pull request, it happened very very often. Now it doesnt happen at all to me.

**Comment by Daegaladh** [comment]
> I just tested this. Before applying the pull request, it happened very very often. Now it doesnt happen at all to me.

Unfortunately it causes some undesirable side effects (monsters stopping and other weird stuff), we need to check this thoroughly

**Comment by lighta** [comment]
You could try to reduce this check only for mob and not al the BL, just to see if that reduce the side effect.

**Comment by Daegaladh** [comment]
> 
> 
> You could try to reduce this check only for mob and not al the BL, just to see if that reduce the side effect.

They still don't move correctly :/

**Comment by KrokusPokus** [comment]
Not sure if it makes any difference, but I have been using a similar check in clif_move() for a  while now and haven't noticed anything weird. Can you confirm that this causes the same side effects for you? (And what's the best way to trigger the side effects?)

```
void clif_move(struct unit_data *ud)
{
	unsigned char buf[16];
	struct view_data* vd;
	struct block_list* bl = ud->bl;
	struct status_change *sc = NULL;

/*TEST*/	struct status_data *status;
/*TEST*/	status = status_get_status_data(bl);
/*TEST*/	if (status->hp == 0)
/*TEST*/		return;

	vd = status_get_viewdata(bl);
...

```

**Comment by attackjom** [comment]
this fix from Hercules https://github.com/HerculesWS/Hercules/commit/c04d79112575bc4e756231f8b447378dbab951ad

can solve the issue "when the monster dies while you're moving and the monsters gets momentarily out of sight range".

**Review by Playtester — APPROVED** [review]

**Review by Daraen1 — APPROVED** [review]
It seems to be good for me, work fine ;)

GG!

**Review by aleos89 — APPROVED** [review]

**Pull request merged**
