### PR TITLE
SC Value clean up & SC Documentation

### PR DESCRIPTION
**Pull request by cydh**
* Clean up some SC Values asisgnment (val1 ~ val4)
  * SC_MTF_MLEATKED: val1: Endure level, val2: Rate to cast Endure, val3: Neutral element resistance
  * SC_MTF_CRIDAMAGE: val1: +Critical rate. Also fixed its assignment
  * SC_MTF_RANGEATK: val1: +Ranged attack damage
  * SC_MTF_MATK: val1: +% MAtk
  * SC_MTF_ASPD: val1: +ASPD, val2: +Hit
  * SC_ILLUSIONDOPING: val2: -Hit
  * SC_FULL_THROTTLE: val3: +All status
  * SC_SPEEDUP0: val1: +Speed (previously is hardcoded)
  * SC_TELEKINESIS_INTENSE: val4: Variable casttime reduction, previously using val2 with SP consumption
  * SC__FEINTBOMB: val2: SP reduction each interval
  * SC_LIGHT_OF_REGENE only heal HP amount on revive
* Init documentation doc/status_change.txt for values of each SC, should be useful for sc_start/2/4 scripts (not complete yet)
* Item DB Updated
  * Following SC values changes
  * Fixed script Vitata500_To_Throw (13282), missing MaxSP bonus
  * Fixed inconsistency of constant name for SCs
  * Fixed bonus for Bluefin_Tuna_Skewer (22771), should be +30% ATK
  * Fixed bonus for Sea_Bream_Skewer (22772), should be +30% MATK

Signed-off-by: Cydh Ramdh <house.bad@gmail.com>

### CODE REVIEW

**Comment by cydh** [comment]
@nanakiwurtz update ur local, checkout this branch and update the doc with urs!

**Comment by nanakiwurtz** [comment]
Tonight you'll have to show me how.

**Comment by Atemo** [comment]
Someone is still on this ?

**Comment by cydh** [comment]
I'll merge this to master first

**Comment by cydh** [comment]
oh lol, merge from master to here isn't good idea, everything are look so weird now. I'll reopen this xD

**Pull request closed without merging**
