### PR TITLE
Fixed atcommand use in playerless scripts

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: #8886

* **Server Mode**: Both

* **Description of Pull Request**: 
Made the dummy character creation C++ safe.

Thanks to @Beginerxxxxx

### CODE REVIEW

**Comment by fab10Carvalho** [comment]
simple one

```
int32 atcommand_sub(struct script_state* st,int32 type) {
	TBL_PC *sd, dummy_sd;
	static map_session_data dummy_sd;
	TBL_PC *sd;
```

**Comment by fab10Carvalho** [comment]
```
int32 atcommand_sub(struct script_state* st,int32 type) {
-	TBL_PC *sd, dummy_sd;
+	static map_session_data dummy_sd;
+	TBL_PC *sd;
	int32 fd;
	const char *cmd;

+	if (dummy_sd.group == nullptr) {
+		// Init Dummy SD Group ID, Level, & permissions
+		dummy_sd.group_id = 99;
+		pc_group_pc_load(&dummy_sd);
+	}

	cmd = script_getstr(st,2);

	if (st->rid) {
@@ -15657,19 +15664,14 @@ int32 atcommand_sub(struct script_state* st,int32 type) {
	} else { //Use a dummy character.
		sd = &dummy_sd;
		fd = 0;
+		safestrncpy(dummy_sd.status.name, "", NAME_LENGTH);

-		memset(&dummy_sd, 0, sizeof(TBL_PC));
		if (st->oid) {
			struct block_list* bl = map_id2bl(st->oid);
-			memcpy(&dummy_sd.bl, bl, sizeof(struct block_list));
			if (bl->type == BL_NPC)
				safestrncpy(dummy_sd.status.name, ((TBL_NPC*)bl)->name, NAME_LENGTH);
			sd->mapindex = (bl->m > 0) ? map_id2index(bl->m) : 0;
		}

-		// Init Group ID, Level, & permissions
-		sd->group_id = 99;
-		pc_group_pc_load( sd );
	}
```

**Comment by coookie1010** [comment]
I found a bug that will crash server too if use a teleport.

Used script
`
-	script	8886#ci	-1,{
OnInit:
	atcommand "@warp prontera 100 141";
	end;
}
`

**Comment by Lemongrass3110** [comment]
> I found a bug that will crash server too if use a teleport.
> 
> Used script
> 
> ```
> -	script	8886#ci	-1,{
> OnInit:
> 	atcommand "@warp prontera 100 141";
> 	end;
> }
> ```

@coookie1010 Please open a new issue.

**Pull request merged**
