### PR TITLE
Fixes to some quests and typo errors.

### PR DESCRIPTION
**Pull request by AtlantisRO**
- Fix to NPC [Iromo's Mother#ep3_2] to fix a bug that restarts the quest.

- A minor fix to some typo error.

- Pre-RE: Fixed the position of NPC [Promotional Staff#iz] from izlude before renewal.

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
- [x] c5cd672 is good to merge
- [ ] 3cd6774 needs confirmation from our leaks
- [ ] 438e33a looks good, but we need to check how the official script handles this, since it might only be a conversion problem.
- [ ] 9c99c5c sounds reasonable and should also be recheck with our aegis sources.

**Comment by Lemongrass3110** [comment]
438e33a is good to merge, this bug comes from strict conversion of the aegis script. It also has this error.

**Comment by Lemongrass3110** [comment]
9c99c5c confirmed with our aegis sources.

**Comment by AtlantisRO** [comment]
The position of the npc [Promotional Staff#iz] was changed in commit [a1c1238](https://github.com/rathena/rathena/commit/a1c12384fa63078e12c43e89ffdb181c517ec30d) to fit with the redisign of izlude map.

After that were differenced the localization from re and pre-re version, but without changing the position back.

However, the correct facing is 5 (according to the previous position of rAthena's script), not 6 as in the commit. Sorry about that.

**Comment by Lemongrass3110** [comment]
Thanks for looking that up! Would you mind to create another small follow up so that this can be merged together with it? It's your work after all. :-)

**Comment by AtlantisRO** [comment]
I added a small commit f3fa99f to change the position from 6 to 5. Would you explain how to do a follow up?

**Comment by aleos89** [comment]
@AtlantisRO You did exactly what he meant. :+1:

**Comment by AtlantisRO** [comment]
Thank you both :)

**Comment by Lemongrass3110** [comment]
Thanks @AtlantisRO :-)

**Pull request merged**
