### PR TITLE
create Soul reaper job change quest

### PR DESCRIPTION
**Pull request by BotGigo**
* **Addressed Issue(s)**: 

Missing quest for soul reaper job.

* **Server Mode**: 

Renewal.

* **Description of Pull Request**: 

Create the files in db for quest and instace for the soul repaer job change quest and add the script for the quest.

### CODE REVIEW

**Comment by Atemo** [comment]
Thanks you for your work. Before any review I have a few questions.
Was your work done based on replay?
Can you add a comment later where you added your custom dialog?

**Comment by BotGigo** [comment]
> Thanks you for your work. Before any review I have a few questions. Was your work done based on replay? Can you add a comment later where you added your custom dialog?

Yes, the script is based on the video, is written in the script header, so the dialogs are the ones that appear in the video, and yes, lately I'll comment the fill dialogs .

**Comment by Atemo** [comment]
Did you use a replay parser?

**Comment by BotGigo** [comment]
> Did you use a replay parser?

What do you mean by that?

**Pull request closed without merging**
