### PR TITLE
Initial release 'premium' storage

### PR DESCRIPTION
**Pull request by cydh**
- Adapting official multiple storages.
- Added config to defines storages. See conf/import-tmpl/inter_server.conf.
- Added packet IZ `0x388c` for sending storage definitions.
- Added script command `openstorage2` to open premium storages.
- Removed `sd->storage_size`, replaced by `sd->storage.max_amount`. The value is defined in inter_server.conf in storage entries.
---

All naming are my preferences, can be cleaned up

### CODE REVIEW

**Comment by cydh** [comment]
my sample config
```
storages: (
{
	// Default storage
	// DO NOT CHANGE THIS EXCEPT YOU KNOW WHAT YOU ARE DOING
	id: 0
	name: "Storage"
	table: "storage"
	//max: 600
}
,{
	id: 1
	name: "Premium"
	table: "storage_1"
	max: 100
}
,{
	id: 2
	name: "VIP"
	table: "storage_2"
	max: 300
}
)
```

sample NPC
```
prontera,146,162,5	script	Premium Kafra#prt	4_F_KAFRA4,{
	mes "[ Kafra ]";
	mes "Which storage do you want to open?";
	next;
	switch(select("Normal Storage","Premium Storage","VIP Storage")) {
		case 1:
			mes "[ Kafra ]";
			mes "Storage will be opened. Thank you";
			close2;
			openstorage;
			break;
		case 2:
			mes "[ Kafra ]";
			mes "Premium storage will be opened";
			close2;
			openstorage2(1,STOR_MODE_GET|STOR_MODE_PUT);
			break;
		case 3:
			mes "[ Kafra ]";
			if (vip_status(1)) {
				.@mode = STOR_MODE_GET|STOR_MODE_PUT;
				mes "VIP will be opened. Thank you";
			} else {
				.@mode = STOR_MODE_GET;
				mes "Seems you're no longer VIP anymore. You only can take the items.";
			}
			close2;
			openstorage2(2,.@mode);
			break;
	}
	end;
}
```

**Comment by lucasoli** [comment]
Thanks for this awesome feature Cydh! Thank you very much! =]

**Comment by Drakkus** [comment]
Thank you Cydh. indeed very useful

**Comment by cydh** [comment]
I'll merge this to cleanup/storages_optimization

**Pull request merged**
