### PR TITLE
Added windows specific socket timeout code

### LINKED ISSUE #794: socket timeout options on WinAPI use DWORD, not struct timeval
In https://github.com/rathena/rathena/commit/f67f82c472585bb5fdb4860deedf32cccb508f98 a cascade of 'timeout' parameters was added, eventually ending at setsocketopts:

```
    if(delay_timeout){
        struct timeval timeout;
        timeout.tv_sec = delay_timeout;
        timeout.tv_usec = 0;

        if (sSetsockopt (fd, SOL_SOCKET, SO_RCVTIMEO, (char *)&timeout,sizeof(timeout)) < 0)
            ShowError("setsocketopts: Unable to set SO_RCVTIMEO timeout for connection #%d!\n");
        if (sSetsockopt (fd, SOL_SOCKET, SO_SNDTIMEO, (char *)&timeout,sizeof(timeout)) < 0)
            ShowError("setsocketopts: Unable to set SO_SNDTIMEO timeout for connection #%d!\n");
    }
```

According to MSDN docs:

```
SO_RCVTIMEO DWORD   Sets the timeout, in milliseconds, for blocking receive calls. 
SO_SNDTIMEO DWORD   The timeout, in milliseconds, for blocking send calls. 
```

So there is a platform incompatibility, which results in a parameter type mismatch. This is the cause why in https://github.com/rathena/rathena/issues/793 I saw a 21-second delay.

### PR DESCRIPTION
**Pull request by Lemongrass3110**
Added socket code for windows that respects our given timeout.
Also added some more ifndef checks to some stat reporting functions.
Updated the MSDN reference link.
Fixed the delay being milliseconds on windows, thanks to @theultramage
Fixes #794 on windows.

### CODE REVIEW

**Comment by theultramage** [comment]
Ouch, that windows case looks as painful as I imagined. You could help it a bit by flattening the if-return-else error handling code (remove 'else' scope and unindent, because the 'if' scope ends with a 'return').

**Comment by theultramage** [comment]
https://gist.github.com/theultramage/e22b0013407bf85e0ab2cd755ceb1973 is what I had in mind in my previous post. You chose to do a fake while() scope and break; out of it in the positive case, and folded the three error cases into one block of code. That's quite rough, I prefer to stick with the duplicated code for more clarity. I do remember that we used to do do { ... } while( 0 ); to indicate dummy scope. Just some extra thoughts.

**Comment by Lemongrass3110** [comment]
Yeah I understood what you were getting at. That was just my solution of removing the duplicate code, since I personally prefer not duplicating code if it is useless. If it would not be fitting onto one screen I would possibly also duplicate the code but like this I think it's quite useless.
I also though about the dummy scope you mentioned, but I thought that I could just use the first if as while entry condition to get the same effect and without having to add one level of identitation for the pseudo scope again.

**Comment by theultramage** [comment]
Okay, I see. I was just worried about the while() thing, because I had to read the whole code listing twice to realize it's not intended to loop and just forms a dummy breakable scope.

**Comment by Lemongrass3110** [comment]
Yeah you are right it might be misleading. At least I should (have) put a comment above it to make it clear for anyone reading the code.

**Pull request merged**
