### PR TITLE
Corrected Tiucknuc mob name into Tiyanak in /npc/re/quest/quest_malaya.txt

### PR DESCRIPTION
**Pull request by musashi076**
To avoid confusion in Tiyanak Mob Hunt.

### CODE REVIEW

**Comment by cydh** [comment]
@Atemo @nanakiwurtz @Luciar can u check on official/Aegis?

**Comment by Atemo** [comment]
It's Tiucknuc in aegis, maybe a mistake since it doesn't follow the mob name..?

**Comment by musashi076** [comment]
based in pRO and iRO. I think aegis pronounce it in their native pronounciation. 
Tiucknuc = Tiyanak
Mongkukuromu = Mangkukulam (Witch here in PH)
Bongisungisu= Bungisngis

i was doing the Port malaya quest in normal gameplay, also can we put the Lost Belongings Drop of Tiyanak/Tiucknuc in quest since it doesn't drop normally? After i saw the official gameplay, they only drop when in quest and put directly in your inventory. I tried the hercules script and modified it to limit drop per quest npc (1st npc=2, 2nd=7, 3rd=3, 4th=5)
based in here.
http://irowiki.org/wiki/Bakonawa_Extermination

**Comment by cydh** [comment]
it makes sense. xD just like write English in Japanese

**Pull request merged**
