### PR TITLE
Biolab Edda Weapon

### PR DESCRIPTION
**Pull request by attackjom**
* **Addressed Issue(s)**: -

* **Server Mode**: Renewal

* **Description of Pull Request**: 
- Add Biolab EDDA weapon and their enchant itemDB
- All of itemscript make from translation in divine-pride.net (Thanks to "Sigma")
https://www.divine-pride.net/forum/index.php?/topic/3592-kro-edda-biolab-enchant/

### CODE REVIEW

**Comment by Atemo** [comment]
Why did you close it @attackjom ? The review is delayed (I'm alone to do that, well sorry) but on going.
For the story I started to review the previous PR you closed and I didn't finish it here, the review will be lost 2 times.

**Comment by attackjom** [comment]
> Why did you close it @attackjom ? The review is delayed (I'm alone to do that, well sorry) but on going.
> For the story I started to review the previous PR you closed and I didn't finish it here, the review will be lost 2 times.

I'm sorry. I think this is forgotten because no one to comment or label / review it.

**Comment by attackjom** [comment]
@Atemo  Thank you. I have fix these from your suggestion.

**Comment by Atemo** [comment]
Thanks @attackjom

**Pull request merged**
