### PR TITLE
Update mobs for Sky Fortress

### PR DESCRIPTION
**Pull request by Latiosu**
* **Addressed Issue(s)**: https://github.com/rathena/rathena/pull/3586#discussion_r394506033

* **Server Mode**: Renewal

* **Description of Pull Request**: 
Updates mobs according to Divine-Pride.net DB for majority of values and RMS DB for missing values (Attack Motion and Modes).

**Screenshot Example of Mob ID 3473:**
image

### CODE REVIEW

**Comment by reunite-ro** [comment]
If im not mistaken, rAthena didnt implement this yet because of the random option details.

Example : https://irowiki.org/wiki/Vicious_Mind_Weapon_Enchants

**Comment by Akkarinage** [comment]
>  and RMS DB for missing values
RMS doesn't use official data, they use data found in emulators and then make the rest up based on best-guess. There are several topics on this in rA, Herc and RMS itself.

**Comment by Latiosu** [comment]
> > and RMS DB for missing values
> 
> RMS doesn't use official data, they use data found in emulators and then make the rest up based on best-guess. There are several topics on this in rA, Herc and RMS itself.

Got it, I'll try and update it just based on Divine-Pride/kRO information.

**Comment by Lemongrass3110** [comment]
Closing this since #3586 was updated by @Atemo.

**Pull request closed without merging**
