### PR TITLE
Updated max recovery weight to 70% for renewal

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: #2622

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Added a new battle config for renewal.
  * Adjusted the battle config to support dropping the recovery weight to 0.

### CODE REVIEW

**Comment by Haikenz** [comment]
When the weight reaches 50%, the weight limit message appears. was to appear when it reaches 70%

**Comment by syracuase** [comment]
@Haikenz That is more of a client based problem

**Comment by spinzaku** [comment]
hello @Haikenz when you reach 70% the correct weight status icon show up? does it show 70%? or 50%?

**Comment by hendra814** [comment]
50% form max weight limit not 70%
PS: i already replace the state icon

screenrathena075

**Comment by ecdarreola** [comment]
Works fine except for the red text that changes at 50% but the icon is showing at 70%. Thanks!

**Comment by BrOgBr** [comment]
@ecdarreola So doesn't works fine haha.

**Comment by vstumpf** [comment]
The red text is a client change. If you don't have the right client, you'll have to manually diff it.

**Comment by functor-x** [comment]
Starting from 2017-10-25bRagexeRE it is possible to set percentage for "red text" by sending 0xADE packet.

0x0ADE <percentage>.L

EXE has to show message with line 3312 from "msgstringtable.txt" if it reaches percentage you set.

P.S. I haven't tested it.

**Comment by hendra814** [comment]
@haikenz, Sorry my mistake, i test the wrong rathena server.
ok  i will test it again.

**Comment by Lemongrass3110** [comment]
Thanks a lot @functor-x :-)

**Comment by ecdarreola** [comment]
It works fine now! Thanks @functor-x and @Lemongrass3110 !

at 69%
image

at 70%
image

**Comment by Lemongrass3110** [comment]
Still sucks that they resued the status icon though... :-(

**Pull request merged**
