### PR TITLE
Fix broken portal in eden HQ

### PR DESCRIPTION
**Pull request by crazystorm2017**
* **Addressed Issue(s)**: 
None

* **Server Mode**: 
Renewal

* **Description of Pull Request**:

### CODE REVIEW

**Comment by Jeybla** [comment]
Before:
image
After:
image

Why is this fix needed?

**Comment by crazystorm2017** [comment]
Try Coming from the inside and go outside :o

**Comment by crazystorm2017** [comment]
moc_para01 47 37 is a warp portal already thus making you go back when you try to exit.

**Comment by Jeybla** [comment]
Is your warp portal custom, or why can't I see one?

**Comment by crazystorm2017** [comment]
Nope Im Using Clean rAthena testing out stuffs then encountered it running on Renewal

**Comment by sader1992** [comment]
i remember it was a npc that you click on it and it will warp you inside
i maybe wrong

**Comment by crazystorm2017** [comment]
@sader1992 that's what i remember too i just encountered it while testing some stuffs

**Comment by Atemo** [comment]
There is none warp at `moc_para01,47,39` on renewal clean version
screenrathena000

Click npc :  https://github.com/rathena/rathena/blob/master/npc/re/quests/eden/eden_common.txt#L318
Please double check on your repo. Thanks!

**Pull request closed without merging**
