### PR TITLE
Fixed pre-re items using bAtkRate bonus

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: -

* **Server Mode**: Pre-Renewal

* **Description of Pull Request**: 

- Now all pre-re items consistently use bAddClass,Class_All instead of bAtkRate (which doesn't work in pre-re)
- Other minor corrections

### CODE REVIEW

**Comment by gidzdlcrz** [comment]
Good catch. But using bAddClass,Class_All,n; is capped 100% rate. How to make it work if you have more than 100%?

**Review by Lemongrass3110 — APPROVED** [review]

**Comment by Playtester** [comment]
> Good catch. But using bAddClass,Class_All,n; is capped 100% rate. How to make it work if you have more than 100%?

It's not capped to 100%.

**Comment by gidzdlcrz** [comment]
> > Good catch. But using bAddClass,Class_All,n; is capped 100% rate. How to make it work if you have more than 100%?
> 
> It's not capped to 100%.

It's not for me.

To replicate:
1. Script any item temporarily to give 100% of bonus2 bAddClass,Class_All,n; (In my case i used poring card)
2. Test your damage
3. Equip any weapon with turtle general card
4. See result

The total bonus2 bAddClass,Class_All,n; should be 120% with turtle general card. The additional damage doesnt work at least for me.

**Comment by Playtester** [comment]
> > > Good catch. But using bAddClass,Class_All,n; is capped 100% rate. How to make it work if you have more than 100%?
> > 
> > 
> > It's not capped to 100%.
> 
> It's not for me.
> 
> To replicate:
> 
>     1. Script any item temporarily to give 100% of bonus2 bAddClass,Class_All,n; (In my case i used poring card)
> 
>     2. Test your damage
> 
>     3. Equip any weapon with turtle general card
> 
>     4. See result
> 
> 
> The total bonus2 bAddClass,Class_All,n; should be 120% with turtle general card. The additional damage doesnt work at least for me.

Works perfectly fine. Increases damage by 100% without Turtle General Card, increases damage by 120% with Turtle General Card.

**Pull request merged**
