### PR TITLE
Code Consistency 

### PR DESCRIPTION
**Pull request by Stolao**
A small inconsistency that bothered me...

### CODE REVIEW

**Comment by anacondaqq** [comment]
and you think it's more `readable`?

**Comment by cydh** [comment]
Do you bother to read it?

**Comment by anacondaqq** [comment]
I didn't ask the question to you @cydh, and i have not rude to you, so please, you know what to do.

**Comment by cydh** [comment]
He's my teammate.
It's just formatting style, and the change is good in ternary term.

**Comment by anacondaqq** [comment]
@cydh sorry then, i'm not right, i though it's unsafe and non readable (i have tested it a little bit & i have bad experience (but my own and personal) with such code declaration with if statement). 😃

**Comment by Playtester** [comment]
There's a space missing behind the "?"

**Comment by Stolao** [comment]
`int maxcount = (skill_id==AM_CANNIBALIZE)? 6-skill_lv : skill_get_maxcount(skill_id,skill_lv);`

another example of it in use, its always

`(condition)? statment : statement`with no space

**Pull request merged**
