### PR TITLE
Refactored item bonuses to utilize C++ features

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: #996, #3152

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Refactored MAX_PC_BONUS item bonuses from static arrays to vectors.
  * Increased MAX_PC_BONUS to 50.
  * Frees up memory from players that may not ever utilize all their static MAX_PC_BONUS item bonuses.
  * Expanded bonus ResEff to not be restricted to SC_COMMON* statuses.
  * Removed old ERS usages.
  * Removed code redundancy and general cleanups.

### CODE REVIEW

**Comment by Angelic234** [comment]
1. when player equid an autobonus item (ex item 5856)
2. logout
map - server crashed

**Comment by Everade** [comment]
Seems to be working fine.

**Comment by keitenai** [comment]
Expanded bonus ResEff to not be restricted to SC_COMMON* statuses.

YES!! Omg! finally!

**Comment by Everade** [comment]
Any plans on bringing this to master?
That's were the real feedback is coming in when it's getting hot :D

I've been testing this since quite a while and did not encounter any issues so far.
Although i haven't tested your latest cleanups, i think it should be quite safe to use.

**Pull request merged**
