### PR TITLE
Updates the Magic Book NPC

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: N/A

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Updates the Magic Book NPC, Lea, to the new item IDs.
  * Lea no longer requires items for Magic Books.

### CODE REVIEW

**Comment by Surefirer** [comment]
I need to change the type of nameid in ragnarok_logs -> picklog to int and length set to 6, otherwise when I receive a book from npc, it will throw an error. Original setting is smallint(5)

**Comment by aleos89** [comment]
Sounds like you didn't run [a SQL upgrade](https://github.com/rathena/rathena/blob/master/sql-files/upgrades/upgrade_20200808_logs.sql).

**Comment by Surefirer** [comment]
oops, my bad:)

**Comment by mazvi** [comment]
Need add packver checker for old client

**Review by Latiosu — APPROVED** [review]

**Review by Atemo — APPROVED** [review]

**Pull request merged**
