### PR TITLE
Cleans up Severe Rainstorm damage

### LINKED ISSUE #5450: Severe Rainstorm skill damage explosion when equip instruments/whips
* **rAthena Hash**: 8385162fd

* **Client Date**: 20200401

* **Server Mode**: RE

* **Description of Issue**: Use Improve Concentration skill right after use Severe Rainstorm skill, the severe rainstorm damage will explosion if you use element arrow or the same element arrow as the monster.

skillbug

  * Result: 
  * Expected Result: the damage should remain the same if you cast improve concentration after you cast severe rainstorm skill.

skillbugNor

  * How to Reproduce: equip arrow of shadow (item#1767), then `@monster 1719`. use improve concentration after you cast severe rainstorm skill, the damage increases a lot. I tried different element arrow, they all affect. You can see in the video below. If you equip steel arrow(item#1753), then the damage does not affect by improve concentration skill.
  * Official Information:
  

* **Modifications that may affect results**: no mod. I use clean Ra to test.
  
  

Video: https://www.youtube.com/watch?v=SN5vf8yakfY

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #5450

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Adjusts the damage formula to further reflect kRO.
  * More info: https://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=7275&curpage=2
Thanks to @Surefirer!

### CODE REVIEW

**Comment by Surefirer** [comment]
Thanks. @aleos89

**Comment by attackjom** [comment]
this is the part of rebalance that came along with class 4 ?

**Comment by aleos89** [comment]
Yeah looks like it is part of that balancing. I've completely forgotten about that patch.

**Comment by Surefirer** [comment]
Do you have a plan to release this rebalance patch on Rathena in the future?

**Comment by aleos89** [comment]
Yes, I am working on completing the full patch soon.

**Pull request closed without merging**
