### PR TITLE
Hotfix for issue #146

### LINKED ISSUE #146: mob_item_ratio.txt in import folder (still) not working
6 months ago: https://github.com/rathena/rathena/commit/6c5d4a730f82afa9367ec0b29d8509ec95e420c5

mob_item_ratio.txt in the main db folder works, but not the one in the import folder.

### PR DESCRIPTION
**Pull request by Lemongrass3110**
Seperated monster drop ratio adjustment into it's own function.

Fixes #146

### CODE REVIEW

**Comment by cydh** [comment]
tested good (in my eyes witness :P)

**Comment by cydh** [comment]
but still there's something that bother me about result of `@whodrops` when do `@reloadmobdb` then `@reloaditemdb` (or swapped? xD) if there's change on mob ratio.

**Comment by Lemongrass3110** [comment]
I don't really get what you mean @cydh
No problem for me here. Only thing is that this file is only reloaded on `@reloadmobdb`

**Comment by cydh** [comment]
I'm lazy to explain. :D

* load server with no entry for mob_item_ratio
* put value on mob_item _ratio
* `@reloadmobdb`
* `@whodrops`
* `@reloaditemdb`
* `@whodrops`

**Comment by Lemongrass3110** [comment]
screenrathena010
screenrathena011
screenrathena012

I would not have asked you if I would have seen any problem during my tests. o_o
So your explanation please. :P

I put this entry into mobratio:
``909,1000``

**Comment by cydh** [comment]
merged. :P
just let if people found issue and repost (as always /gg)

**Pull request merged**
