### PR TITLE
Moved the NPCs from WolfchevLaboratory.txt (Issue #774)

### PR DESCRIPTION
**Pull request by Atemo**

### CODE REVIEW

**Comment by Atemo** [comment]
Please correct my comment

**Comment by cydh** [comment]
I don't any your comment

**Comment by Atemo** [comment]
I mean the additional comments need to be checked because of my creepy english

**Comment by Akkarinage** [comment]
Doesn't a new file need to be loaded from somewhere? (/npc/re/scripts_athena.conf)

**Comment by Atemo** [comment]
I hate to admit but I forgot about that..

**Comment by cydh** [comment]
oot,
I think rathena.org domain is down. afaik it's expiration date around 28 Nov 2015 (it's expire around, thanksgiving, black Friday, cyber Monday events. xD)

**Pull request merged**
