### PR TITLE
Small Bugfix in Ayothaya Dungeon Entrance Quest

### PR DESCRIPTION
**Pull request by Jeybla**
Showed the wrong mes-output.

(First test pull request >_<)

### CODE REVIEW

**Comment by aleos89** [comment]
Would be nice if you could revert the name of the Fabric, that way this could be merged. :)

**Comment by aleos89** [comment]
Ah, sorry I just noticed you did this against the master of your fork. Next time, check out this link: https://help.github.com/articles/creating-a-pull-request/

It's better to create a branch, that way you con make changes to it later on!

**Comment by aleos89** [comment]
Thanks! Fixed in 4b3d8dd!

**Comment by Jeybla** [comment]
Okay, I'll leave the forked master branch clean. Thanks for the info. :)

**Pull request closed without merging**
