### PR TITLE
correct bad npc name format in buwaya cave instance

### PR DESCRIPTION
**Pull request by CitrusAroma**
IMO. The first char of npc name should not be put in with '#' .

### CODE REVIEW

**Comment by secretdataz** [comment]
NPC names with `#` as prefix are meant to be hidden.
Your PR is meaningless since every NPC you edited its name has 139 (`HIDDEN_WARP_NPC`) as sprite ID.

**Comment by secretdataz** [comment]
This pull request has been rejected.

**Comment by CitrusAroma** [comment]
Every NPC has  its hidden sprite ID why we need '#' ?

**Comment by secretdataz** [comment]
It was converted from the official script and kept there.

**Pull request closed without merging**
