### PR TITLE
Costume Enchant NPC in Malando

### PR DESCRIPTION
**Pull request by GMSarah**
I don't own this script but as i remember there's someone who shared this on rAthena Forum, the script still working fine.
Just need to add or edit some lines to match some new changes on the git.

Hopefully this will help

Big credits to the owner.

* **Addressed Issue(s)**: 

* **Server Mode**:  Renewal

* **Description of Pull Request**: 

 Added missing malangdo custom enchant npcs.

Just a reference > https://irowiki.org/wiki/Malangdo_Costume_Enchants

### CODE REVIEW

**Comment by attackjom** [comment]
https://github.com/rathena/rathena/pull/4839

Atemo also open pull request for this.

**Comment by Questune09** [comment]
> #4839
> 
> Atemo also open pull request for this.

This is different npc who actually enchant the costumes, the other one is just an exchange npc

**Comment by ZelosAvalon** [comment]
I started coding these npc today, if anyone can help and have some iRO content to share I could finish coding, any print screen of interactions with npc or replays already helps.

**Comment by Atemo** [comment]
Handled by https://github.com/rathena/rathena/pull/4839
Thanks!

**Pull request closed without merging**
