### PR TITLE
Add base logic of shiranui job skills

### PR DESCRIPTION
**Pull request by Tyritti**
Description here ->https://github.com/rathena/rathena/issues/8424
I don't think this code should be in main thread, but it could be some base for other developers. All skills works correct, besides of issues below.

* **Addressed Issue(s)**: 
No correct damage calculation
Skill with detected bugs:
Mirage - no skill limit check
Melt Away - Mirage clone not working
Infiltrate - wrong placement

* **Server Mode**:  Both

* **Description of Pull Request**: No

### CODE REVIEW

**Comment by admkakaroto** [comment]
Why not use this?

https://github.com/rathena/rathena/pull/7024

**Comment by Tyritti** [comment]
> Why not use this?
> 
> #7024

Don't see this before, I'll have to check this out.

**Comment by Nicapone1** [comment]
> > Why not use this?
> > #7024
> 
> Don't see this before, I'll have to check this out.

Why did you close this one? the functioning of the skills is not correct. Need reviews

**Comment by Daegaladh** [comment]
> > > Why not use this?
> > > #7024
> > 
> > 
> > Don't see this before, I'll have to check this out.
> 
> Why did you close this one? the functioning of the skills is not correct. Need reviews

Then do a review on the other PR

**Comment by Tyritti** [comment]
> > > Why not use this?
> > > #7024
> > 
> > 
> > Don't see this before, I'll have to check this out.
> 
> Why did you close this one? the functioning of the skills is not correct. Need reviews

As mentioned, job skills has been implemented in [#402](https://github.com/rathena/rathena/pull/7024) thread.

**Comment by Nicapone1** [comment]
> > > > Why not use this?
> > > > #7024
> > > 
> > > 
> > > Don't see this before, I'll have to check this out.
> > 
> > 
> > Why did you close this one? the functioning of the skills is not correct. Need reviews
> 
> Then do a review on the other PR
  
 I make my reviews, but not all make this capability . Just waning

**Pull request closed without merging**
