### PR TITLE
Fix compiler warning C4244.

### PR DESCRIPTION
**Pull request by userid0**
* **Addressed Issue(s)**: 
47c9a362156b27fca484fd70e7990ceb1cc79d32

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
fix variable type for compiler warning C4244.

### CODE REVIEW

**Comment by idk-whoami** [comment]
It works.

**Comment by KingarteR** [comment]
It work should take the master

**Comment by vstumpf** [comment]
If you change these to `int64`s, you need to change the sub functions to parse the arguments as `int64`s as well. 
for example, in `mob_getfriendhprate_sub`:
```
min_rate = va_arg(ap, int64);
```

**Comment by aleos89** [comment]
Agreed with @vstumpf. Some of the types within the functions are still using int, so they need to be adjusted accordingly.

**Comment by userid0** [comment]
update arguments

**Comment by userid0** [comment]
> If you change these to `int64`s, you need to change the sub functions to parse the arguments as `int64`s as well. for example, in `mob_getfriendhprate_sub`:
> 
> ```
> min_rate = va_arg(ap, int64);
> ```

apply

**Review by aleos89 — APPROVED** [review]

**Pull request merged**
