### PR TITLE
Fixed AG_BATTLE and AG_TAMING achievements

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: #4015

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Fixes a potential crash from AG_BATTLE and AG_TAMING achievements.
  * General cleanups.
Thanks to @Atemo!

### CODE REVIEW

**Comment by rickborges93** [comment]
I made these changes manually and this map_server error continue.
The error's happening like i've changed nothing. 
So, unfortunately this error is still happening.

**Comment by aleos89** [comment]
Sorry, I can't reproduce any crashes with this PR. Make sure you didn't miss anything if you're applying manually.

**Comment by earnestinence** [comment]
Looks like its not fixing it. still crashes.

**Comment by korkeng** [comment]
Me too, still crashing

**Comment by Normynator** [comment]
@earnestinence & @korkeng can you get a crashlog from gdb?

**Comment by korkeng** [comment]
@Normynator 
image

**Comment by earnestinence** [comment]
@Normynator Using clean rathena, switch the server to pre-renewal mode: if you kill poring the map server crashes, but other monster like Lunatic doesn't crash the map-server.

**Comment by aleos89** [comment]
We are aware of the issue now and are working on a fix.

**Comment by earnestinence** [comment]
Looks like everything is working now, thanks @aleos

**Comment by korkeng** [comment]
Thanks @aleos89 , @Normynator now it's work fine

**Comment by earnestinence** [comment]
> Thanks @aleos89 , @Normynator now it's work fine

Actually can you try to kill two or more porings?

**Comment by korkeng** [comment]
@earnestinence I can't sir
and i got this crashlog 
image

**Comment by earnestinence** [comment]
@aleos89 Looks like everything is working fine now, no issue so far. Thanks for your hard work!

**Pull request merged**
