### PR TITLE
Removed leftovers from unreleased classes

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: None

* **Server Mode**: Both

* **Description of Pull Request**: 
Removed unreleased classes from the job database and atcommand jobchange

### CODE REVIEW

**Comment by mazvi** [comment]
is there a change in hp and sp? is this more accurate?

**Comment by Atemo** [comment]
> is there a change in hp and sp? is this more accurate?

Read the description of the pull request and tell me what you understand

**Comment by mazvi** [comment]
Sorry i only see this..

gambar

There may be a line difference causing this.

**Comment by aleos89** [comment]
That’s just GitHub trying to align lines in the file from the removal of the others. It’s simply looks like a trick to you in this format.

**Pull request merged**
