### PR TITLE
Suggestion: identifyall script command

### PR DESCRIPTION
**Pull request by Atemo**
* **Addressed Issue(s)**: -

* **Server Mode**: -

* **Description of Pull Request**: 
Suggestion to simplify the item identification throught script command.

**Sample**
_____________
```
izlude,130,140,5	script	identifyall test	60,{
	.@count = identifyall(false);
	mes "You have " + .@count + " unidentified items in your inventory.";
	mes "Would you like to identify them?";
	next;
	if (select( "Yes", "No" ) == 1) {
		.@count = identifyall();
		mes "" + .@count + " items have been identified.";
	}
	close;
}
```

### CODE REVIEW

**Comment by secretdataz** [comment]
I'd merge `@identifyall`'s code with this script command's code.

**Comment by Atemo** [comment]
In others words, you mean

1. to use the code of this script command to update `@identifyall`

or

2. you prefer the script command without `<type>` parameter

?

**Comment by secretdataz** [comment]
Currently we have a piece of code that does the same thing as the new BUILDIN_FUNC(identifyall) code you want to add, which is @identifyall's code. Now you added another and we have two duplicate code to maintain.
Merge the functionality into one function and have both ACMD_FUNC and BUILDIN\_FUNC call the merged function instead.

**Comment by Atemo** [comment]
hmm like that? Is that fine to put the function in `script.c` ?

**Comment by secretdataz** [comment]
Maybe pc.cpp?

**Pull request merged**
