### PR TITLE
* Official EXP-Giving Script

### LINKED ISSUE #980: Official EXP-Giving Script
Our `getexp` is not quite correct.
Afaik, there are some ways on official while giving EXP to the player.

* `getexp` to give **Quest** Base EXP to player, only Base EXP. So does with `dropexp`.
  * Affected by item bonus, and 'server' EXP rate.
  * Displayed in purple color.
  * Emulated by `getexp` command.
* `getJexp` to give **Quest** Job EXP to player, only Job EXP. So does whit `dropJexp`.
  * Affected by item bonus, and 'server' EXP rate.
  * Displayed in yellow color.
  * Emulated by `getexp` command.
* `AddParameterValue VAR_EXP n` to **add** Base EXP to player
  * **Not** affected by item bonus, and 'server' EXP rate.
  * **Ignore** guild tax.
  * Displayed in yellow color.
  * Emulated by `set BaseExp`.
* `AddParameterValue VAR_JOBEXP n` to **add** Job EXP to player
  * **Not** affected by item bonus, and 'server' EXP rate.
  * **Ignore** guild tax.
  * Displayed in yellow color.
  * Emulated by `set JobExp`.

### So, here's the todo
* [ ] `getexp`
I'll make server won't send 0 EXP to the client, so if the script is `getexp 50,0;`, on player's end it only displayed as

> 50 EXP gained
> 0 Job EXP gained <--- This is won't be displayed.

except, the 0 because of max level, like `getexp 100,100;` on Max job level
> 100 EXP gained
> 0 Job EXP gained <--- 0 because max job is max still displayed

* [ ] `set BaseExp`, I'll add `clif_displayexp(sd, ismaxbaselevel ? 0 : value, SP_BASEEXP, false, [gain|loss]);` in `pc_setparam()`.
* [ ] `set JobExp`, I'll add `clif_displayexp(sd, ismaxjoblevel ? 0 : value, SP_JOBEXP, false, [gain|loss]);` in `pc_setparam()`.
* [ ] Change the item bonus from `getexp` to `set` for:
  * 12259,Miracle_Medicine
  * 12261,Secret_Medicine

### PR DESCRIPTION
**Pull request by cydh**
* Fixed #980.
  * Job Quest EXP always be shown in yellow color.
  * Miracle Tonic (12259) and Leap of Fantasy (12261) give fixed EXP through `pc_setparam` that ignore EXP item bonuses and exp rates. Not as Quest EXP from `getexp` script.
  * If given EXP is 0 by `getexp`, it won't be notified in client EXP log.
  * If given EXP for base/job that reach max level, client will be notified as 0 EXP gained.
* Follow up 20588abcd83fab53f9e52deafc08bfcddfe1658a
  * Some clean up on `pc_gainexp`.

Signed-off-by: Cydh Ramdh <cydh@pservero.com>

### CODE REVIEW

**Comment by cydh** [comment]
then, brace for another issue report

**Comment by julia40124009** [comment]
..I found it ( I deliberately set exp to large )
  `12259,Miracle_Medicine,Miracle Tonic,2,0,,0,,,,,0xFFFFFFFF,63,2,,,,,,{ BaseExp += 3000000000;    JobExp += 1500000; },{},{}`

and overflow
`[Warning]: script:op_2num: overflow detected op=C_ADD i1=99999999 i2=2147483647
[Debug]: Source (NPC): FAKE_NPC (invisible/not on a map)`

I know because int variable limit 2147483647

**Comment by cydh** [comment]
better prevention, just how people script it.
all integers in scripting are limited to `INT32_MAX`, like `Zeny` etc.

but well, I planned to make `getexp` with flag so it works like current `BaseExp += n` and `JobExp += n`, then put 'error' message if idk-who-rathena-user-will-use-bad-scripting use `set BaseExp` or `set JobExp`.

**Comment by cydh** [comment]
well, maybe will make `pc_setparam` for `SP_BASEEXP` and `SP_JOBEXP` as original, then I'll create `getexp2` for this behavior. If using `pc_setparam`, max input limit is `INT_MAX`.
In case, if player makes script by using `set BaseExp,BaseExp+n` , if `BaseExp` itself is greater than `INT_MAX` at first place, it will overflow! Even the `n` is 0.

What a bad practice!

**Comment by cydh** [comment]
going to merge this manually /hmm

**Pull request merged**
