### PR TITLE
Migrated clif.c to C++

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: None

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Needed in preparation for future projects.

### CODE REVIEW

**Comment by Daegaladh** [comment]
Compiled fine, but got this error on login on both x64 and x32 (Win10, VS17, 2015-05-13aRagexe):
`[Error]: WFIFOSET: Maximum write buffer size for client connection 4 exceeded, most likely caused by packet 0x099d (len=298, ip=127.0.0.1).`

**Comment by Mikegyver** [comment]
another c++ PR.. maybe will give a try later. xD

**Comment by Mikegyver** [comment]
tested & works fine on both ubuntu server 16.04.3 LTS & lubuntu server arm linux v7.1 (using 2017-08-01aRagexeRE client)

**Comment by Daegaladh** [comment]
@aleos89 please change clif.c to clif.cpp in this few instances:

clif.cpp:
`delay_clearunit_ers = ers_new(sizeof(struct block_list),"clif.c::delay_clearunit_ers",ERS_OPT_CLEAR);`

scr/map/CMakeLists.txt:
`"${MAP_SOURCE_DIR}/clif.c"`

scr/map/server/CMakeLists.txt:
"${SERVER_MAP_SOURCE_DIR}/clif.c"

unit.c:
`// Normally not needed because clif.c checks for it, but the at/char/script commands don't! [Skotlex]`
and
`if(ud->skilltimer != INVALID_TIMER) // Normally not needed since clif.c checks for it, but at/char/script commands don't! [Skotlex]`

**Comment by aleos89** [comment]
@Daegaladh: Thanks! I updated the references you listed except for cmake since it hasn't been updated to support C++ yet (or maybe never).

**Pull request merged**
