### PR TITLE
Corrected script for some item #19

### PR DESCRIPTION
**Pull request by idk-whoami**
* **Addressed Issue(s)**: 

* **Server Mode**: re

* **Description of Pull Request**: Implementations + corrections of a bunch of items

### CODE REVIEW

**Comment by mazvi** [comment]
Please check this https://github.com/rathena/rathena/issues/7741

**Comment by mazvi** [comment]
okay but on rathena to get the box is barter not use zeny
image

**Comment by idk-whoami** [comment]
Sorry, I did a quick search, found an NPC available for sale, but the Barter Shop Feature came in and closed the NPC.

Capture

**Comment by mazvi** [comment]
I also get this from @Balferian on kRO the trap sell price is 0 to avoid abuse. I think probably all the arrows in the quiver are also 0 on the sell price 

image-5

**Comment by idk-whoami** [comment]
Capture

**Comment by idk-whoami** [comment]
Capture

**Comment by Atemo** [comment]
Good for me, thanks!

**Comment by mazvi** [comment]
LGTM

**Pull request merged**
