### PR TITLE
Added Paradise Market Mapflag

### PR DESCRIPTION
**Pull request by mazvi**
Added ParaMarket NoBranch

* **Addressed Issue(s)**: 

* **Server Mode**: 

* **Description of Pull Request**:

### CODE REVIEW

**Comment by Atemo** [comment]
`prt_in` has the same group of mapflags, do you mind to add the following mapflags too (in their respective file) ?
```
paramk	mapflag	nomemo
paramk	mapflag	nopenalty
paramk	mapflag	pvp	off
paramk	mapflag	noteleport
```

**Comment by mazvi** [comment]
Yes no problem.. so i need edit my commit?

**Comment by Atemo** [comment]
No it requires `nobranch` as well, keep your change.
You just have to push a new commit with the others mapflags for `paramk` (each mapflag in their respective file).

**Comment by mazvi** [comment]
@Atemo thank you for your advice, I have made 5 mapflag according to your advice :)

**Pull request merged**
