### PR TITLE
Fix equip order

### PR DESCRIPTION
**Pull request by eppc0330**
* **Addressed Issue(s)**: 

* **Server Mode**: Both

* **Description of Pull Request**:
*  Weapon and accessory should always be equipped for Right side of character, left side of equip window,  first.

### CODE REVIEW

**Comment by Playtester** [comment]
From my tests on official servers, they are equipped on the left side first.

**Comment by eppc0330** [comment]
> From my tests on official servers, they are equipped on the left side first.

How about accessories? I tested on KRo today and they are equipped on the right first.

**Comment by eppc0330** [comment]
> From my tests on official servers, they are equipped on the left side first.
Equiporderweapon
Equiporderacc
These are all from KRo, and both are equipped right side first.

**Comment by aleos89** [comment]
Confirmed the behavior as well, the items are applied to the player's right-hand, which is on the left side of the equip window.

**Review by aleos89 — APPROVED** [review]

**Comment by Playtester** [comment]
Yes, sorry I misunderstood. Correct, it's the left side of the equipment window, so it's the right side of the character.

**Comment by eppc0330** [comment]
> Yes, sorry I misunderstood. Correct, it's the left side of the equipment window, so it's the right side of the character.

Sorry my description was kind of confusing. I edited it.

**Comment by Playtester** [comment]
@eppc0330 
Hi, I tested this on pre-renewal now and I think there's a difference. On pre-renewal, if you have both hands equipped and you equip an item, it will always go to your shield hand (right side).
However, if both your right hand is free, then it will go to your right hand (left side).

For accessoires it works perfectly fine! There it indeed always prioritizes the left side.

We might need a switch for renewal here.

**Comment by eppc0330** [comment]
> @eppc0330 Hi, I tested this on pre-renewal now and I think there's a difference. On pre-renewal, if you have both hands equipped and you equip an item, it will always go to your shield hand (right side). However, if both your right hand is free, then it will go to your right hand (left side).
> 
> For accessoires it works perfectly fine! There it indeed always prioritizes the left side.
> 
> We might need a switch for renewal here.

Thanks for info. I will add RENEWAL switching.

**Review by Playtester — APPROVED** [review]
Tested in pre-re and approved.

**Pull request merged**
