### PR TITLE
Fix SP and CD of some Star Emperor/Soul Reaper skills

### PR DESCRIPTION
**Pull request by LordWhiplash**
* **Addressed Issue(s)**:  SP cost for this levels was missing

* **Server Mode**: RE

* **Description of Pull Request**: adds the sp cost based on: http://kafra.kr/#!/en/KRO/skillinfo/2602

### CODE REVIEW

**Comment by aleos89** [comment]
Eswhoo is also missing the Splash and SP for levels 8-10. Curse Explosion and Solar Burst are also missing SP for levels 6-10. Full Moon Kick is missing SP for levels 8-10. Falling Star is missing Cooldown and SP for levels 8-10.

Sorry for throwing these on to this too. I just went ahead and checked the other Star Emperor/Soul Reaper skills and seems I forgot to update the values after increasing the levels.

**Comment by LordWhiplash** [comment]
I'll add so, as soon as i can, no problema!

**Comment by LordWhiplash** [comment]
@aleos89 do you have info about the Falling Star cooldown? could not find

**Comment by aleos89** [comment]
Falling Star has a couple issues. It would seem Cooldown is actually not present and it's meant to be Duration1. The cast values for Falling Star should look like:
```yaml
    CastTime: 1000
    Duration1:
      - Level: 1
        Time: 120000
      - Level: 2
        Time: 140000
      - Level: 3
        Time: 160000
      - Level: 4
        Time: 180000
      - Level: 5
        Time: 200000
      - Level: 6
        Time: 220000
      - Level: 7
        Time: 240000
      - Level: 8
        Time: 260000
      - Level: 9
        Time: 280000
      - Level: 10
        Time: 300000
    FixedCastTime: 2000
```

**Comment by LordWhiplash** [comment]
Should SJ_FALLINGSTAR_ATK and SJ_FALLINGSTAR_ATK2 be updated to MaxLevel: 10 too, right?

**Comment by aleos89** [comment]
Good catch. Yes, they should match the "parent" skill level.

**Pull request merged**
