### PR TITLE
Added November and current December clients

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: None

* **Server Mode**: Both

* **Description of Pull Request**: 
This pull requests adds support for all clients up until 2017-12-06
Credits to @4144

### CODE REVIEW

**Comment by admkakaroto** [comment]
any information about the problem of the party system bug?

**Comment by secretdataz** [comment]
What about the PACKETVER_RE define for 2017-12-06 since it is first ever Ragexe available since mid 2016?

**Comment by Lemongrass3110** [comment]
I did not see that when I copied it over, but we currently do not support the mid 2016 Ragexe clients as well.
If we plan on adding support for Ragnarok Zero clients and kRO main clients or even support for other servers we should come up with a design for storing the packet versions/user configurations.

**Comment by xEasycore** [comment]
It would be great if rA adds support to Ragnarok Zero

**Comment by idamonli** [comment]
The ZERO related update that I tried to transplant HERC/4144 failed
https://github.com/4144/Hercules/commits?author=4144

**Comment by Lemongrass3110** [comment]
This pull request was merged already. ZERO clients are not on our agenda for now.

**Pull request merged**
