### PR TITLE
[FEATURE] restore amotion from sonicblow/vulcan arrow/cross impact removed from ragexe 20181128+ 

### PR DESCRIPTION
**Pull request by AoShinRO**
* **Addressed Issue(s)**:  https://github.com/Neo-Mind/WARP/issues/63

* **Server Mode**:  Both

* **Description of Pull Request**:  Add a feature config to force src send packets to restore hardcoded animation from sonicblow and vulcan arrow removed from ragexe 20181128+ using pre-renewal mode
https://ragnarok.fandom.com/wiki/RO_Patch_(2018_Nov._28)
maybe it's a work from 4144 😄 client sided hex edit but still without solution from years 

-> Added Cross Impact Amotion removed at 2019/10/16
https://ragnarok.fandom.com/wiki/RO_Patch_(2019_Oct._16)
-> Changed to be used on renewal too

### CODE REVIEW

**Review by apichead — COMMENTED** [review]
have for renewal? plz

**Comment by AoShinRO** [comment]
> have for renewal? plz

if you want to run it on renewal, just change from unit.cpp changes
```#ifndef RENEWAL```
to:
```#ifdef RENEWAL```
or just remove #ifndef RENEWAL and the respective #endif from code to make it works on all versions

**Comment by apichead** [comment]
> > อยากต่ออายุไหม? ได้โปรด
> 
> ส่วนรันเมื่อต่ออายุเพียงเปลี่ยนจาก unit.cpp `#ifndef RENEWAL` : `#ifdef RENEWAL` หรือเพียงแค่ลบ #ifndef RENEWAL และ #endif ตามลำดับจากโค้ดเพื่อให้ทำงานได้กับทุก ๆ อย่างการเปลี่ยนแปลง


It seems like it's only displaying attack images. It's still just one time.
Still not like per-re

**Comment by NexoMMORPG** [comment]
It was quite accomplished, I think there are other skills missing that the animation lost, but I don't remember which ones are missing, good job 😎👍

**Comment by NexoMMORPG** [comment]
It was quite accomplished, I think there are other skills missing that the animation lost, but I don't remember which ones are missing, good job 😎👍

**Comment by AoShinRO** [comment]
> It was quite accomplished, I think there are other skills missing that the animation lost, but I don't remember which ones are missing, good job 😎👍

From the post on warp, it's Crossimpact, but I couldn't find the patchnotes with the date of the change

**Comment by apichead** [comment]
> > > > อยากต่ออายุไหม? ได้โปรด
> > > 
> > > 
> > > ส่วนรันเมื่อต่ออายุเพียงเปลี่ยนจาก unit.cpp `#ifndef RENEWAL` : `#ifdef RENEWAL` หรือเพียงแค่ลบ #ifndef RENEWAL และ #endif ตามลำดับจากโค้ดเพื่อให้ทำงานได้กับทุก ๆ อย่างการเปลี่ยนแปลง
> > 
> > 
> > It seems like it's only displaying attack images. It's still just one time. Still not like per-re
> 
>  Project.Rio_2023.12.03-09.25.mp4 
> it just restores the animation, you probably changed the skill in the database, I pull the hitscount information from there animation tick scales with aspd

try  ::
	-sd->animation_force.iter = 0;
	-sd->animation_force.hitcount = skill->num[pc_checkskill(sd, skill_id)] < 0 ? std::abs(skill->num[pc_checkskill(sd, skill_id)]) : skill->num[pc_checkskill(sd, skill_id)];
	-sd->animation_force.tid = add_timer(gettick(), pc_animation_force_sub, sd->bl.id, sd->battle_status.amotion + sd->battle_status.dmotion);

Change to >>
	+sd->animation_force.iter = 0;
	+sd->animation_force.hitcount = 8
	+sd->animation_force.tid = add_timer(gettick(), pc_animation_force_sub, sd->bl.id,  sd->battle_status.dmotion);
	
	i think beter

**Comment by AoShinRO** [comment]
> > > > > อยากต่ออายุไหม? ได้โปรด
> > > > 
> > > > 
> > > > ส่วนรันเมื่อต่ออายุเพียงเปลี่ยนจาก unit.cpp `#ifndef RENEWAL` : `#ifdef RENEWAL` หรือเพียงแค่ลบ #ifndef RENEWAL และ #endif ตามลำดับจากโค้ดเพื่อให้ทำงานได้กับทุก ๆ อย่างการเปลี่ยนแปลง
> > > 
> > > 
> > > It seems like it's only displaying attack images. It's still just one time. Still not like per-re
> > 
> > 
> > Project.Rio_2023.12.03-09.25.mp4
> > it just restores the animation, you probably changed the skill in the database, I pull the hitscount information from there animation tick scales with aspd
> 
> try :: -sd->animation_force.iter = 0; -sd->animation_force.hitcount = skill->num[pc_checkskill(sd, skill_id)] < 0 ? std::abs(skill->num[pc_checkskill(sd, skill_id)]) : skill->num[pc_checkskill(sd, skill_id)]; -sd->animation_force.tid = add_timer(gettick(), pc_animation_force_sub, sd->bl.id, sd->battle_status.amotion + sd->battle_status.dmotion);
> 
> Change to >> +sd->animation_force.iter = 0; +sd->animation_force.hitcount = 8 +sd->animation_force.tid = add_timer(gettick(), pc_animation_force_sub, sd->bl.id, sd->battle_status.dmotion);
> 
> ```
> i think beter 
> ```

nope, you just changed it to a fixed number of hits, it's not better because this function can be used to restore animation from cross impact on future, better is you maintain the number of hits from skill as original value :D

**Comment by AoShinRO** [comment]
```
Cross Impact added system on PACKETVER >20191016
Renewal support added
Cleaned PC.cpp unnecessary timer_list call
```

**Pull request closed without merging**
