### PR TITLE
Added support for RSW 2.2

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: None

* **Server Mode**: Renewal

* **Description of Pull Request**: 
Added support for RSW 2.2
Merged mapserver and mapcache RSW reading code
Credits to @4144 in HerculesWS/Hercules@0b3f5c3

### CODE REVIEW

**Comment by mazvi** [comment]
So we alse need uodate client to 2019? Because only client 2019 support RSW 2.2

**Comment by secretdataz** [comment]
No, the server being able to read RSW 2.2 doesn't mean you have to use it.

**Comment by mazvi** [comment]
Okay so that mean the client also must support RSW2.2 like client 2019?

**Comment by secretdataz** [comment]
You can continue to use 2018 clients normally.

**Pull request merged**
