### PR TITLE
Updated Old Glast Heim instance

### PR DESCRIPTION
**Pull request by secretdataz**
* **related issues**: #493, #1363, #1591, #1941, #2002
- merged from idAthena
- cleaned up dialogues
- cleaned up script logic

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
Is #493 related to this?

**Comment by srhmike** [comment]
```
// Old Glast Heim (currently placeholders)
2464,MG_ZOMBIE,Zombie,Zombie,17,9340,1,117,87,1,38,50,20,3,15,8,17,0,15,0,10,12,1,1,29,0x3885,400,2612,912,288,0,0,0,0,0,0,0,6609,1000,6610,1000,6608,10,938,1000,727,500,0,0,0,0,0,0,0,0,0,0 //Corrupted Steward
2465,MG_WRAITH,Wraith,Wraith,77,23168,1,1190,1191,1,335,396,80,40,62,26,30,55,76,5,10,12,2,1,89,0x3695,300,1816,576,240,0,0,0,0,0,0,0,6609,1000,6610,1000,6608,10,2206,100,731,100,747,500,0,0,0,0,0,0,0,0 //Corrupted Monk
2466,MG_GHOUL,Ghoul,Ghoul,61,12614,1,583,656,1,216,245,78,5,56,12,19,11,27,10,10,12,1,1,49,0x3885,250,2456,912,504,0,0,0,0,0,0,0,6609,1000,6610,1000,6608,10,756,100,2609,100,7751,1000,0,0,0,0,0,0,0,0 // Grand Chamberlain in pain
2467,MG_ARCLOUSE,Arclouse,Arclouze,107,14020,1,1844,2607,1,269,309,101,36,60,73,45,35,140,15,10,12,1,4,42,0x2003095,100,960,500,480,0,0,0,0,0,0,0,6609,1000,6610,1000,6608,10,1096,3000,997,100,0,0,0,0,0,0,0,0,0,0 //Maggot
2468,MG_RAYDRIC,Raydric,Raydric,115,25408,1,20770,2076,1,572,668,89,15,129,87,55,32,76,27,10,12,2,7,47,0x3095,150,824,780,420,0,0,0,0,0,0,0,6609,1000,6610,1000,6608,10,7054,3000,985,50,2316,200,0,0,0,0,0,0,0,0 //Corrupted Palace Guard
2469,MG_RAYDRIC_ARCHER,Raydric Archer,Raydric Archer,82,30370,1,1049,1332,9,377,395,63,40,53,24,40,15,112,30,10,12,1,6,47,0x2002085,200,1152,1152,480,0,0,0,0,0,0,0,6609,1000,6610,1000,6608,10,7054,3000,985,50,2330,200,0,0,0,0,0,0,0,0 //Wandering Archer
2470,MG_KNIGHT_OF_ABYSS,Knight of Abyss,Abysmal Knight,122,332970,1,4779,4013,1,810,1002,102,50,121,55,68,70,97,37,10,12,2,7,87,0x3695,300,1500,500,1000,0,0,0,0,0,0,0,6609,3000,6610,2000,6608,50,1004,10,2341,200,0,0,0,0,0,0,0,0,0,0 // Corrupted Abysmal Knight
2471,MG_KHALITZBURG,Khalitzburg,Khalitzburg,118,109860,1,2862,2147,1,737,833,125,10,121,48,40,31,89,32,10,12,2,1,29,0x3695,350,528,1000,396,0,0,0,0,0,0,0,6609,3000,6610,2000,6608,50,985,50,1004,10,1110,300,0,0,0,0,0,0,0,0 //Suffering Khalitzburg
2472,MG_BLOODY_KNIGHT,Bloody Knight,Bloody Knight,116,285000,1,7348,6511,3,942,1065,122,50,132,59,70,57,98,45,10,12,2,0,87,0x3695,250,828,528,192,0,0,0,0,0,0,0,6609,3000,6610,2000,6608,50,7054,5000,1160,100,1157,100,0,0,0,0,0,0,0,0 //Bloody Knight
2473,MG_M_UNDEAD_KNIGHT,Undead Knight,Undead Knight,133,500000,0,4500,3375,2,751,880,122,62,122,87,54,65,103,65,14,16,2,7,80,0x6203695,170,140,384,288,0,0,0,0,0,0,0,0,0,0,0,0,0,6609,5000,6610,5000,6608,50,1191,10,1163,100,1463,200,4605,1 //1st Commander of Destruction
2474,MG_F_UNDEAD_KNIGHT,Undead Knight,Undead Knight,133,500000,0,4500,3375,2,751,880,122,62,122,87,54,65,103,65,14,16,2,7,80,0x6203695,170,140,384,288,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6609,5000,6610,5000,6608,50,1163,100,1145,50,4606,1 //2nd Commander of Destruction
2475,MG_CORRUPTION_ROOT,Root of Corruption,Root of Corruption,136,3190000,1,240120,187920,3,710,1762,213,123,86,89,120,131,101,92,14,12,2,7,62,0x6280084,170,854,2016,480,120060,607,5500,608,3500,732,5500,0,0,0,0,0,0,616,5000,617,10000,6607,5000,607,10000,2854,1000,7566,10000,4603,1 //Corrupted Soul
2476,MG_AMDARAIS,Amdarias,Amdarias,143,3283990,1,74288,77950,2,8860,10022,32,66,140,159,30,109,300,90,10,12,2,2,63,0x6283695,200,1152,1152,576,37144,617,5500,617,5000,616,2000,0,0,0,0,0,0,616,5000,617,10000,6607,5000,607,10000,1186,1000,1004,10000,4601,1
```

If this helps any I added in the mob drops.  Source is divine pride.

**Comment by Akkarinage** [comment]
Is there anything in particular that needs to be completed before this PR is merged?

**Comment by Jeybla** [comment]
> Is there anything in particular that needs to be completed before this PR is merged?

Currently testing this PR. What about `Hugin's Buttler` for buying and upgrading `Temporal Boots`?

**Comment by mazvi** [comment]
I agree with @jeybla

**Comment by Jeybla** [comment]
@Atemo I think you can go ahead and merge this pull request if you don't have any more open points.
@mazvi @Atemo already added `Hugin's Butler`

**Comment by Atemo** [comment]
Actually I would like to add the modified temporal menu (boots for gun).
Also the script hasn't been properly tested.

**Comment by ecdarreola** [comment]
@atemo I am currently testing this pr but have problems on enchant though. The special enchant still at slot 4 causing nornal enchants to be removed.

I copied iDathenas npc and its working fine, just added modified temporal boots manually.

As for the gun, no idea.

**Comment by Atemo** [comment]
Thanks to Divine Pride for the Modified Boots informations !

**Comment by zackdreaver** [comment]
@Atemo 
Are these boots have combo script with Gigant Snake Skin[0] and Gigant Snake Skin[1]?

**Comment by ecdarreola** [comment]
@zackdreaver : Should have the combo script but not included yet.

@Atemo : Scripts work great after update. Thanks for the great PR!

**Comment by Atemo** [comment]
>Are these boots have combo script with Gigant Snake Skin[0] and Gigant Snake Skin[1]?

@zackdreaver Yes according to the descriptions (sample https://www.divine-pride.net/database/item/22107/kRO). Thanks for pointing out!

**Comment by ecdarreola** [comment]
Hi sir, found something on 2nd floor of OGH, all mobs spawn at the cell once you pass them through.

**Comment by Atemo** [comment]
Provide ss please.
Officially on commander place, player can hide -> walk on mobs spot -> unhide -> mobs spawn.

**Comment by ecdarreola** [comment]
@Atemo : Sorry late revert. Will add screenshot later. I just found something not sure if its related.

If multiple client running and doing some OGH instance using PR. The other char doesn't receive temporal crystal. Is this normal behavior? They're at the same party though.

Also, sometimes the mobs at 2nd floor doesn't respawn. (Will provide screenshot also later)

**Comment by RyeDE** [comment]
mob spawn is really weird on 2nd floor. in boss room im not sure if all dead bodies are supposed to respawn but  you are able to farm coagulated spells until the instance gets destroyed this way.

**Comment by LMVa** [comment]
Should item_db_re.sql be updated as well? Besides maybe that and the mobs spawning on a single tile(on 2nd map at least), I haven't seen any issues with this branch so far.

**Comment by Lemongrass3110** [comment]
@LMVa item_db_re.sql will be automatically updated when this is merged to master.

**Comment by LMVa** [comment]
Sounds good. What's stopping this from going through? It's not perfect but it's fully functional.

**Comment by Atemo** [comment]
@ecdarreola 
>If multiple client running and doing some OGH instance using PR. The other char doesn't receive temporal crystal. Is this normal behavior? They're at the same party though.

The monsters (boss) killed must be in the character visible area to mark the hunting quest as completed and to receive the reward.
>Also, sometimes the mobs at 2nd floor doesn't respawn. (Will provide screenshot also later)

A part of `OnTouch` issues. WIP in https://github.com/rathena/rathena/pull/2382


@RyeDE
>mob spawn is really weird on 2nd floor. in boss room im not sure if all dead bodies are supposed to respawn but you are able to farm coagulated spells until the instance gets destroyed this way.

It's official behaviour.

>fatal enchant as 3rd and 4th option missing in LUK too

Officially they don't use fatal charm for temporal enchant.

@LMVa
>What's stopping this from going through? It's not perfect but it's fully functional.

We didn't implement some buffs yet https://github.com/rathena/rathena/pull/1554/files#diff-877efde6bb80b5e4ec8c8d71ce8b2181R1553

**Pull request merged**
