### PR TITLE
Fixed 3D_Glasses item script.

### PR DESCRIPTION
**Pull request by CairoLee**
3D_Glasses's item script `Class=Job_Star_Gladiator2` is wrong, Changed to `Class==Job_Star_Gladiator2`

### CODE REVIEW

**Comment by cydh** [comment]
D: `Class=Job_Star_Gladiator2`, it's terrible. Good catch.
but, can u push a commit again to revert the changes in .sql file, we will let's the rathena bot for converting.

**Comment by CairoLee** [comment]
Sure, give me a minute.

**Comment by CairoLee** [comment]
I will close this for keep commit log clear. i will resubmit a new PR for this.

**Comment by CairoLee** [comment]
New pull request without .sql file change at #1694

**Pull request closed without merging**
