### PR TITLE
Fixed unknown map in character select

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: #1145

* **Server Mode**: Both

* **Description of Pull Request**: 
Fixed unknown map being displayed because the client did not trigger it's final code if the character cound was a multiple of 3.

Credits to @4144 for finding this!
Thanks to @RadianFord for reporting.

### CODE REVIEW

**Comment by RadianFord** [comment]
@Lemongrass3110 thank you so much, i tested it and works perfectly no more unknown map.

**Comment by BrOgBr** [comment]
Finally!! Thank you @Lemongrass3110 <3

**Comment by teededung** [comment]
No characters to select. My account has 9 characters.
Tested on 2017-06-14b and 2018-06-21.

**Comment by Lemongrass3110** [comment]
@teededung works just fine for me. Are you sure you have not applied anything wrong here?

**Pull request merged**
