### PR TITLE
CR_GRANDCROSS

### PR DESCRIPTION
**Pull request by violetharmony**
* **Addressed Issue(s)**: 

* **Server Mode**: Renewal

* **Description of Pull Request**:

### CODE REVIEW

**Comment by aleos89** [comment]
What is your source for these changes? Keep in mind the couple PR's you opened are in the list of 1st/2nd class skills that got revamped.

**Comment by violetharmony** [comment]
> 
> 
> What is your source for these changes? Keep in mind the couple PR's you opened are in the list of 1st/2nd class skills that got revamped.

http://violet-harmony.blogspot.com/2017/12/grand-cross-renewal.html

**Comment by admkakaroto** [comment]
This is based on iRO, rAthena is based on kRO server.

**Comment by violetharmony** [comment]
> 
> 
> This is based on iRO, rAthena is based on kRO server.

This is base on all aegis server.

**Pull request closed without merging**
