### PR TITLE
Fix wrong `next` function call

### PR DESCRIPTION
**Pull request by keitenai**
* **Addressed Issue(s)**: 

* **Server Mode**: renewal

* **Description of Pull Request**: 
Fix script error "npc_scriptcont: Guard Leader#buwaya (sd->npc_id=110011242) is not 'Unknown NPC' (id=0)

### CODE REVIEW

**Comment by sader1992** [comment]
if this causes that warning , wouldn't be also better to ignore the next command when there is no mes active ?

**Comment by aleos89** [comment]
I don't think we want to suppress this type of warning as it would promote bad scripting behavior.

**Comment by sader1992** [comment]
i agree , but this warning happens a lot , so by not making a custom message for it or just remove it at this case , it will get mixed with other and more important errors with the same message in my opinion

**Comment by secretdataz** [comment]
More annoying messages = More server owners asking their scripter to fix the problematic script.

**Comment by sader1992** [comment]
yes but people will get an error anyway
i would much rather someone asking me to fix this error
```
buildin_next: Guard Leader#buwaya 'mes' is not active.
```
or
```
buildin_clear: Guard Leader#buwaya 'mes' is not active.
```
instead of this 
```
npc_scriptcont: Guard Leader#buwaya (sd->npc_id=110011242) is not 'Unknown NPC' (id=0)
```

**Comment by secretdataz** [comment]
I agree with your point. A pull request is welcome and I'd be happy to review it.

**Pull request merged**
