### PR TITLE
Updated rockridge npcs to official

### PR DESCRIPTION
**Pull request by Atemo**
* **Addressed Issue(s)**: N/A

* **Server Mode**: renewal

* **Description of Pull Request**: 

Replaced the walkthrough rockridge npcs to official npcs.

### CODE REVIEW

**Review by Kahmora — COMMENTED** [review]
I think I found a small error. I found out while I was translating my language. I'm still translating, if I find anything else I'll let you know.
Line.1075: **Alert** = **Albert**
```mes "Alert wants us to pay him for the ores.";```

**Comment by Kahmora** [comment]
Line: 1617 **Bandit Scarves** = **Bandit's Scarf**
```mes "Please ^4d4dffeliminate Buffalo Bandits and take 5 Brown Mufflers and 5 Bandit Scarves with you^000000 on your way there.";```

**Comment by Pokye** [comment]
getitem 25246,1;// Juice_Mix_Package
Juice_Package - https://www.divine-pride.net/database/item/25246

I think you have to change the item_db_etc.yml too

**Comment by mazvi** [comment]
After this update and SQL upgrade [upgrade_20221103.sql](https://github.com/rathena/rathena/commit/201285781580c9136cb54648218c9db4d4a44ffd#diff-ffc512c7d2a716be83fef2e2afa85c9275ed95038ed14d99c08a800e96616505) the user is stuck and can't get item 25246 on mound sand, is another sql reset needed? considering there are many quest id on this rockridge.

**Comment by mazvi** [comment]
Steel Vigilante also stuck on if (isbegin_quest(12389) == 2) {

**Pull request merged**
