### PR TITLE
Adds back removed skills from kRO

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: #4802

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Adds back AB_EUCHARISTICA, GN_SLINGITEM, and GN_MAKEBOMB.
  * Adds back CR_CULTIVATION for renewal.
  * Skills are still commented out in their respective databases but gives easy ability to re-enable.
  * Fixes an issue with pre-renewal produce database spitting errors when using any production-type skills.
Thanks to @trinitynetworks!

### CODE REVIEW

**Comment by mazvi** [comment]
How about sql upgrade you remove it?

**Comment by aleos89** [comment]
No, because it's still disabled on kRO. I simply added the skills (source side) back so that people could just uncomment the database values if they want to re-enable the skills. The SQL reset can just be avoided if you want to keep these skills on your server.

**Comment by trinitynetworks** [comment]
errors still

**Comment by aleos89** [comment]
According to the build bots below I don't see any errors.

**Comment by darking12345** [comment]
added the changes, however it outputs alot of error when starting up the server. no issues encountered on compiling part.

**Comment by aleos89** [comment]
Sorry, but I tested on pre-renewal and renewal and got no errors from start up or skill usage. What steps are you doing to create the errors to pop up?

**Comment by mazvi** [comment]
@darking12345 can you inform what your operating system and compiler? If use GCC what version of GCC?

**Comment by darking12345** [comment]
I apologies for the delay. I re'diffed it again. No more issue encountered. Thank you!

**Pull request merged**
