### PR TITLE
Corrected Heat Barrel bonuses

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: #2875

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Attack was not factoring in coins.
  * Corrected fixed cast time to also factor in coins.
Thanks to @rye305!

### CODE REVIEW

**Comment by rye305** [comment]
working fine my man!

**Comment by LordWhiplash** [comment]
I was looking at Rebellion skills and noticed that in Heat Barrel, the description says that the ASPD is modified by a fixed number, rather than a percentage 

http://kafra.kr/#!/en/KRO/skillinfo/2568

**Comment by aleos89** [comment]
rAthena currently grants Heat Barrel at a fixed value, not as a percentage.

**Comment by LordWhiplash** [comment]
I've just applied the #4428 and checked on master, the place and code of the bonus is exactly equals mine, and in my tests, the aspd is in %.

Just to confirm i'm not missinterpreting what fixed means... it means that ASPD bonus will ever be +5, independent of user stats, right?

image
(1 agi, no Heat Barrel)

image
(1 agi, Heat Barrel level 5)

image
(130 agi, no Heat Barrel)

image
(130 agi, Heat Barrel level 5)

**Comment by aleos89** [comment]
I tested on kRO and confirmed it is a fixed amount.

**Comment by erosama28** [comment]
i want to confirm the formula above increases the attack at the end of the formula. AFAIK it factors only weapon attack much like racial modifier correct .

**Comment by erosama28** [comment]
`	//Skill damage modifiers that stack linearly
	if(sc && skill_id != PA_SACRIFICE) {
		if(sc->data[SC_OVERTHRUST])
			skillratio += sc->data[SC_OVERTHRUST]->val3;
		if(sc->data[SC_MAXOVERTHRUST])
			skillratio += sc->data[SC_MAXOVERTHRUST]->val2;
		if (sc->data[SC_HEAT_BARREL])` i'm trying to code this on my own server and based on all video i reviewed heat barrel should add the modifier linearly.

**Pull request merged**
