### PR TITLE
Summoner Eden Group Equip Quest Implementation

### PR DESCRIPTION
**Pull request by MysticFurur0RE**
#1151 Issue

this https://github.com/rathena/rathena/commit/bf82a8edc298a64bbf3b147e50a550157b50e1ff 
Job_Summoner job detection
It not detected in script that ask for the job

Example: EDEN GROUP EQUIPAMENT QUEST

### CODE REVIEW

**Comment by Atemo** [comment]
Can someone confirm this ?

**Comment by MysticFurur0RE** [comment]
test

**Comment by MysticFurur0RE** [comment]
https://github.com/rathena/rathena/commit/d83559cb7fe4357f6cd9458987b6c7a9988c0e94

**Comment by spinzaku** [comment]
I tried this on my server.. Had problems:
players couldn't click anything.. and get stuck
13555739_1018901414861013_1253286108_o
michaelerror
[eden_quests.txt](https://github.com/rathena/rathena/files/333712/eden_quests.txt)

**Comment by Atemo** [comment]
Thanks you.

**Pull request closed without merging**
