### PR TITLE
feature/restore animation from sonicblow/vulcan arrow/cross impact

### PR DESCRIPTION
**Pull request by AoShinRO**
* **Addressed Issue(s)**:  recoding  https://github.com/rathena/rathena/pull/8088

* **Server Mode**:  both

* **Description of Pull Request**:  Add a feature config to force src send packets to restore hardcoded animation from sonicblow and vulcan arrow removed from ragexe 20181128+ using pre-renewal mode
https://ragnarok.fandom.com/wiki/RO_Patch_(2018_Nov._28)
maybe it's a work from 4144 😄 client sided hex edit but still without solution from years

-> Added Cross Impact Amotion removed at 2019/10/16
https://ragnarok.fandom.com/wiki/RO_Patch_(2019_Oct._16)
-> Changed to be used on renewal too
-> Pre-Renewal stop attack call added
-> Added aspd motion on packet send
-> Added monster rotation in sonic blow
-> Added multi-spamming support to animation

https://github.com/user-attachments/assets/6bcf79ff-bf22-4763-b8bc-bf9d5ac2f488

https://github.com/user-attachments/assets/ba569a1c-da93-4f3c-ac49-1b24e9f47df9

https://github.com/user-attachments/assets/b64e58a5-62ca-4863-9f27-f354ee4b23ed

TODO:
- [x] Fix duplicated msg when sd fail on skill_check_condition_castbegin

### CODE REVIEW

**Comment by AoShinRO** [comment]
Do you played with bard or sinx on Pré-re? if you test it let me know what you think if is not been like oficial behavior, and give details about that

**Comment by thanna** [comment]
HI @AoShinRO, tested your pull. when enabled on feature.conf there seems to be an error when ever I use sonic blow and arrow vulcan.

image

**Comment by AoShinRO** [comment]
> HI @AoShinRO, tested your pull. when enabled on feature.conf there seems to be an error when ever I use sonic blow and arrow vulcan.
> 
> image

this packet is converted to struct, you need to update clif packet...

**Comment by thanna** [comment]
> > HI @AoShinRO, tested your pull. when enabled on feature.conf there seems to be an error when ever I use sonic blow and arrow vulcan.
> > image
> 
> this packet is converted to struct, you need to update clif packet... [AoShinRO/brHades@8cf22ee](https://github.com/AoShinRO/brHades/commit/8cf22ee35fea93e89393ba6207ff04849fbdbccb)

works like a charm, works just like the original client thing. great work @AoShinRO.

**Comment by thanna** [comment]
> > HI @AoShinRO, tested your pull. when enabled on feature.conf there seems to be an error when ever I use sonic blow and arrow vulcan.
> > image
> 
> this packet is converted to struct, you need to update clif packet... [AoShinRO/brHades@8cf22ee](https://github.com/AoShinRO/brHades/commit/8cf22ee35fea93e89393ba6207ff04849fbdbccb)

not nitpicking or anything but is there a fix for facing the wrong direction when using sonic blow & vulcan arrow? I attached a gif below so that you can see what I mean. thank you for this update.

sonicblow

**Pull request closed without merging**
