### PR TITLE
Fixed random options with negative values being stored as 0 in database.

### PR DESCRIPTION
**Pull request by secretdataz**
* **Addressed Issue(s)**: #2415
* **Server Mode**: Both
* **Description of Pull Request**: 
This pull request removes the `unsigned` modifier for random option columns in rAthena's MySQL script. Upgrade scripts are also provided.

### CODE REVIEW

**Comment by Jeybla** [comment]
Looks fine. Just for clarifications: When dies these values become negative?

**Comment by secretdataz** [comment]
@Jeybla It can be seen in the referenced issue.

**Comment by Jeybla** [comment]
Ah, thanks. Didn't see that.

**Comment by secretdataz** [comment]
@Jeybla Since the client could display the -5 value for the item holder just fine, I concluded that both the client and the server should support signed values and the zero value is just an item link bug.

**Pull request merged**
