### PR TITLE
Initial support for Star Emperor and Soul Reaper

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: None

* **Server Mode**: Renewal

* **Description of Pull Request**:
Mostly placeholders for now, but you can switch to the jobs at least and play with them(without their skills).
Merges 3CeAM/3CeAM@7df0f57 and 3CeAM/3CeAM@028d2e8
Credits to @Rytech2 for his amazingly fast work!

### CODE REVIEW

**Comment by idamonli** [comment]
The lack of 20180530 packets

**Comment by Lemongrass3110** [comment]
What packets are missing? Everything worked fine for me by settling PACKETVER to 20180530

**Comment by Questune09** [comment]
thank you is it possible to merge 2018 sprites to 2017 hahah

works perfectly but im missing sprites after using ctrl S and ctrl Q

2017 client ahahah

image

**Comment by Lilori** [comment]
20180530 , it becomes Novice Sprite, any help?
cc: @Lemongrass3110 @Badarosk0

**Comment by Lemongrass3110** [comment]
Please use the board for this kind of questions.
Thank you.

**Comment by Lilori** [comment]
Sorry, my bad.

**Comment by xTakami** [comment]
Will the missing information be added?

**Comment by Mateuus** [comment]
@Lemongrass3110 It would be cool to continue this Pull Request
https://github.com/rathena/rathena/pull/3800/commits/557d7cfdc8723f4584834ea77b001e00c1c749f3

**Pull request merged**
