### PR TITLE
Few Genetic skill fixes

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: N/A

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Fixes Acid Demonstration to use the target's VIT and not casters.
  * Fixes Crazy Weed not doing 2 damage attacks.
  * Crazy Weed is now a long ranged physical attack.
  * Fixes Hell's Plant attack formula when learning Summon Flora.
  * Hell's Plant now uses the caster's weapon as the element.
  * Hell's Plant no longer ignores the target's DEF and Element.
  * Removes fixed cast time from Xeno Slasher.
Thanks to @teededung and @Badarosk0!

### CODE REVIEW

**Comment by Badarosk0** [comment]
produce_db


Concentrated Golden Syrup Potion
Recovers about 2750 HP
Require Level : 180
Weight : 0.2
Recipe : Empty Test Tube 10 ea + Empty Potion Bottle 10 ea + White Syrup 10 ea + Yellow Syrup 10 ea.

Change from Yellow Syrup 15 ea to Yellow Syrup 10 ea.

**Comment by cahya1992** [comment]
Screenshot_235
i got crash map when used this pull

**Comment by LordWhiplash** [comment]
Just tested, fire expansion acid is working now! Thanks!

**Comment by Badarosk0** [comment]
The Spore Explosion skill should generate a first major damage and a second minor damage. The first damage is the same value as the second damage.
```
스포어 익스플로젼
MAX Lv : 10
습득조건 : 스페셜 파머시 4
계열 : 액티브 / 데미지
내용 : 대상 1 체에게 폭발성 버섯 포자를 붙여 1차적으로 대상에게 원거리 물리 데미지를 준 뒤, 폭발시켜 2차적으로 대상 및 주변에 원거리 물리 데미지를 준다.
1차 데미지는 시전자의 BaseLv 및 INT에 따라 데미지가 증가되며, 2차 데미지는 시전자의 BaseLv에 따라 데미지가 증가된다.
스킬 사용시 [폭발 버섯 포자] 를 하나 소모한다.
[Level 1] : 공격력 380%/180%/범위: 3x3셀
[Level 2] : 공격력 560%/360%/범위: 3x3셀
[Level 3] : 공격력 740%/540%/범위: 5x5셀
[Level 4] : 공격력 920%/720%/범위: 5x5셀
[Level 5] : 공격력1100%/900%/범위: 7x7셀
[Level 6] : 공격력1280%/1080%/범위: 7x7셀
[Level 7] : 공격력1460%/1260%/범위: 9x9셀
[Level 8] : 공격력1640%/1440%/범위: 9x9셀
[Level 9] : 공격력1820%/1620%/범위:11x11셀
[Level10] : 공격력2000%/1800%/범위:11x11셀
```

**Comment by Badarosk0** [comment]
Skill Hell's Plant must continue with the effect when changing maps, teleporting or entering any warp. What happens is the disappearance of the visual effect only. The skill's effect continues.

kRO confirm:
https://youtu.be/qYPSy0EX4J8

**Comment by aleos89** [comment]
So how I have this coded now won't work since the config for clearing skill units on map changes exists. I'm wondering if this is a bug on kRO or if it's really intended to persist through map changes.

**Comment by Badarosk0** [comment]
The Hell's Plant icon is missing.
status.cpp
```
  StatusIconChangeTable [SC_HELLS_PLANT] = EFST_HELLS_PLANT_ARMOR;
```

**Pull request merged**
