### PR TITLE
Thanatos Tower Minor Fix

### PR DESCRIPTION
**Pull request by admkakaroto**
Minor fix to quest progression with summoner job.
* **Addressed Issue(s)**: https://github.com/rathena/rathena/issues/4369
* **Server Mode**: RE
* **Description of Pull Request**: Just add Summoner Job check.

### CODE REVIEW

**Comment by JohnnyPlayy** [comment]
You read my mind, I thought of doing the same thing

**Comment by Lemongrass3110** [comment]
Needs to be confirmed on kRO.

**Comment by Lemongrass3110** [comment]
@Tokeiburu do you have any info from kRO? My last check on this was negative and summoner was not added to this check on official.

**Comment by Everade** [comment]
Most likely obsolete due the Thanatos Tower revamp that took place last december.

The new update replaced the entire upper floor with an instanced Memorial Dungeon, new monsters armor sets and more.

Sources:
Official Release Information:
http://ro.gnjoy.com/news/update/View.asp?seq=247&curpage=1

Official Related Event:
http://ro.gnjoy.com/news/event/View.asp?Seq=936&kind=A&curpage=1

Translations:
https://www.divine-pride.net/forum/index.php?/topic/4277-kro-thanatos-tower-revamp/
https://www.divine-pride.net/forum/index.php?/topic/4242-kro-changelog-december-04-2019/

Devnotes:
http://ro.gnjoy.com/news/devnote/View.asp?category=1&seq=4004954&curpage=1

**Pull request merged**
