### PR TITLE
Update Mobs Renewal

### PR DESCRIPTION
**Pull request by Pokye**
* **Addressed Issue(s)**: https://github.com/rathena/rathena/issues/6610

* **Server Mode**: Renewal

* **Description of Pull Request**: As promised, I finished updating the mob_db Renewal here according to Divine-Pride.

TODOs:

- [x] MvpExp
- [x] Drops and MvpDrops
- [x] Fix Name of Mobs
- [ ] New Itens

Special thanks to @Atemo for the support.

### CODE REVIEW

**Comment by RagnaWay** [comment]
Missing 4 items in rA and **Broken_Magic_Stone** does not exist the correct is: **Shattered_Rune** ( https://www.divine-pride.net/database/item/6905 )

https://www.divine-pride.net/database/item/23817
https://www.divine-pride.net/database/item/23258
https://www.divine-pride.net/database/item/23257
https://www.divine-pride.net/database/item/11606

**Comment by Pokye** [comment]
> Missing 4 items in rA and **Broken_Magic_Stone** does not exist the correct is: **Shattered_Rune** ( https://www.divine-pride.net/database/item/6905 )
> 
> https://www.divine-pride.net/database/item/23817 https://www.divine-pride.net/database/item/23258 https://www.divine-pride.net/database/item/23257 https://www.divine-pride.net/database/item/11606

Yes. You're right, I'll fix it. And about the missing items, unfortunately I'll leave it to rA to implement I'm not good at it especially with combo item and etc.

**Comment by Lemongrass3110** [comment]
> Missing 4 items in rA and **Broken_Magic_Stone** does not exist the correct is: **Shattered_Rune** ( https://www.divine-pride.net/database/item/6905 )
> 
> https://www.divine-pride.net/database/item/23817 https://www.divine-pride.net/database/item/23258 https://www.divine-pride.net/database/item/23257 https://www.divine-pride.net/database/item/11606

How often do I have to tell you to stop this...?

**Comment by RagnaWay** [comment]
> > Missing 4 items in rA and **Broken_Magic_Stone** does not exist the correct is: **Shattered_Rune** ( https://www.divine-pride.net/database/item/6905 )
> > https://www.divine-pride.net/database/item/23817 https://www.divine-pride.net/database/item/23258 https://www.divine-pride.net/database/item/23257 https://www.divine-pride.net/database/item/11606
> 
> How often do I have to tell you to stop this...?

Stop being an asshole! I'm just reporting to the guy that 4 items are missing and 1 is misnamed.

**Comment by Everade** [comment]
Seems like you've added `DamageTaken: 10` to all monsters with the boss attribute.
Please note that only monsters with a green aura should have the reduced incoming damage buff as defined client side.
As such these changes should be reverted.

Also removed a lot of monster AI, however basically every monster should have an AI.
Divine possibly just lacks some data here, i wouldn't trust it too much.

Some of the added MVP drops are odd on divine-pride.
For example monster id 1956, 1816 and 2066
You added MvpDrops, yet both monsters have no MVP mode nor do they show mvp drops on any official server database.
Possibly false data on divine-pride too due to data mining issues?!

Not sure if `#DP New Type Ai: MERCENARY_TYPE_02` needs some new AI behavior, but this would most likely take place in the mercenary_db.

Please note that i only did a quick check half-way through as there are possibly more issues such as the removed attack and defense data from id 3790.

**Comment by Pokye** [comment]
> Seems like you've added `DamageTaken: 10` to all monsters with the boss attribute. Please note that only monsters with a green aura should have the reduced incoming damage buff as defined client side. As such these changes should be reverted.
> 
> Also removed a lot of monster AI, however basically every monster should have an AI. Divine possibly just lacks some data here, i wouldn't trust it too much.
> 
> Some of the added MVP drops are odd on divine-pride. For example monster id 1956, 1816 and 2066 You added MvpDrops, yet both monsters have no MVP mode nor do they show mvp drops on any official server database. Possibly false data on divine-pride too due to data mining issues?!
> 
> Not sure if `#DP New Type Ai: MERCENARY_TYPE_02` needs some new AI behavior, but this would most likely take place in the mercenary_db.
> 
> Please note that i only did a quick check half-way through as there are possibly more issues such as the removed attack and defense data from id 3790 or Id 2599 isn't a Boss class according to DP.

I just followed the divine-pride. 
And about the #DP New Type Ai: MERCENARY_TYPE_02 Atemo said he would see about it, he asked me to add this information to the mobs to know later.
```
PS C:\Users\pokye> dp2rathena mob 1956
Header:
  Type: MOB_DB
  Version: 2
Body:
- Id: 1956
  AegisName: NAGHT_SIEGER
  Name: Naght Sieger
  Level: 99
  Hp: 5000000
  BaseExp: 2160000
  JobExp: 900000
  Attack: 7020
  Attack2: 3200
  Defense: 410
  MagicDefense: 40
  Str: 190
  Agi: 60
  Vit: 80
  Int: 220
  Dex: 317
  Luk: 30
  AttackRange: 2
  SkillRange: 16
  ChaseRange: 16
  Size: Large
  Race: Demon
  Element: Ghost
  ElementLevel: 4
  WalkSpeed: 100
  AttackDelay: 76
  AttackMotion: 432
  DamageMotion: 504
  Ai: 21
  Class: Boss
  MvpDrops:
  - Item: Old_Violet_Box
    Rate: 5500
  Drops:
  - Item: Twin_Edge_B
    Rate: 4500
  - Item: Twin_Edge_R
    Rate: 4500
  - Item: Flame_Manteau
    Rate: 4500
  - Item: Bone_Helm
    Rate: 4500
  - Item: Old_Card_Album
    Rate: 4500
  - Item: Pauldron
    Rate: 4500
  - Item: Turquoise
    Rate: 4500
  - Item: Nahtzigger_Card
    Rate: 1
    StealProtected: true

PS C:\Users\pokye> dp2rathena mob 2599
Header:
  Type: MOB_DB
  Version: 2
Body:
- Id: 2599
  AegisName: G_WILD_RIDER
  Name: Invader!
  Level: 95
  Hp: 33300
  BaseExp: 0
  JobExp: 0
  Attack: 1320
  Attack2: 330
  Defense: 480
  MagicDefense: 22
  Str: 89
  Agi: 124
  Vit: 89
  Int: 56
  Dex: 112
  Luk: 56
  AttackRange: 1
  SkillRange: 10
  ChaseRange: 12
  Size: Large
  Race: Fish
  Element: Water
  ElementLevel: 2
  WalkSpeed: 120
  AttackDelay: 432
  AttackMotion: 792
  DamageMotion: 360
  Ai: 04
  Class: Boss

PS C:\Users\pokye> dp2rathena mob 3790
Header:
  Type: MOB_DB
  Version: 2
Body:
- Id: 3790
  AegisName: SWEETS_DROPS
  Name: Sweet Drops
  Level: 1
  Hp: 20
  BaseExp: 0
  JobExp: 0
  Str: 1
  Agi: 1
  Vit: 1
  Int: 1
  Dex: 1
  Luk: 1
  AttackRange: 1
  SkillRange: 10
  ChaseRange: 12
  Size: Medium
  Race: Plant
  Element: Fire
  ElementLevel: 1
  WalkSpeed: 440
  AttackDelay: 1372
  AttackMotion: 672
  DamageMotion: 480
  Ai: 02
  Drops:
  - Item: Stolen_Cacao
    Rate: 10000
  - Item: Stolen_Cacao
    Rate: 7000

**Comment by Everade** [comment]
Unfortunately dp isn't the holy grail for everything. And there are obviously various issues with the automated conversion you've used as stated in a few examples above.

**Comment by Pokye** [comment]
I'm going to close this PR and open a new one just with the **MvpExp** fix and some **AegisName** fixes.

**Pull request closed without merging**
