### PR TITLE
Implemented missing skills

### PR DESCRIPTION
**Pull request by Atemo**
* **Addressed Issue(s)**: Part of https://github.com/rathena/rathena/issues/1525

* **Server Mode**: renewal

* **Description of Pull Request**: 

Implemented some missing skills according to Aegis data.

### CODE REVIEW

**Review by Lemongrass3110 — APPROVED** [review]
Looks perfectly fine!
Just some additions for your final commit message for documentation reasons:

- NPC_WIDESTONE2 is missing in commit messages/description
- NPC_BLEEDING2 different rates should be "higher chance to cause bleeding", because hitrate seems to be the same.
- You added some more new skill id constants. Do we need to create an issue for those or do we want to add them in #1525?

**Comment by Atemo** [comment]
The mob skill db can be updated later, let's focus on the skill db

**Comment by AbsoluteXeroEX** [comment]
I've tested a small handful of these using the mob additions from #7207 and they appear to be working quite well so far. I'll do more testing with some of the other mobs that use the other skills before I work on my own mob skill db update.

**Review by aleos89 — APPROVED** [review]

**Comment by Atemo** [comment]
>     * NPC_BLEEDING2 different rates should be "higher chance to cause bleeding", because hitrate seems to be the same.
> 

The rates are set in
https://github.com/rathena/rathena/pull/7552/files#diff-35e92cf6786714f700005941b58d63e942fb78afd9330d2027cf30e7c5c3dedaR1641

**Comment by fab10Carvalho** [comment]
please check this

https://github.com/fab10Carvalho/rAthena_z/pull/1

**Comment by Atemo** [comment]
I don't plan to add more skill in this PR.

**Comment by Lemongrass3110** [comment]
@fab10Carvalho feel free to open a PR to rathena/rathena. You opened one for your own fork fab10Carvalho/rAthena_z

**Pull request merged**
