### PR TITLE
Small optimization on change sex

### PR DESCRIPTION
**Pull request by Daegaladh**
* **Addressed Issue(s)**: N/A

* **Server Mode**: Both

* **Description of Pull Request**: Small optimization when changing sex from sex specific classes.

### CODE REVIEW

**Review by Atemo — APPROVED** [review]

**Review by aleos89 — APPROVED** [review]

**Review by aleos89 — APPROVED** [review]
A little longer but I see no issue in that since now it's much safer and less assumptions about the expected class.

**Comment by SapitoSucio** [comment]
Could be done like this too, to shrink it a lil bit
```
switch (class_) {
	case JOB_BARD: class_ = JOB_DANCER; break;
	case JOB_DANCER: class_ = JOB_BARD; break;
	case JOB_CLOWN: class_ = JOB_GYPSY; break;
	...
```

**Comment by Daegaladh** [comment]
> Could be done like this too, to shrink it a lil bit
> 
> ```
> switch (class_) {
> 	case JOB_BARD: class_ = JOB_DANCER; break;
> 	case JOB_DANCER: class_ = JOB_BARD; break;
> 	case JOB_CLOWN: class_ = JOB_GYPSY; break;
> 	...
> ```

I could, but I thought it would be clearer this way

**Comment by aleos89** [comment]
> Could be done like this too, to shrink it a lil bit
> 
> ```
> 
> switch (class_) {
> 
> 	case JOB_BARD: class_ = JOB_DANCER; break;
> 
> 	case JOB_DANCER: class_ = JOB_BARD; break;
> 
> 	case JOB_CLOWN: class_ = JOB_GYPSY; break;
> 
> 	...
> 
> ```

As my professor always said, white space is free when developing!

**Pull request merged**
