### PR TITLE
Checkweight Ring of Wise King (Fixes #910)

### LINKED ISSUE #910: 13.2 quests: getitem vs player overweight
In the npc/quests/quests_13_2.txt we have some `getitem`s for items that weigh > 0 like `getitem 2782,1; //Ring_Of_Wise_King` and `getitem 7574+.@num,1;` at `jewel_13_2` function. But we do also need a player's current weight check there. When a player has no free weight (especially if he was overweighted during the dialog) and is to receive a quest item, an item isn't received and the quest continues, leaving a player no opportunity to attempt to get that item again. 

Latest commit: 6a62aab 
Mode: Renewal AND Pre-Renewal

### PR DESCRIPTION
**Pull request by Jeybla**
Issue #910, just a simple fix.

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
I kind of dislike to do this check silently without telling the user why he did not get his reward.
Maybe adding a custom dialog would be a good solution.
What do you guys think @rathena/rathena-script-db-developers?

**Comment by cydh** [comment]
Just remain your players to make sure that there's empty slot in inventory & not overweight :v

**Comment by secretdataz** [comment]
@Lemongrass3110 I agree, adding a custom dialog is the best way while we don't have any global solution for this imo.

**Comment by Jeybla** [comment]
@Lemongrass3110 you're absolutely right.

**Comment by Lemongrass3110** [comment]
Sorry to tell you, but I think the check you added should be before the "thank you, here have this ring" stuff.
Then I guess it could be merged.

**Comment by Atemo** [comment]
Please move the check at the beginning of the npc, like the others check in official npc.

**Comment by aleos89** [comment]
@Jeybla : If you want to update this, then it can be merged. :+1:

**Comment by secretdataz** [comment]
Merged in 055ee42b3d6bfe035c235b7aa7d9ac7bc935feef.

**Pull request closed without merging**
