### PR TITLE
Updated default PACKETVER

### PR DESCRIPTION
**Pull request by Akkarinage**
It makes no sense to use 20130807 as the default PACKETVER when we use 55 (20151104) as the default packet_ver in /db/packet_db.txt

Signed-off-by: Akkarinage akkarin@rathena.org

### CODE REVIEW

**Comment by CairoLee** [comment]
New mail system(RODEX) and the

**Comment by CairoLee** [comment]
RODEX New Mail System Feature
Clan System Feature
Pet Evolution System Feature
Achievement System (New Extra Quest) Feature
Title System Feature

they are not implemented

**Comment by Akkarinage** [comment]
We fully support the client and it doesn't (afaik) break anything we currently have, which is why we already have default_packet_ver set for this client. Setting PACKETVER to this client data doesn't mean a great deal, as most users change it anyway.

Some of the above features would make their way into the master branch quicker if people bothered to test the PRs that are available.

**Comment by cydh** [comment]
The part that must be change is `packet_db_ver: default` in packet_db instead change the PACKETVER.
Say, if follow every latest packet supported, PACKETVER must be changed.
Well, it's not significant for me, I put many local gitignores for some files. xD

**Comment by CairoLee** [comment]
We can let the packet_db_ver support auto mode.
if set packet_db_ver to auto, then map-server will read PACKETVER and set the match packet_db_ver value.

Sorry for my bad english XD

**Comment by aleos89** [comment]
I see no problem updating the PACKETVER to 2015+. The clients are stable for play which is the main point. Just because all of the features of the client aren't fully supported by rAthena doesn't seem (to me at least) to be a reason to hold it back from updating it. If we hold to this standard, then that means we shouldn't be on 2013 since we don't support the BG Queue.

**Pull request merged**
