### PR TITLE
Corrected some statuses and Mado Gear interaction

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: N/A

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Follow up to 0d81697.
  * Added a separate check for Mado Gear and blocking Merchant/Blacksmith/Whitesmith specific statuses.
  * Harmonized the statuses with the new allowed skill list.
Thanks to @slyx88!

### CODE REVIEW

**Comment by slyx88** [comment]
Based on  Ziu's latest video on kRO mado mechanic, few additional statuses can be received while on mado:
1) Magnificat
2) Increase Agi
3) Renovatio

https://www.youtube.com/watch?v=E-jhwkIYD7Y

**Comment by aleos89** [comment]
Would be nice if we had a more solid list.

**Comment by Badarosk0** [comment]
Maximum Power Thrust and Power Thrust work with MADO in kRO.

**Comment by RagnaWay** [comment]
Update and Merge pls <3

**Comment by admkakaroto** [comment]
@aleos89 please, merge this! :D

**Comment by admkakaroto** [comment]
This need be updated:

```
error C3861: 'skill_get_inf3': identifier not found
error C2065: 'INF3_USABLE_MADO': undeclared identifier
```

**Comment by Badarosk0** [comment]
Could you please update? @aleos89 
Thank you

**Pull request merged**
