### PR TITLE
Fixed a few name typos with Niflheim

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: None

* **Server Mode**: Both

* **Description of Pull Request**: 
There are a few typos with the name Niflheim all over the place.
I simply searched and replaced them with the correct spelling with only one F.

### CODE REVIEW

**Comment by Daegaladh** [comment]
There are some "niffleheim", "niffleim", "niffelheim" and "nifleheim" too.

**Comment by Lemongrass3110** [comment]
I only found niffleheim in the item db, where it is actually spelled incorrectly by iRO:
https://www.divine-pride.net/database/item/20398
I am not really sure what to do about that...
Thanks for the others though! 👍

**Comment by Everade** [comment]
**Niffleheim** is actually correct.
It is traditionally spelled **Niflheim** though.

**Comment by Lemongrass3110** [comment]
Even though I like Marvel their interpretation of the norse mythology is even further away from the real deal than the stories in Ragnarok Online, so we are going to stick with Niflheim, since that also matches the mapname and a lot of other references in NPCs and client side data.

**Comment by Freyja-Folkvangr** [comment]
Are these ???? marks ok?
screen shot 2018-01-17 at 12 15 47

**Pull request merged**
