### PR TITLE
Update ticket_refiner.txt

### PR DESCRIPTION
**Pull request by AsurielRO**
* **Addressed Issue(s)**: 

* **Server Mode**:   Renewal

* **Description of Pull Request**: 

On KRO Refine Master can also refine item using +12 Weapon Certificate and +12 Armor Certificate

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
@Atemo can you check this please? :-)

**Comment by Atemo** [comment]
The NPC exists on KRO ? It doesn't exist in the navi files. Also
https://github.com/rathena/rathena/pull/4444/files#diff-413bd0e173c855d1929d2617fd4a6485d1c7eae37a2c180e076716966bb4215eR13
```
//= [Official Conversion]
...
//= NOTE: This NPC is currently disabled on official servers.
```

**Comment by Balferian** [comment]
@Atemo yes, kRo have this npc.

**Comment by Lemongrass3110** [comment]
Well the part with equipmentlv switching for 5 & 6 is definitely wrong, but maybe some part of this PR could be used.

**Comment by AsurielRO** [comment]
Sorry guys i accidentally deleted my branch regarding this that's why i can't update :(, but yeah this is excist on KRO.

**Comment by Balferian** [comment]
https://youtu.be/RLmn9BbnE6M?t=82
and it seems there are more coupons in the list than we have now in script

**Pull request closed without merging**
