### PR TITLE
Migrated script.c to C++ 2.0

### PR DESCRIPTION
**Pull request by Daegaladh**
Reverts rathena/rathena#2403

### CODE REVIEW

**Comment by Jeybla** [comment]
Original Pull Request: #2395

**Comment by Daegaladh** [comment]
Comments on compile warnings: #https://github.com/rathena/rathena/commit/965edbf47d5044e29c011c621f5129008c85b7aa#commitcomment-24092722

**Comment by Mikegyver** [comment]
can't wait for this to be merge into master branch...

**Comment by Mikegyver** [comment]
just notice slight different on compiling of the one yesterday & the latest commit of this PR.

not cpp 1

not cpp 2

on compiling into src/map directory, on yesterday, it compiles script.cpp while today it compiles script.c
i'm not sure what are diferent between those 2. just want to notify u guys. xD

**Comment by Daegaladh** [comment]
@Mikegyver that's because the commit was reverted, wait til it's applied again, or download my branch Daegaladh:revert-2403-revert-2395-master for testing

**Comment by Mikegyver** [comment]
Well.. i'm using ur revert-2403-revert-2395-master for testing.. just add ur repo into remote branch and fetch this branch & do the testing.

**Comment by Mikegyver** [comment]
Well.. i'm using ur revert-2403-revert-2395-master for testing.. just add ur repo into remote branch and fetch this branch & do the testing.

git status

**Comment by Daegaladh** [comment]
@Mikegyver That's weird, that branch should have script.cpp, look: https://github.com/Daegaladh/rathena/blob/revert-2403-revert-2395-master/src/map/script.cpp
Try with a fresh checkout

**Comment by Mikegyver** [comment]
Ok. I'll let u know later once i'm done it.. xD

**Pull request merged**
