### PR TITLE
Refactored/Cleaned Visual-Studio Solutions

### PR DESCRIPTION
**Pull request by secretdataz**
* **Description of Pull Request**: 

This pull request removes old Visual Studio 2008, 2010, 2012, 2013, and 2015 solution and projects.  
This pull request also adds a new and clean Visual Studio 2013 solution.  

Support for Visual Studio older than 2013 will also be dropped as a result of merging,  

Each component has its own project.
The Core (common) is also a stand-alone project (static-lib) = no more redundant source-refs in all projects.

For further reading please see #1208.

This pull request is based on @wilkemeyer's pull request.  All credit goes to him.

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
Could you add the missing EOLs?

**Comment by secretdataz** [comment]
@Lemongrass3110 done

**Comment by Akkarinage** [comment]
It's about time we dropped the crusty old versions of Visual Studio!

**Comment by anacondaqq** [comment]
## tl;tr

**Main idea:** if you need rathena to compile, git clone rathena repo, download gcc/clang pack (50-100mb) click "compile.cmd" and you will be able to run emulator on windows platform (of course such people need to download MySQL package too, but this is another story & [problem which very easy to cover](https://rathena.org/board/topic/109823-ragnarok-online-complete-offline-pack-2017-make-your-ro-server-in-less-then-5-minutes/)). And if you are a developer, and you adding source code, or you edit source code of course you will need something more powerful then clang/gcc compiler, so download and install professional very big tool for this.





## Related to #1208 comment:

> Solution & all Project's are created with/for 2013, the Platform Toolset of all Project's is also 2013 by default.

> When working with Visual Studio 2015 - just open The Solution & just don't upgrade it - you'll be fine.
**_If you're running VS2015 without 2013 Installed, you'll need to change the platform Toolset in all projects to their 2015 counterpart._**


I'm worried that highlighted above text will be a reason of hell a lot of problems for many developers.
Why? Because latest version of the free visual studio is 2017 and this product will be advertised as the main one by Microsoft, and people will be confused what version to use and will make mistakes, etc. Before it was main for 2 years 2015 one, then hell a lot of people still using VS2010 just for compilation purposes. 

#### Another problem related to:

> This pull request removes old Visual Studio 2008, 2010, 2012, 2013, and 2015 solution and projects.

Yes, I understand that is painful to support different solutions at the same time and better concentrate on the only one thing then divide focus into all different parts. But let me explain critical for me & for all friends who has their own servers or joined to development problems, they are in next:

> 1. Around 90% of all known by me people don't even use even 10% of all features at Visual Studio (like debugger, their different awesome features which help easy & safe code, etc) All for what they need Visual Studio it's just for compilation/recompilation software, nothing more.

> 2. Related to `1.` we have next problem related to internet bandwidth, the total size of the visual studio, etc. For just "re-compile or compile" rathena newbie user must download around 8GB of data. This is a very big pain for people with a limited connection (people from Europe / North America can ignore it) but people in SEA region experience really big problems with BW, and downloading 8GB of data just for recompiling it's very bad and painful for them.


### Based on problems above I suggest next:

How about adding some alternative to dropped 2008 / 2010 VS Express (their size ~100MB) just to feed most important needs of people who will use the source code for compilation/recompilation only. For example some package or basic script or alternative guide which will use clang + GCC for recompilation project? Of course, I'm talking only about Windows platform. 

I'm talking about solution to make easy to use something like this: http://herc.ws/board/topic/6043-showcase-clang4win/

Or something like this https://github.com/Cronus-Emulator/clang

As an addon, i already saw it somewhere some time ago possible to add gdb for debugging.
But this is a just suggestion.

### Why

Imagine that you need just download 50-100MB archive with clang/gcc compiler which will compile rathena src code or recompile source code to .exe for windows, not need to download 8GB of Visual Studio data just for very common things like compilation. BW saved, time saved, space saved. 

### Problems related to clang

1. `clang rathena compilation pack` must be packed to archive and hosted somewhere at rathena with mini-guide how to use it. 

2. clang/gcc very hard to configure & understand for people, so need ready2use solution like http://herc.ws/board/topic/6043-showcase-clang4win/ where you just copy clang from portable pack & replace `path` to use path of clang then you run "compile.cmd" and violia you have compiled or recompiled .exes in rathena folder.

### Why am I write here, and not at ra board?

I think At rAthena board such topic will be inactive & nobody will even read it, or even comment. But here is a good place in good issue where fundamental changes will happen.

Because this is a really critical problem and developers maybe need to review it again and rethink it. If you decide to break fundamental things with project solutions and drop hell a lot of solutions like VS2010, VS2012, VS2015, how about making some modern and actual "tool" which will cover 99% administrator needs in terms of compilation? While other people who really need Visual Studio for doing great professional things with code like debugging & use all features which offer Visual Studio will use latest Visual Studio or only one offered by rAthena.

**Comment by Akkarinage** [comment]
They're not being dropped for the hell of it, they're being dropped because they're no longer supported by Microsoft, or shortly coming to the end of their main support cycle. I don't see any reason to replace old defunct methods of compiling with something different. VS has worked well enough for us for the last decade.

**Comment by anacondaqq** [comment]
> I don't see any reason to replace old defunct methods of compiling with something different. 

You don't get my point in the message above. Let me repeat.

## Problem 1, very big size just for 1 task. This task called "compilation"

| Product        | Size to download / store |
| ------------- |---------------|
| VS 2010 C++ Express      | ~130 MB | 
| VS 2013 Community (update 5)     | 2.800MB, it's 20x more then VSE2010 |
| VS 2015 Community      | 5.900MB, it's 45x more then VSE2010 |
| VS 2017 Community      | 8.100MB, it's 62x more then VSE2010 |

If you personally have powerful PC & unlimited 100mbit/s internet it's ok, but not all people here have it.
Even for me with 100mbit/s unlimited connection which cost 2$ download & installs 11GB of data it's pretty painful. But personally I use rathena not for compiling, I write code too, and visual studio in my case really important. 

But how many people who do not write code, or need emulator just to compile it? How many people just apply patches from rathena board src section, or grab latest updates via git? How many people who have limited internet, or very slow internet? How many people who just need VS 2010 C++ like a solution to solve their main problem -> make rathena work on windows? Please, pay attention to this, since you decided to make significant changes, so let's do everything beautifully and correctly for years and next decades.

Download 62x more package just to compile sources to application i think it's way too much.

## Problem 2, why using 2013? There are no sense at all

You said:
They're not being dropped for the hell of it, they're being dropped because they're no longer supported by Microsoft.

The last update for VS 2013 was at the 2015 year. 2 years ago! This version NO MORE ACTUAL. And there is no sense at all to focus on this version, while Microsoft announced their optimized VS 2017, which is community (free) too.


## Problem 3, by setting VS2013 default you add a trap for yourself & for newbies.

Because of: 

> If you're running VS2015 without 2013 Installed, you'll need to change the platform Toolset in all projects to their 2015 counterpart.

That means if someone using VS2017 (which is actual for now and offered by Microsoft by default) people will download only this. Because everything else hard to find at Microsoft website. That means people will download it (8-12GB of data (depends on user experience (if he totally newbie, he will install 12GB of data where will be used only 1GB of apps required for him)). Then after installation, he will try to run .sln file to compile his source code, and what will he see? Tons of errors because of not changed toolset in projects? 

> When working with Visual Studio 2015 - just open The Solution & just don't upgrade it - you'll be fine.

This part will be done 100% again and again by different people. That means = more stupid issues at issue tracker & at forum related to this stupid thing. 

# Problem 4, most important things what better to read.

Based on all 3 problems above, I made the suggestion, my suggestion in next:

1. You drop support for old VS2008, VS2010 Express, and do what you wish, and focused on the latest available version of Visual Studio (right now it's 2017). 2013 will be soon deprecated and already not popular anymore. People who develop code, or write their own custom code, or people for who bandwidth is not a problem will choose this one.

2. For people who need the ONLY compiler to compile source code, or recompile source code, and who don't need any more extra 8GB of data just to do only 1-2 tasks with code better to make clang/gcc thing.  Why? Because clang+gcc size will be around 100-150mb. It's not 10GB of data to download.
It's not 15GB of data to store on SSD drives for just compiling. It saves time, and it increases potential people who will join the development team. It will make rathena more newbie friendly and will bring more people. 

About second one, why this suggestion made:
Because you drop support for VS2010 Express. [This VS2010 Express size only 130MB](http://download.microsoft.com/download/1/D/9/1D9A6C0E-FC89-43EE-9658-B9F0E3A76983/vc_web.exe), and it easy to download and install in less then 3-5 minutes. 

(Again, this is just suggestion, I have some experience, and I can help, but I guess if people here knows better, their help will be much better than mine).

**Comment by Akkarinage** [comment]
I understand what you mean, i just don't think it's worth our time dropping older versions of VS to reintroduce additional compiler options for Windows when we all know that game servers should be ran and compiled on Linux anyway. I know we all test locally on Windows before pushing to our Linux hosted servers... or atleast we all **should**.

If it's just a matter of package size, I personally don't think that is a justifiable reason from a project perspective to add support for additional compilers. I've asked the devs on their thoughts though, as I do think that 8GB just for something to provide right-click & compile capabilities is abit overkill.

I'm all for removing support of deprecated VS versions, but i'm on the fence about adding support for more compilers. My personal opinions differ from my project-based opinions.

**Comment by anacondaqq** [comment]
okay, i got your point, and i understand developers. clang/gcc pretty hard to setup to. I will try in someday to release something like this guy did: http://herc.ws/board/topic/6043-showcase-clang4win/ at rathena board for all. If i will release it, that means no files will be changed at rathena current repo, will be added maybe maximum 1 bat file with instructions for clang. Anyway, thank you for your time & for reading my very weird wall of txt. Sorry, but i can't explain things in much shorter messages...

**Comment by secretdataz** [comment]
@anacondaqq The reason why @wilkemeyer choosed 2013 was stated in the previous PR.
In addition, 2013 was choosen because it has proper C++11 support as seen in [here](https://msdn.microsoft.com/en-us/library/hh567368.aspx).  
Currently, my plan on C++ rAthena has shifted to 'add C++ modules one by one with a C facade to link it with the rest of rA code', so eventually older versions of VS won't be able to compile rAthena without us dropping it like I do in this PR.  

If you are concerned about older versions of Visual Studio are still being used, I'd like to see a community-maintained solutions for older versions of VS.

**Comment by cydh** [comment]
@anacondaqq don't worry, they won't listen every logic issues. everything that matters are their each 'personal' goals. I'm fucked since this PR merged. F*cking thank you

**Comment by anacondaqq** [comment]
@cydh I will find a solution very soon, right now I'm very busy with personal projects, but soon the problem will be resolved and I will post & share it. I hope no edits will require.

**Pull request merged**
