### PR TITLE
Fixes Weapon Crush and Weapon Blocking combo

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: #4808

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Weapon Crush now uses SC_WEAPONBLOCK_ON to track the target instead of SC_COMBO.
  * Also fixes Quick Draw Shot target selection.
Thanks to @wdivet!

### CODE REVIEW

**Comment by ecdarreola** [comment]
@aleos89 error on SC_QD_SHOT_READY causing crash.

image

**Comment by aleos89** [comment]
How did you trigger the crash? After Chain Action triggered I used Quick Draw Shot and it casted just fine. I use it against a living target and attempted a couple times on a dying target.

**Comment by ecdarreola** [comment]
> How did you trigger the crash? After Chain Action triggered I used Quick Draw Shot and it casted just fine. I use it against a living target and attempted a couple times on a dying target.

Haven't noticed. I was not the one who actually cause the crash. I just monitored the console and found this out.

**Comment by wdivet** [comment]
> How did you trigger the crash? After Chain Action triggered I used Quick Draw Shot and it casted just fine. I use it against a living target and attempted a couple times on a dying target.

I don't know this was related or not, but i experienced same problem with my current version (https://github.com/rathena/rathena/commit/2b49d12d7384a12ec0c8b1f9ce1c7db713741fc6) manual update to this commit. And yes, If i use skill Weapon Crush or QDshot, map crash.

**Comment by ecdarreola** [comment]
QSD caster receiving own damage from the latest commit.
Adding NoTargetSelf DamageFlag will make the skill not working.

**Comment by ecdarreola** [comment]
Latest commit makes the skill RL_QD_SHOT not usable. When casting skill nothing happens even the condition is met with SC_ and after chain action.

**Comment by LordWhiplash** [comment]
Applied and is working fine, but i've notice that i can use RL_QD_SHOT 3 times in one unique double hit from GS_CHAINACTION  if i start spamming RL_QD_SHOT even before the double hit proc...
I'll try to record a video of it... kinda hard to explain...
I don't know if it is suposed to happen (never player Rebellion on official servers)

**Comment by ecdarreola** [comment]
Works fine now.

**Pull request merged**
