### PR TITLE
Add support for the new basic skill & Clean-ups

### PR DESCRIPTION
**Pull request by secretdataz**

### CODE REVIEW

**Comment by aleos89** [comment]
Looking through the `npc` folder shows quite a few checks for `NV_BASIC`. Would be nice to hit them all in one shot.

But before we do any of this, I'd like to confirm Doram's interaction with Kafra or the other NPC to see if they should have access through these methods or not.

**Comment by secretdataz** [comment]
Doram's new basic skill description explicitly said that it gives access to Kafra storage.
This is in skillinfoz/skilldescript.lub from latest kRO rdata.grf.
```
[SKID.SU_BASIC_SKILL] = {
		"새로운 기본 기능 (New Basic Skill)",
		"MAX Lv : 1",
		"계열 : ^000099패시브^000000",
		"내용 : ^777777기본 인터페이스에 관한 기술을 사용할 수 있게 된다.^000000",
		"^777777캐릭터 간의 거래, 이모션의 감정 표현, 앉기, 채팅방 개설, 파티참가 및 파티 개설, 카프라 창고이용 가능.^000000"
```

**Comment by RagnarokNova** [comment]
Can most definitely confirm Dorams can access regular Kafras with Doram Basic Skill 1

**Comment by Kolkka** [comment]
Official description says Doram can access Kafra Storage with New Basic Skill level 1, I think this should be merged.

**Comment by cydh** [comment]
it's only me or that redundant checks are annoying. xD
I meant, why don't we try make a function like
```
function	script	F_CanOpenKafra	{
	return (basicskillcheck() && (getskilllv("NV_BASIC") < 6 && getskilllv("SU_BASIC_SKILL") < 1));
}
```

**Comment by cydh** [comment]
then, what is this PR waiting for?

**Pull request merged**
