### PR TITLE
Fixes Ensemble skills behavior

### LINKED ISSUE #4987: Minstrel/Gypsy debuff EFST_ENSEMBLEFATIGUE not working properly
* **rAthena Hash**: d9f5331

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: EFST_ENSEMBLEFATIGUE not aplying correct effects.
  * Result: can't walk, can cast skills and no aspd penalty
bandicam-2020-05-20-04-55-48-716
  * Expected Result: 30% movespeed penalty, 30% ASPD penalty, and can't cast skills
  * How to Reproduce: Use any ensemble skill
  * Official Information: 

1. kRO sites (the text says 30 second duration, which is different from ingame values)
http://ro.gnjoy.com/news/devnote/View.asp?category=1&seq=3903893&curpage=1 
http://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=7033&curpage=21
2. Sigma from Divine Pride describing the debuff
 image
3. Looking at actual stateiconinfo.lub of kRO found this description
StateIconList[EFST_IDs.EFST_ENSEMBLEFATIGUE] = {haveTimeLimit = 1, posTimeLimitStr = 2, 
descript = {
{"합주 피로 상태", COLOR_TITLE_DEBUFF}, 
{"%s", COLOR_TIME}, 
{"합주로 인한 피로 상태."}, 
{"스킬 사용 불가."}, 
{"이동, 공격속도 30% 감소."}}}

   (TRANSLATION)
StateIconList[EFST_IDs.EFST_ENSEMBLEFATIGUE] = {haveTimeLimit = 1, posTimeLimitStr = 2, 
descript = {
{"Joint fatigue state", COLOR_TITLE_DEBUFF}, 
{"%s", COLOR_TIME}, 
{"Fatigue due to ensemble."}, 
{"Skill unavailable."}, 
{"Move, attack speed reduced by 30%."}}}

  

* **Modifications that may affect results**: None.

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #4987

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Ensemble skills apply SC_ENSEMBLEFATIGUE which should disable skill casting and reduces movement speed/ASPD by 30%.
  * Applies SC_ENSEMBLEFATIGUE to both the caster and partner.
Thanks to @LordWhiplash!

### CODE REVIEW

**Comment by LordWhiplash** [comment]
Could you please confirm if the duration is 10 or 30 seconds? kRO site when the changes came said 30 seconds, while Sigma from Divine Pride said 10 seconds once, and this korean database says 10 seconds too on skill descriptions http://kafra.kr/#!/en/KRO/skillinfo/311
Thank you very much!

**Comment by Balferian** [comment]
@aleos89 in skill description was said that it have 10 sec duration, but in status icon 30 sec duration.
Maybe they forgot to change skill description.
(kRo Sakray)
image

**Comment by aleos89** [comment]
The description says 30 seconds for Loki’s Wail and near the bottom it says 10 seconds for Ensemble fatigue. Am I missing something?

**Comment by Balferian** [comment]
Yeah, all durations are correct.
I looked at the wrong time in skill description.

**Pull request merged**
