### PR TITLE
Added guild/party checks for character deletion process #1480

### PR DESCRIPTION
**Pull request by cyilcode**

### CODE REVIEW

**Comment by cydh** [comment]
Ok, looks good. This is that I wanted.

**Comment by Lemongrass3110** [comment]
I think this should have a configuration to enable/disable this check.

Additionally shouldn't it be added to `chclif_parse_delchar` too?

**Comment by Lemongrass3110** [comment]
Could you please enable edit from maintainers?
https://rathena.org/board/topic/107284-improving-collaboration-with-forks/
Thank you.

**Comment by cydh** [comment]
what's the point to enable it, in the end u squash it LOL
just merge (don't push it yet) it locally, edit as u like, then push it ckckck

**Comment by Lemongrass3110** [comment]
The difference is that others can review my changes before i push it to master too. And yes I will squash it because I dont need credits for 2 lines of changes to feel better ;)

**Pull request closed without merging**
