### PR TITLE
Initial release of Soul Reaper

### PR DESCRIPTION
**Pull request by nubspixel**
* **Addressed Issue(s)**: Implements 3CeAM version of Soul Reaper

* **Server Mode**: Both (?)

* **Description of Pull Request**: 
Inspired by the pull request for Star Emperor (/pull/3893), I decided to do the same for Soul Reaper to expedite the process of having both classes in to the main branch. But, I am not confident that I did a good job on the 3CeAM -> rAthena conversion.

### CODE REVIEW

**Comment by Badarosk0** [comment]
Map server crash:
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000065b34e in status_change_timer (tid=Unhandled dwarf expression opcode 0xf3
) at status.cpp:13851
13851				if ( !check_distance_bl(bl, unity_src, 11) )
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.2.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-23.el6.x86_64 libgcc-4.4.7-18.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 libstdc++-4.4.7-18.el6.x86_64 mysql-libs-5.1.73-8.el6_8.x86_64 nss-softokn-freebl-3.14.3-23.3.el6_8.x86_64 openssl-1.0.1e-57.el6.x86_64 pcre-7.8-7.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) 
[K(gdb) 
[K(gdb) bt full
#0  0x000000000065b34e in status_change_timer (tid=Unhandled dwarf expression opcode 0xf3
) at status.cpp:13851
        unity_src = 0x0
        type = SC_SOULUNITY
        bl = 0x7e5f2a0
        sd = 0x7e5f2a0
        interval = 0
        dounlock = false
        status = 0x7e5f734
        sce = 0x5f3e188
        sc_timer_next = {<std::_Maybe_unary_or_binary_function<void, unsigned int>> = {<std::unary_function<unsigned int, void>> = {<No data fields>}, <No data fields>}, <std::_Function_base> = {static _M_max_size = 16, 
            static _M_max_align = 8, _M_functor = {_M_unused = {
                _M_object = 0x5b72f20, _M_const_object = 0x5b72f20, 
                _M_function_pointer = 0x5b72f20, _M_member_pointer = (
    void (std::_Undefined_class::*)(
    std::_Undefined_class *)) 0x5b72f20, this adjustment 3345299758}, 
              _M_pod_data = " /\267\005\000\000\000\000.9e\307\000\000\000"}, 
            _M_manager = 0x6388a0 <std::_Function_base::_Base_manager<status_change_timer(int, unsigned int, int, intptr_t)::<lambda(unsigned int)> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation)>}, 
          _M_invoker = 0x6373c0 <std::_Function_handler<void(unsigned int), status_change_timer(int, unsigned int, int, intptr_t)::<lambda(unsigned int)> >::_M_invoke(const std::_Any_data &, unsigned int &)>}
        __FUNCTION__ = "status_change_timer"
#1  0x0000000000690028 in do_timer (tick=Unhandled dwarf expression opcode 0xf3
) at timer.cpp:370
        tid = 4539
        diff = -6
        __FUNCTION__ = "do_timer"
#2  0x0000000000465ebc in main (argc=1, argv=0x7fffffffde28) at core.cpp:367
        next = <value optimized out>
```

**Comment by nubspixel** [comment]
Not sure if this will solve your problem, @Badarosk0 .

**Comment by sianromantic** [comment]
skill([Soul Reap](https://www.divine-pride.net/database/skill/2607)) not work

**Comment by nubspixel** [comment]
ugh.. commit to the wrong repo.

**Comment by nubspixel** [comment]
If possible, please delete this request. :shy:

Reason: commited a bunch of files, to the wrong repo.

**Comment by nehpetskie** [comment]
@nubspixel  ? sir i can compile it all Map.cpp is error

**Comment by nubspixel** [comment]
Dude. I did a mistake in this branch. Why are you compiling it?
read what i wrote above your post.

**Pull request closed without merging**
