### PR TITLE
Added support for skill scale display

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: #4530

* **Server Mode**: Both

* **Description of Pull Request**: Adds a new packet that displays the AoE range of a skill that is being casted.

Thanks to @Balferian
Credits to @Asheraf and @exneval

### CODE REVIEW

**Comment by chishen912** [comment]
The skill scale not

**Comment by chishen912** [comment]
image
The skill scale didn't disappear on player.

**Comment by Lemongrass3110** [comment]
@chishen912 this is not enabled for every skill. Was it casting a skill that should have shown the scale?

**Comment by qwerty7vp** [comment]
@Lemongrass3110 I guess he's using Faceworm Queen Leg [13090] and it has a autobonus to cast NPC_EARTHQUAKE while transformed

**Comment by Lemongrass3110** [comment]
This is because no casting packet is triggered because of autocast -> no cast time.

**Comment by chishen912** [comment]
@Lemongrass3110 That was Faceworm Queen monster use NPC_EARTHQUAKE skill.

**Pull request merged**
