### PR TITLE
Initial Release: Translation/Localization Feature

### PR DESCRIPTION
**Pull request by cydh**
Initial release NPC Translations.
- Further info can be read in [README.md](https://github.com/cydh/rathena/blob/feature/translation/lang/README.md)
- Credits to https://github.com/HerculesWS/Hercules/commit/330e31cc71ece055908acb1eb967b4009ebc9c46, @aleos89

---
## Known issue
- The message inside `select` with `:` as separator, won't be parsed/translated

### CODE REVIEW

**Comment by anacondaqq** [comment]
Best of the best!

**Comment by darknessfmy** [comment]
WOW FINALLY!!!!!!!

**Comment by HellyCts** [comment]
Than you so much!

**Comment by cydh** [comment]
## My sample
In case for someone wondering how I test it (unfortunately written in Bahasa)
https://github.com/pservero/rAthenaID
and because the config also support [motd.txt](https://github.com/pservero/rAthenaID/blob/master/lang/Indonesian/motd.txt) and [help.txt](https://github.com/pservero/rAthenaID/blob/master/lang/Indonesian/help.txt), those are my files.
also I moved my collaboration work with @nanakiwurtz to [lang/Indonesian/msg_conf.po](msg_conf.po)

**Comment by darknessfmy** [comment]
Thank you @aleos89   for aproved this system!
The International community thanks what you are you doing  now.

**Comment by HellyCts** [comment]
ooooww i love to see this! jajaja i hope have time to work in a client side translation project to spanish too but this is a small step for the man, but a big step for the ragnarok worldwide community! jajaja

**Comment by darknessfmy** [comment]
@reloadmsgconf cause crash in map server (i use last rA and last diff of this system)
image

I check the system and work fine:
image

**Comment by RadianFord** [comment]
This is awesome :+1:

**Comment by darknessfmy** [comment]
any news? :(

**Comment by aleos89** [comment]
Confirmed the crash, will look into it when I get some time.

**Comment by CairoLee** [comment]
this is a powerful feature,but it's not friendly for chinese language, hope we can have a define switch to turn off this feature.

**Comment by aleos89** [comment]
There's no way to disable this because index 0 is English.

**Comment by Daegaladh** [comment]
Waiting for it to be merged <3

**Comment by cydh** [comment]
> this is a powerful feature,but it's not friendly for chinese language

@CairoLee can you tell us why?

**Comment by cydh** [comment]
I'm f*cked since #2089 was merged

**Comment by M45T3Ryu** [comment]
This should be fixed, its a very cool feature

**Pull request closed without merging**
