### PR TITLE
Initial implementation of Converted mob_skill_db to yml

### PR DESCRIPTION
**Pull request by AoShinRO**
* **Addressed Issue(s)**: 

* **Server Mode**: Both

* **Description of Pull Request**: Initial implementation of Converted mob_skill_db to yml + Conversor

### CODE REVIEW

**Comment by AoShinRO** [comment]
I hadn't seen that @Atemo did this in 2021 :c too late now 😄

**Comment by ADMChester** [comment]
After applying these changes, I added some skills to the skill_nocast_db to block their use in certain maps using zones 1 to 9. When trying to use a blocked skill, the map-server crashes without showing any error.
I tested the mapflag in zones 1 to 9, and all of them crashed the map-server.

**Comment by AoShinRO** [comment]
> After applying these changes, I added some skills to the skill_nocast_db to block their use in certain maps using zones 1 to 9. When trying to use a blocked skill, the map-server crashes without showing any error. I tested the mapflag in zones 1 to 9, and all of them crashed the map-server.

atemo have coded it better, just search on pullrequests

**Comment by ADMChester** [comment]
Thx brother

**Pull request closed without merging**
