### PR TITLE
Added missing quest ID in quest_db.txt

### PR DESCRIPTION
**Pull request by hazimjauhari90**
* **Addressed Issue(s)**: 

* **Server Mode**: 

* **Description of Pull Request**:

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
Your pull request contains monster ids we do not have yet.
Have a look at this line and below:
https://travis-ci.org/rathena/rathena/jobs/217721485#L1468

**Comment by hazimjauhari90** [comment]
done updating the invalid monster id for 3125, 3169, 3170...

**Comment by Lemongrass3110** [comment]
Sorry to say this, but now you added a missing item...
https://travis-ci.org/rathena/rathena/jobs/218032505#L1396
This is caused because of the drop from "Step".

**Comment by hazimjauhari90** [comment]
i'm sorry.. i shouldn't be rush.. just typo for item Slug Shot SH, which its iD is 13213.. not 3213..

**Pull request merged**
