### PR TITLE
Changed the way gender restrictions work

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: #5458

* **Server Mode**: Renewal

* **Description of Pull Request**: 
Added a missing gender restriction to item id 5905.

Thanks to @HenryAlvarez12

### CODE REVIEW

**Comment by HenryAlvarez12** [comment]
This does not seem to work for me. I changed the value but still, both classes can equip it. I feel like gender restriction does not work at ALL anymore.

**Review by Atemo — APPROVED** [review]

**Comment by Atemo** [comment]
Did you check with a character non-gm (`all_equipment` permission to `false` in `conf/group.conf`)?

**Comment by HenryAlvarez12** [comment]
grafik
	id: 0 /* group 0 is the default group for every new account */
	name: "Player"
	level: 0
	inherit: ( /*empty list*/ )
	commands: {
		all_equipment: false
		changedress: true
		resurrect: true
		commands: true
		rates: true
		uptime: true
		exp: true
		mobinfo: true
		iteminfo: true
		whodrops: true
		time: true
		hominfo: true
		homstats: true
		showexp: true
		whereis: true
		battlestats: true
		refresh: true
		noask: true
		autoloot: true
		alootid: true
		autoloottype: true
		autotrade: true
		go: true
		breakguild: true
	}
	permissions: {
		/* without this basic permissions regular players could not 
		trade or party */
		can_trade: true
		can_party: true
		attendance: true
	}

grafik

**Comment by Lemongrass3110** [comment]
Did you unequip it and try to equip it again?

**Comment by HenryAlvarez12** [comment]
> 
> 
> Did you unequip it and try to equip it again?

of course, even restarted the server.
I did not change the value within SQL, is it necessary?

**Comment by saya9200** [comment]
Can confirm. Even after changing the value inside item.db, both genders can still equip it. all_equipment: false also added

**Comment by saya9200** [comment]
Im getting this error though, 
grafik
maybe thats why?

all_equipment: false 
added the same way as alvarez did

**Comment by HenryAlvarez12** [comment]
> 
> 
> Im getting this error though,
> grafik
> maybe thats why?
> 
> all_equipment: false
> added the same way as alvarez did

okay nvm Im getting this error aswell. how to add it properly?

**Comment by aleos89** [comment]
That is a permission, not a command. You put it in the wrong location of the config.

**Review by aleos89 — APPROVED** [review]

**Comment by Lemongrass3110** [comment]
Working perfectly fine for me.

grafik

**Comment by saya9200** [comment]
It does not work for me and I cant explain why..

	id: 0 /* group 0 is the default group for every new account */
	name: "Player"
	level: 0
	inherit: ( /*empty list*/ )
	commands: {
		changedress: true
		resurrect: true
		commands: true
		rates: true
		uptime: true
		exp: true
		mobinfo: true
		iteminfo: true
		whodrops: true
		time: true
		hominfo: true
		homstats: true
		showexp: true
		whereis: true
		battlestats: true
		refresh: true
		noask: true
		autoloot: true
		alootid: true
		autoloottype: true
		autotrade: true
		go: true
		breakguild: true
	}
	permissions: {
		/* without this basic permissions regular players could not 
		trade or party */
		**all_equipment: false**
		can_trade: true
		can_party: true
		attendance: true
	}
},
{

`5905,Lyrica_Hat,Lyrica Hat,4,0,,200,,10,,1,0x00080000,56,1,256,,100,1,1126,{ .@r = getrefine(); bonus2 bSkillAtk,"WM_SEVERE_RAINSTORM",15; if(.@r>=7) { bonus bFixedCastrate,4*(getskilllv("WM_LESSON")); } if(.@r>=9) { bonus2 bSkillUseSP,"WM_SEVERE_RAINSTORM",10; } },{},{}
`

grafik

**Comment by HenryAlvarez12** [comment]
Same.. im starting to get desperate lol

**Comment by RO-GM06** [comment]
I can confirm that this is not working. Both genders are able to equip the hat. 

grafik

**Comment by HenryAlvarez12** [comment]
just test with other hats. wanderer is also able to equip 18976 Old Minstrel Song Hat

**Comment by saya9200** [comment]
Nothing is working. Tried everything. 

Maybe it helps letting you know what SRC edits I have.

Lapine UI
Refine UI

**Comment by HenryAlvarez12** [comment]
For fuck sake.. why is this YES by default? Just why? I was about to freak out and start from scratch again.

Guys this fixes it.
battle/items.conf

// Can any player equip any item regardless of the gender restrictions
// NOTE: Wedding Rings and Whips/Musical Instruments will check gender regardless of setting.
ignore_items_gender: yes

**Comment by RO-GM06** [comment]
> 
> 
> For fuck sake.. why is this YES by default? Just why? I was about to freak out and start from scratch again.
> 
> Guys this fixes it.
> battle/items.conf
> 
> // Can any player equip any item regardless of the gender restrictions
> // NOTE: Wedding Rings and Whips/Musical Instruments will check gender regardless of setting.
> ignore_items_gender: yes

Thank you @HenryAlvarez12. 

That's really silly though, why was it set to yes.. by default?

**Comment by Lemongrass3110** [comment]
Sorry it failed to equip it for me, because my Ministrel was Baselevel > 100 and my Wanderer was only Baselevel 1...

Was able to reproduce it now.

**Review by aleos89 — APPROVED** [review]

**Review by Atemo — APPROVED** [review]

**Review by Daegaladh — APPROVED** [review]

**Review by aleos89 — APPROVED** [review]

**Review by aleos89 — APPROVED** [review]

**Review by Atemo — APPROVED** [review]

**Pull request merged**
