### PR TITLE
Cleaned and merged the chat functions

### PR DESCRIPTION
**Pull request by Lemongrass3110**
This adresses the issue that clients from late 2015 will not zero terminate most of their messages anymore.
It should also fix the problem with the unknown packets that were most likely caused by adding the zero termination directly into the packet buffer.

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
@admkakaroto @Darkelfen @Badarosk0 this could be interessting for you to test, because of #1049.

**Comment by admkakaroto** [comment]
I will put in the emulator and see if there is a difference, if it improves, or something.

**Comment by spinzaku** [comment]
is this related to people disconnecting via random chat ?

**Comment by Lemongrass3110** [comment]
It most likely is. Since I was not able to reproduce these issues myself I can not promise, but it is most likely related to the wrong handling of the zero termination.

**Comment by spinzaku** [comment]
my players have reported if they chat too much, they get sudden "disconnected from server" ><

**Comment by Badarosk0** [comment]
Yes . This is happening in client 2015+

**Comment by spinzaku** [comment]
Any estimate on this? my players disconnect so fast.. just talking in party chat. haha

**Comment by Lemongrass3110** [comment]
Test it and give us feedback then it will be merged into master faster.

**Comment by admkakaroto** [comment]
I'm with personal problems, so I'm away from ragnarok for some time ... I can only re-test and help within two weeks.

**Pull request merged**
