### PR TITLE
Speed up item and mob information commands

### LINKED ISSUE #7081: Using @whodrops will cause the entire server lag
rAthena Hash: [Current](https://github.com/rathena/rathena/commit/15a5bcb2cf6ef30d9322d04ee7c30d96c5eca7a3)
Client Date: 2021-11-03
Server Mode: Re
Description of Issue:
Using @whodrops will cause the entire server lag
It may be due to the time of reading, but this is not the case in previous versions!
e.g. @whodrops 111

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #7081

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Small refactor of the atcommands: iteminfo, mobinfo, whodrops, and idsearch.
  * Item information gathering is now sped up.
  * Refactored itemdb_searchname_array to store results in a std::map so that the data is sorted by ID automatically.
  * Cleanups across the board to remove extra calls for itemdb_exists().
Thanks to @voyfmyuh!

### CODE REVIEW

**Comment by voyfmyuh** [comment]
Typing @whodrops aaa crashes the map server
螢幕擷取畫面 2022-07-09 183022

**Comment by StarGmes** [comment]
verified, when using @whodrops the map crashes

**Comment by StarGmes** [comment]
now if it is working correctly without problems

**Comment by gravity-ro** [comment]
I compile from this
https://github.com/rathena/rathena/commit/8038e713221166b45fdd7dac495d77d5e0f1a870

Found a little error 

Screenshot_1

**Comment by idk-whoami** [comment]
I can't find bg_team_getitem

**Comment by gravity-ro** [comment]
> I can't find bg_team_getitem

Error this line
if (amount < 1 || bgd == NULL || (id = **itemdb_exists**(nameid)) == NULL)

itemdb_exists

or i can delete 

`void bg_team_getitem(int bg_id, int nameid, int amount)
{
	std::shared_ptr<s_battleground_data> bg;
	struct map_session_data *sd;
	struct item_data *id;
	struct item it;
	int get_amount, j, flag;

	std::shared_ptr<s_battleground_data> bgd = util::umap_find(bg_team_db, bg_id);
	if (amount < 1 || bgd == NULL || (id = itemdb_exists(nameid)) == NULL)
		return;
	if( battle_config.bg_reward_rates != 100 )
		amount = amount * battle_config.bg_reward_rates / 100;

	memset(&it, 0, sizeof(it));
	it.nameid = nameid;
	it.identify = 1;

	for (j = 0; j < MAX_BG_MEMBERS; j++)
	{
		if ((sd = bg->members[j].sd) == NULL)
			continue;

		get_amount = amount;

		if ((flag = pc_additem(sd, &it, get_amount, LOG_TYPE_SCRIPT)))
			clif_additem(sd, 0, 0, flag);
	}
}`

and the

`	std::shared_ptr<s_battleground_data> bgd = util::umap_find(bg_team_db, bg_id);
	if (amount < 1 || bgd == NULL || (id = itemdb_exists(nameid)) == NULL)
		return;`

**Comment by Pokye** [comment]
> I compile from this [8038e71](https://github.com/rathena/rathena/commit/8038e713221166b45fdd7dac495d77d5e0f1a870)
> 
> Found a little error
> 
> Screenshot_1
> 
> Screenshot_2

This is custom BG Mod. rA does not give support third party mods.

**Comment by gravity-ro** [comment]
> > I compile from this [8038e71](https://github.com/rathena/rathena/commit/8038e713221166b45fdd7dac495d77d5e0f1a870)
> > Found a little error
> > Screenshot_1
> > Screenshot_2
> 
> This is custom BG Mod. rA does not give support third party mods.

Thank you ^^ maybe i forgot delete battleground mod this is old mod
I'll try to fine mod and delete.

**Comment by aleos89** [comment]
The `itemdb_exists` function has been removed as it was just a wrapper for `item_db.find()`.

**Comment by gravity-ro** [comment]
> aleos89

Thank you [aleos89](https://github.com/aleos89) ^^

**Pull request merged**
