### PR TITLE
reset npc update [SC per Class]

### PR DESCRIPTION
**Pull request by sader1992**
* **Addressed Issue(s)**: 

* **Server Mode**: 

* **Description of Pull Request**: 
Adding SC per Class to prevent remove other item buffs during skill reset
and to be as intended

### CODE REVIEW

**Comment by sader1992** [comment]
searching for 

-Champion
//soul collect?
-Merchant
//crazy uproar?
-Ninja
//Cisada Skin Shed?
//ninja aura?
//mirror image?
-Kagerou / Oboro
//fire charm?
//ice charm?
//wind charm?
//earth charm?
//the 16th night?
-Gunslinger
//incress accuracy?
-Taekwon
//tornado kick ?
//heel drop stance?
//roundhouse stance?
//counter kick stance?
//tumbling?
//mild wind?
-Star Gladiator
//solar heat/protaction ?
//lunar heat/protaction ?
//stellar heat/protaction ?
//union?

**Comment by aleos89** [comment]
Before you go too far adding more, there is an easier way to do this with a couple lines of changes in source.

**Comment by sader1992** [comment]
yes but i am not so good in c/c++ so i may mess up there :X

**Comment by Lemongrass3110** [comment]
Aleos will do it for you :-)

**Comment by aleos89** [comment]
Check out #2368 and let me know what you think.

**Pull request closed without merging**
