### PR TITLE
Initial release of morse cave instance

### PR DESCRIPTION
**Pull request by Atemo**
* **Addressed Issue(s)**: NA

* **Server Mode**: renewal

* **Description of Pull Request**: 
Walkthrough of morse cave instance
Thanks to https://www.divine-pride.net/ !

### CODE REVIEW

**Comment by laziem** [comment]
Hi, after defeat Weakened Morroc nothing happen

`[Warning]: Incorrect use of 'close' command! (source:Red Flower#a1 / path:npc/re/instances/MorseCave.txt)`
`[Error]: get_val_: fatal error ! player not attached!`
`[Debug]: Function: getpartymember (3 parameters):`
`[Debug]: Data: number value=18`
`[Debug]: Data: variable name='PARTY_TYPE_CHAR' index=0`
`[Debug]: Data: variable name='.@char_id' index=0`
`[Debug]: Source (NPC): Weakened Morroc#RZ1 at 0011@rev (111,178)`
`[Warning]: script:get_val: cannot access player variable 'PARTY_TYPE_CHAR', defaulting to 0`
`[Error]: buildin_getpartymember: The array .@char_id is not string type.`
`[Debug]: Source (NPC): Weakened Morroc#RZ1 at 0011@rev (111,178)`

**Comment by ecdarreola** [comment]
Got it too after testing the script. See image below.

image

**Comment by Atemo** [comment]
I forgot to remove my customs constants sorry!

**Comment by ecdarreola** [comment]
I'm getting an error but the script still continue.

image

**Comment by ecdarreola** [comment]
Works fine now! Thanks!

Only a noticeable wrong usage of close command for the Red Flower.

**Comment by ecdarreola** [comment]
Works great now <3 thanks!

**Comment by Questune09** [comment]
Correct me if im wrong i just notice the npc's on first map before the last boss appeared is too long to wait before they talk at the middle

I also notice after defeating the fist boss and enter the portal to proceed to next map after talking to npc and go up ahead the portal at the left side is already there and you can enter it with out any broadcasting if the portal is open?  Someone notice this too?

Hopefully this will help

**Comment by Atemo** [comment]
>the npc's on **first** map before the **last** boss appeared is too long to wait before they talk at the **middle**

Maybe you're referring to https://github.com/rathena/rathena/pull/3173/files#diff-d098a6bad9e7029cc5882f49c4819b52R233
It should be 3s

>I also notice after defeating the fist boss and enter the portal to proceed to next map after talking to npc and go up ahead the portal at the left side is already there and you can enter it with out any broadcasting if the portal is open? Someone notice this too?

I don't understand. Give npc name and/or coordinates and/or screenshot ?

**Comment by laziem** [comment]
Sir, I have suggestion:

1. When the party got teleported and divided, and when teleported to regroup again (when they still can't move), to not stack all the player in one cell. Because sometimes, the mobs that spawn walk the other way (out of skill range).

2. When a player got DC, can enter the instances and continue the instances.

Thank you

**Comment by ecdarreola** [comment]
@laziem : Prolly the player who got dced is still in 5 minutes restriction for re entry.

**Comment by Atemo** [comment]
@ecdarreola Player can't re-enter in this instance, the delay is 1 day

**Comment by Atemo** [comment]
>When a player got DC, can enter the instances and continue the instances.

Sorry I want to be as close as possible of official script. But you are free to edit it !

**Pull request merged**
