### PR TITLE
OnTouch Royal messenger NPC

### PR DESCRIPTION
**Pull request by Atemo**
* **Addressed Issue(s)**: #3860

* **Server Mode**: renewal

* **Description of Pull Request**: 
Updated OnTouch condition for Royal messenger NPC.
Thanks to @zackdreaver!

### CODE REVIEW

**Comment by zackdreaver** [comment]
Should be triggered as well on below 99, tested on iRO:
screenchaos000

**Comment by Atemo** [comment]
The message `I am looking for the hero who returned from the expedition...` is displayed if the player

- already starts the quest

or
- is below level 100

or
- doesn't have the prerequisite to start the quest

**Comment by zackdreaver** [comment]
[is below level 100 + doesn't have the prerequisite to start the quest] based on screenshot
I'll test it with novice.

**Comment by zackdreaver** [comment]
screenchaos001

**Comment by Atemo** [comment]
The message displayed by our script should be fine. I don't understand what you want to tell me.

**Comment by zackdreaver** [comment]
Not working on my novice with this PR file, replay:
[mess.zip](https://github.com/rathena/rathena/files/2775721/mess.zip)

**Comment by Daegaladh** [comment]
You need to be at least level 100, so `BaseLevel > 99` is ok.
I think @zackdreaver is confusing the lines or something, I don't understand what he means either.

**Comment by zackdreaver** [comment]
Ah I see what's wrong, the only one that works is the original one at prontera,121,72,3

The duplicates aren't working.

**Comment by Daegaladh** [comment]
> 
> 
> Ah I see what's wrong, the only one that works is the original one at prontera,121,72,3
> 
> The duplicates aren't working.

Oh, that's right, they have no trigger area.

**Comment by zackdreaver** [comment]
So, actually the line ``&& BaseLevel > 99 && (ep13_ryu > 99 || ep13_start > 99)`` isn't needed, because it's already correct.
Only the duplicates that need to be fixed.

**Comment by zackdreaver** [comment]
Why delete ``&& BaseLevel > 99 && (ep13_ryu > 99 || ep13_start > 99))``?
That's already correct.
(I was wrong before, so I delete my comment.)

**Comment by Atemo** [comment]
Sigh, it got lost in the process.

**Pull request merged**
