### PR TITLE
Added 'Gradable' in item DB

### PR DESCRIPTION
**Pull request by Atemo**
* **Addressed Issue(s)**: N/A

* **Server Mode**: renewal

* **Description of Pull Request**: 

The field defines if the item can be graded (renewal). (Default: false)
Thanks to @attackjom to bring this up.

The following items don't have grade bonus in the script field nor enchants (from enchant UI) with grade bonus.

List of items currently defined as non-gradable :
-----------------------------------------------------------------------

ArmorLevel: 2 - Gradable = false
-----------------------------------------------------------------------

400178: 'Viva_Adul_Hat_WL1'
400179: 'Viva_Adul_Hat_WL2'
400180: 'Viva_Adul_Hat_SR1'
400181: 'Viva_Adul_Hat_SR2'
400189: 'Viva_Adul_Hat_AB1'
400190: 'Viva_Adul_Hat_AB2'
400191: 'Viva_Adul_Hat_SC1'
400192: 'Viva_Adul_Hat_SC2'
400198: 'Viva_Adul_Hat_RA1'
400199: 'Viva_Adul_Hat_RA2'
400200: 'Viva_Adul_Hat_LG1'
400201: 'Viva_Adul_Hat_LG2'
400216: 'Viva_Adul_Hat_GC1'
400217: 'Viva_Adul_Hat_GC2'
400218: 'Viva_Adul_Hat_SO1'
400219: 'Viva_Adul_Hat_SO2'
400226: 'Viva_Adul_Hat_RK1'
400227: 'Viva_Adul_Hat_RK2'
400228: 'Viva_Adul_Hat_WM1'
400229: 'Viva_Adul_Hat_WM2'
400230: 'Viva_Adul_Hat_NC1'
400231: 'Viva_Adul_Hat_NC2'
400233: 'Viva_Adul_Hat_GN1'
400234: 'Viva_Adul_Hat_GN2'
400235: 'Viva_Adul_Hat_KO1'
400236: 'Viva_Adul_Hat_KO2'
400237: 'Viva_Adul_Hat_RL1'
400238: 'Viva_Adul_Hat_RL2'
400239: 'Viva_Adul_Hat_SP1'
400240: 'Viva_Adul_Hat_SP2'
400241: 'Viva_Adul_Hat_SJ1'
400242: 'Viva_Adul_Hat_SJ2'
400243: 'Viva_Adul_Hat_SU1'
400244: 'Viva_Adul_Hat_SU2'
420066: 'SurviveOrb_K_LT'
450149: 'MD_Geffen_Suits'
450150: 'MD_Geffen_Robe'
450166: 'Vague_Star_Robe'
450167: 'Vague_Star_Suit'
450168: 'Vague_Star_Armor'
450191: 'ST_Orleans_Gown'
450192: 'ST_Naga_Armor'
450199: 'Barmund_Armor'
450206: 'Snowflower_Armor'
450207: 'Snowflower_Robe'
460005: 'MD_Geffen_Shield'
460006: 'MD_Geffen_Shield2'
460021: 'ST_Orleans_Server'
460022: 'ST_Naga_Shield'
470107: 'Barmund_Greave'
470115: 'Snowflower_Boots'
470116: 'Snowflower_Shoes'
480065: 'MD_Geffen_Hood'
480066: 'MD_Geffen_Hood2'
480067: 'MD_Geffen_Hood3'
480068: 'MD_Geffen_Hood4'
480136: 'Thanatos_Sword'
480138: 'ST_Servival_Cloak'
480144: 'Barmund_Manteau'
480159: 'Snowflower_Manteau'
480160: 'Snowflower_Muffler'
490131: 'Signet_Of_Star'
490132: 'Signet_Of_Pow_Star'
490133: 'Signet_Of_Sta_Star'
490134: 'Signet_Of_Con_Star'
490135: 'Signet_Of_Crt_Star'
490136: 'Signet_Of_Spl_Star'
490137: 'Signet_Of_Wis_Star'
490152: 'aegis_490152'
490153: 'aegis_490153'
490155: 'aegis_490155'
490156: 'aegis_490156'
490160: 'ST_Orleans_Glove'
490161: 'ST_Pinquicula_Corsage'
490162: 'ST_Waterdrop_Brooch'
490164: 'aegis_490164'
490165: 'aegis_490165'
490166: 'aegis_490166'
490167: 'aegis_490167'
490171: 'aegis_490171'
490172: 'aegis_490172'
490176: 'Snowflower_Pendant'
490177: 'Snowflower_Ring'
490178: 'Snowflower_Necklace'
490179: 'Snowflower_Earring'
490180: 'aegis_490180'
490181: 'aegis_490181'
490184: 'aegis_490184'
490185: 'aegis_490185'
490186: 'aegis_490186'
490187: 'aegis_490187'
490188: 'aegis_490188'

WeaponLevel: 2 - Gradable = false
-----------------------------------------------------------------------
500018: 'Fourth_1h_Sword'
500049: 'Glacier_Sword'
500050: 'Glacier_B_Sword'
510021: 'Avd_Knife'
510026: 'Fourth_1h_Dagger'
510053: 'Fourth_1h_Nindo'
510054: 'Fourth_1h_Edge'
510055: 'Fourth_1h_Nindo2'
510061: 'Glacier_R_Knife'
510062: 'Glacier_B_Knife'
520017: 'Glacier_Axe'
530009: 'Fourth_1h_Spear'
530025: 'Glacier_Spear'
540013: 'Fourth_1h_Book'
540043: 'Fourth_1h_Manual'
540049: 'Glacier_Book'
550057: 'Fourth_1h_Rod'
550058: 'Fourth_1h_Plant'
550059: 'Fourth_1h_Wand'
550069: 'Glacier_Wand'
550070: 'Glacier_Foxtail'
560011: 'Fourth_1h_Knuckle'
560032: 'Glacier_Knuckle'
570012: 'Fourth_Bh_Lute'
570029: 'Glacier_Violin'
580012: 'Fourth_1h_Whip'
580030: 'Glacier_Whip'
590015: 'Fourth_1h_Mace'
590038: 'Glacier_Mace'
590039: 'Glacier_M_Mace'
600013: 'Fourth_Bh_Sword'
600027: 'Glacier_T_Sword'
610015: 'Fourth_Bh_Katar'
610037: 'Glacier_Katar'
620005: 'Fourth_Bh_Axe'
620017: 'Glacier_T_Axe'
630018: 'Glacier_Lance'
640013: 'Fourth_Bh_Staff'
640033: 'Glacier_Staff'
650020: 'Fourth_Bh_Fuuma'
650025: 'Glacier_Humma'
700021: 'Fourth_Bh_Bow'
700052: 'Glacier_Bow'
800010: 'Fourth_Revolver'
800014: 'Glacier_Revolver'
810006: 'Fourth_Rifle'
810010: 'Glacier_Rifle'
820005: 'Fourth_Shotgun'
820008: 'Glacier_Shotgun'
830009: 'Fourth_Gatling'
830013: 'Glacier_Gatling'
840005: 'Fourth_Grenade'
840009: 'Glacier_Launcher'

### CODE REVIEW

**Review by Lemongrass3110 — APPROVED** [review]
Looks good to me.
Only three things:
1) @aleos89 should say if it is "Gradable" or "Gradeable"
2) Why invert and name it different in src?
3) Needs a version increase again.

**Comment by Atemo** [comment]
About 2. I followed the same logic as 'Refineable' field which uses 'no_refine' flag in src. Should I invert it?

**Comment by aleos89** [comment]
No 'e', gradable. The rule in English is to drop the 'e' when adding a suffix that begins with a vowel.

**Comment by Lemongrass3110** [comment]
> About 2. I followed the same logic as 'Refineable' field which uses 'no_refine' flag in src. Should I invert it?

Refineable is an old field, but we do not need to stick old logic. If we can have it with the same name and value I think it is better to understand and read it.

> No 'e', gradable. The rule in English is to drop the 'e' when adding a suffix that begins with a vowel.

Perfect then! :)

**Pull request merged**
