### PR TITLE
Fixed newer clients not removing skills

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: #5382

* **Server Mode**: Both

* **Description of Pull Request**: 
Fixes the problem with item granted skills not being cleared.
Adds a new display that shows which skills are item granted.

Thanks to @Balferian for his help with the research.

Thanks to @respect1428 for reporting it.

Credits to @4144 and the respective authors for the packets provided in packets_struct.hpp

### CODE REVIEW

**Comment by Balferian** [comment]
- All skills are highlighted in blue.
- Temporary skill does not allow you to learn personal skills.
- When changing a job, the skill bar is not updated.
- When changing a job and unequip item with a temporary skill, the skill goes to an additional tab and does not disappear from the skill bar.

**Comment by Badarosk0** [comment]
> * All skills are highlighted in blue. (As I see upgade param in TODO list)
> * Temporary skill does not allow you to learn personal skills.
> * When changing a job, the skill bar is not updated.
> * When changing a job and unequip item with a temporary skill, the skill goes to an additional tab and does not disappear from the skill bar.
> * If the skill level is the same as the skill from the item or higher, then the ITEM label should disappear.
> * "refresh" command not update skillbar.
> 
>  skill_learn.mp4 
> Example of equip and uneqip packets:
> 
> HEADER_ZC_ADD_SKILL2 `31 0b 1c 00 10 00 00 00 01 00 0d 00 09 00 01 00 00`
> 
> ```
> {
>   "Data": {
>     "SkillId": 28,
>     "Type": 16,
>     "Level": 1,
>     "SPCost": 13,
>     "AttackRange": 9,
>     "Upgradable": true,
>     "Level2": 0
>   },
>   "Command": 2865
> }
> ```
> 
> HEADER_ZC_SKILLINFO_UPDATE3 `33 0b 1c 00 10 00 00 00 00 00 0a 00 09 00 01 00 00`
> 
> ```
> {
>   "Skid": 28,
>   "Type": 16,
>   "Level": 0,
>   "Spcost": 10,
>   "Attackrange": 9,
>   "Upgradable": true,
>   "Level2": 0,
>   "Command": 2867
> }
> ```

i can confirm this

**Comment by ryukazuna1** [comment]
Screenshot (299)

Build checker fail on PRE-RE Mode Packetver 20151104 ?

**Comment by hnomkeng** [comment]
I'm testing on Client date 2021-11-16 still have this error.

**Comment by hnomkeng** [comment]
compile error on #fa4666d 
image

**Comment by imaqtdan** [comment]
still have this error, when will we get the latest update of this pull?

**Comment by eppc0330** [comment]
Nice pull. Hope completed someday.

**Comment by Pokye** [comment]
Lemongrass your beautiful <3 please update the PR.

**Comment by OptimusM** [comment]
i'm kinda have a hard time whit this one.
_please daddy update this pr **wink wink**_

**Comment by Lemongrass3110** [comment]
> Lemongrass your beautiful <3 please update the PR.

@Pokye done



> i'm kinda have a hard time whit this one. _please daddy update this pr **wink wink**_

@OptimusM done

**Comment by imaqtdan** [comment]
is it failed?

**Comment by Pokye** [comment]
The skills have disappeared.
image

**Comment by imaqtdan** [comment]
@Pokye i tried it now on the latest git

https://github.com/rathena/rathena/assets/69942447/f0aba0a0-afe2-46be-8414-ca441ff3c0f2

**Comment by eppc0330** [comment]
> @Pokye i tried it now on the latest git
> 
>  2023-06-03.13-10-08.mp4

Confirned. Not fixed yet.

**Pull request closed without merging**
