### PR TITLE
Merged Faceworm Instance from idathena https://github.com/idathena/tr…

### PR DESCRIPTION
**Pull request by Atemo**
From idathena https://github.com/idathena/trunk/commit/20f71d8c62f2fab2f63a47d177a240dabfaa7468

- [x] Updated item db
- [x] Updated mob db / mob skill db
- [x] Implemented NPC_VENOMFOG skill
- [x] Check NPC_VENOMFOG area and if 2 spells can be stacked

### CODE REVIEW

**Comment by Jeybla** [comment]
item_combo_db:
```

// Gigantic Snake Skin Face Worm Nest
20717:22000,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20717:22001,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20717:22002,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20717:22003,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20717:22004,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20717:22005,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20717:22006,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20717:22007,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20717:22008,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20717:22009,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20717:22010,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20717:22011,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20718:22000,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20718:22001,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20718:22002,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20718:22003,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20718:22004,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20718:22005,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20718:22006,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20718:22007,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20718:22008,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20718:22009,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20718:22010,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
20718:22011,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; }
```

itemdb Faceworm Leg:
```
13089,FaceWorm_Leg,Faceworm Leg,5,20,,500,110:50,,1,1,0x028F5EEF,63,2,2,3,24,1,1,{ bonus bAtkEle,Ele_Poison; autobonus "{}",30,5000,BF_WEAPON,"{ specialeffect2 EF_POTION_BERSERK; active_transform 2528,5000; }"; },{},{}
13090,FaceWormQueen_Leg,Faceworm Queen Leg,5,20,,500,180:120,,1,2,0x028F5EEF,63,2,2,4,100,1,1,{ bonus bInt,3; autobonus "{ bonus3 bAutoSpell,\"NPC_EARTHQUAKE\",1,100; }",8,5000,BF_WEAPON,"{ specialeffect2 EF_POTION_BERSERK; active_transform 2529,5000; }"; },{},{}
```
Note: These itemscripts are not confirmed. We didn't found a official, reliable source.

mob_db should equal idathena with corrected mob modes:
```
// Faceworm's Nest 2528,FACEWORM,Faceworm,Faceworm,140,482427,1,38800,3960,2,1818,727,50,30,100,50,100,100,100,50,10,12,2,4,25,0x2000085,200,384,720,480,0,0,0,0,0,0,0,971,100,22507,100,0,0,0,0,0,0,0,0,13089,10,7326,1000,972,100,0,0 2529,FACEWORM_QUEEN,Faceworm Queen,Faceworm Queen,155,50000000,1,200000,200000,2,4024,1609,100,60,200,100,200,200,200,100,10,12,2,4,85,0x6283695,200,768,540,480,90909,0,0,617,2500,12246,2500,607,1000,0,0,0,0,0,0,0,0,13090,100,0,0,6649,5000,0,0,0,0 2530,FACEWORM_DARK,Faceworm Dark,Dark Faceworm,144,5000000,1,100000,80000,2,2012,805,100,30,150,100,150,150,150,100,10,12,2,4,45,0x6203695,180,576,480,480,0,0,0,0,0,0,0,13089,10,22507,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 2531,VENOM_BUG,Venom Bug,Venom Bug,140,10000,1,0,0,1,340,0,200,100,200,200,200,200,200,200,12,12,0,4,25,0x2200084,2000,384,0,480,0,0,0,0,0,0,0,938,5000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7326,1000,0,0 2532,FACEWORM_QUEEN_R,Faceworm Queen (Red),Red Faceworm Queen,155,50000000,1,200000,200000,2,12000,4800,400,400,500,100,200,200,200,100,10,12,2,4,23,0x6283695,200,768,540,480,90909,12246,2500,617,2500,0,0,994,5000,0,0,0,0,0,0,0,0,13090,100,0,0,6649,5000,0,0,0,0 2533,FACEWORM_QUEEN_G,Faceworm Queen (Green),Green Faceworm Queen,155,50000000,1,200000,200000,2,5000,2000,500,60,200,100,400,200,200,100,10,12,2,4,22,0x6283695,200,768,540,480,90909,617,2500,12246,2500,0,0,6649,5000,13090,100,997,5000,0,0,0,0,0,0,0,0,0,0,0,0,0,0 2534,FACEWORM_QUEEN_B,Faceworm Queen (Blue),Blue Faceworm Queen,155,50000000,1,200000,200000,2,5000,2000,100,400,200,100,200,400,200,100,10,12,2,4,21,0x6283695,200,768,540,480,90909,617,2500,12246,2500,0,0,6649,5000,13090,100,995,5000,0,0,0,0,0,0,0,0,0,0,0,0,0,0 2535,FACEWORM_QUEEN_Y,Faceworm Queen (Yellow),Yellow Faceworm Queen,155,50000000,1,200000,200000,2,5000,2000,100,60,200,400,200,200,200,100,10,12,2,4,24,0x6283695,200,768,540,480,90909,617,2500,12246,2500,0,0,6649,5000,13090,100,996,5000,0,0,0,0,0,0,0,0,0,0,0,0,0,0 2536,HIDDEN_MOB3,Hidden Mob 3,Monster 3,151,10000,200,0,0,1,2000,0,200,100,100,100,100,100,100,100,12,12,0,4,88,0x2370084,2000,0,500,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 2537,HIDDEN_MOB4,Hidden Mob 4,Monster 4,151,10000,200,0,0,1,2000,0,200,100,100,100,100,100,100,100,12,12,0,0,88,0x370084,2000,0,500,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 //2538,E_KING_PORING 2539,HIDDEN_MOB5,Hidden Mob 5,Monster 5,151,10000,200,0,0,9,500,0,200,100,100,100,100,100,100,100,12,12,0,0,88,0x2370084,2000,0,500,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 2540,FACEWORM_EGG,Faceworm Egg,Faceworm Egg,140,10,1,10,12,1,150,0,10,10,10,10,10,10,10,10,10,12,1,4,25,0x2370000,150,0,0,0,0,0,0,0,0,0,0,938,5000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7032,5000,0,0 2541,FACEWORM_LARVA,Faceworm Larva,Faceworm Larva,145,260380,1,10,12,1,1286,1851,10,10,10,50,50,50,180,50,10,12,1,4,45,0x2000085,150,1000,792,336,0,0,0,0,0,0,0,912,225,0,0,0,0,0,0,0,0,0,0,1096,1750,943,400,938,1500,0,0 
```

**Comment by Lemongrass3110** [comment]
@Jeybla updated your mob db to have newlines. And item combo is already in master like this. :-)

**Comment by Lemongrass3110** [comment]
Anything still missing with this now? Your latest commit seemed to contain everything regarding NPC_VENOMFOG.

**Comment by Atemo** [comment]
I want to confirm the spell area 5x5 and to check if 2 NPC_VENOMFOG on the same cell deal damage x1 or x2

**Pull request merged**
