### PR TITLE
doram Power of life Crit issue

### PR DESCRIPTION
**Pull request by MysticFurur0RE**
#1138
Issue is that Crit is being raised by 2, not 20 https://github.com/rathena/rathena/issues/1138#issue-146061631

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
Could you please check the email adress you used for this commit?

unbenannt

**Comment by MysticFurur0RE** [comment]
@Lemongrass3110  animador23@gmail.com

**Comment by Lemongrass3110** [comment]
Hi @MysticFurur0RE I removed your email adress so that not everyone can read it.
The second commit worked correctly. Something seem to have gone wrong with your first though.

**Comment by MysticFurur0RE** [comment]
@Lemongrass3110 My keyboard is not in good condition, I have to change it

**Pull request merged**
