### PR TITLE
Apply MHP limit based on bLv

### PR DESCRIPTION
**Pull request by flamefury**
* **Addressed Issue(s)**: #814
* **Server Mode**: Renewal
* **Description of Pull Request**: 
Changes max HP configuration into 3 values based on the level limits as defined in the kRO news post:
http://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=6322

With defaults matching the values there.

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
You forgot to commit battle.hpp

**Comment by RadianFord** [comment]
Will this affect a server with a max level 500?

**Comment by flamefury** [comment]
@RadianFord yes, but you can just modify the Lv175 limit to whatever you want it to be

**Comment by Atemo** [comment]
Some indentations are still broken in pc and status.cpp (space instead of tab)

**Pull request merged**
