### PR TITLE
chore(map): removed apihook comments

### PR DESCRIPTION
**Pull request by Leemonn**
* **Addressed Issue(s)**:  Apihook comments were left in code.

* **Server Mode**:  Both

* **Description of Pull Request**:  Removed these comments. Also improved code style by removing indentation from blank lines

### CODE REVIEW

**Comment by Leemonn** [comment]
Oh not the blank spaces again, fffffffffffffff#$. I will fix it

**Comment by Lemongrass3110** [comment]
They are intentional for my tool ;-)

**Comment by Leemonn** [comment]
Do we need them on the public repo?

**Comment by Akkarinage** [comment]
Yes.

**Comment by Leemonn** [comment]
I was told those comments were old and probably not used anymore, since I couldn't find any reference to "apihook" anywhere in the docs, code and other projects by rAthena I figured they were not used anymore, or at least didn't belong to the public repo.

Closed the PR and deleted the branch.

**Pull request closed without merging**
