### PR TITLE
 Fixed a mistake in 2008 headgear quest

### LINKED ISSUE #3343: Error in quest 2008_headgeras.txt
* **rAthena Hash**: 
Current

* **Server Mode**: 
Pre-renewal

* **Description of Issue**: 
  * Result: Some case in the Cute Ribbon quest gives the wrong item (itemid 250) (that doesn't exists)
  * Expected Result: give itemid 2250
https://github.com/rathena/rathena/blob/master/npc/quests/newgears/2008_headgears.txt#L714

In the rest of the quest it gives 2250 correctly : 
https://github.com/rathena/rathena/blob/master/npc/quests/newgears/2008_headgears.txt#L360
https://github.com/rathena/rathena/blob/master/npc/quests/newgears/2008_headgears.txt#L478
https://github.com/rathena/rathena/blob/master/npc/quests/newgears/2008_headgears.txt#L596

* **Modifications that may affect results**: 
replace : getitem 250,1;
by :  getitem 2250,1;

### PR DESCRIPTION
**Pull request by BrOgBr**
* **Addressed Issue(s)**: 

* **Server Mode**: Pre Renewal / Renewal

* **Description of Pull Request**:  

Fixed #3343
Thank you @Kutikuti

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
Please address one issue in one pull request. This way we can not merge it until everything has been fixed in your pull request and the issue you linked would have been so easy to merge. x_x

**Comment by BrOgBr** [comment]
Sorry @Lemongrass3110 
So what I need to do to fix it now? :(

**Comment by aleos89** [comment]
For now, if you could revert one of the issues and just create a second PR for it that'd be great. It's best to try and keep the issues separate for issue tracking. Thanks!

**Comment by BrOgBr** [comment]
@aleos89 Ok I'll try do it now. :)

**Comment by BrOgBr** [comment]
@Lemongrass3110 OMG. :(

**Comment by Lemongrass3110** [comment]
Its good now. You pushed the changes back! :-)
Will wait for continuous integration to finish and then we can merge it.

**Comment by Lemongrass3110** [comment]
@BrOgBr in the future:
Please use a branch on your fork. If you use master you will probably run into trouble.
Also by using branches you can submit multiple pull requests at once.
If you need help regarding this feel free to drop me a PM on discord.

**Comment by BrOgBr** [comment]
@Lemongrass3110 You're correct, I was having problems using master.
Now I learned how to use a branch, I did this in this new PR: #3352 

Thank you very much, I thought in talk about it with you, but I didn't find your contact. xD

**Pull request merged**
