### PR TITLE
Added mag_dun03

### PR DESCRIPTION
**Pull request by Atemo**
* **Addressed Issue(s)**: N/A

* **Server Mode**: renewal

* **Description of Pull Request**: 

Added content of Magma Dungeon 3.

TODO
-----------------------------------------------------------------------
- [x] Requires the new skills from https://github.com/rathena/rathena/pull/6753, the skill PR need tester !
- [ ] Correction of the english
- [ ] Implement the random option group associated with armor drops from monsters. For now the groups are based on https://ro.gnjoy.in.th/magma-dungeon-3rd-floor-nogg-road/

### CODE REVIEW

**Comment by Pokye** [comment]
https://github.com/rathena/rathena/pull/6753 skills are missing.
[Error]: mob_parse_row_mobskilldb: Invalid Skill ID (761) for mob 20373 (NIGHTMARE_TERROR_H)
[Error]: mob_parse_row_mobskilldb: Invalid Skill ID (768) for mob 20373 (NIGHTMARE_TERROR_H)
[Error]: mob_parse_row_mobskilldb: Invalid Skill ID (757) for mob 20419 (MUSPELLSKOLL_H)

**Comment by Atemo** [comment]
> #6753 skills are missing. [Error]: mob_parse_row_mobskilldb: Invalid Skill ID (761) for mob 20373 (NIGHTMARE_TERROR_H) [Error]: mob_parse_row_mobskilldb: Invalid Skill ID (768) for mob 20373 (NIGHTMARE_TERROR_H) [Error]: mob_parse_row_mobskilldb: Invalid Skill ID (757) for mob 20419 (MUSPELLSKOLL_H)

Yep
Capture d’écran (1114)

**Comment by Pokye** [comment]
> > #6753 skills are missing. [Error]: mob_parse_row_mobskilldb: Invalid Skill ID (761) for mob 20373 (NIGHTMARE_TERROR_H) [Error]: mob_parse_row_mobskilldb: Invalid Skill ID (768) for mob 20373 (NIGHTMARE_TERROR_H) [Error]: mob_parse_row_mobskilldb: Invalid Skill ID (757) for mob 20419 (MUSPELLSKOLL_H)
> 
> Yep Capture d’écran (1114)

I know, I read... I implemented the PR "New boss skills" to test everything. however as I mentioned in PR "New boss skills" does not have these skills.

**Comment by Atemo** [comment]
Ha ok! I misunderstood, my bad !

**Comment by Pokye** [comment]
```
[Warning]: mob_parse_row_mobskilldb: Unrecognized target place for 20374
[Warning]: mob_parse_row_mobskilldb: Unrecognized target place for 20374
[Warning]: mob_parse_row_mobskilldb: Unrecognized target place for 20375
[Warning]: mob_parse_row_mobskilldb: Unrecognized target place for 20419

**Pull request merged**
