### PR TITLE
Resolved some compile issues

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: #3205

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Follow up to 801d3ed.
  * Resolved some string literals requiring a space.
  * Updated MySQL my_bool variable type to bool as it is deprecated in version 8.0.1.
Thanks to @bentheexo!

### CODE REVIEW

**Comment by bentheexo** [comment]
Any idea when these changes will be merged into a stable, or how can I implement these changes with git. Under the old method of Subversion I was more confident about my ability to manage revision, but this is a different animal to me.

**Comment by aleos89** [comment]
You could just do a checkout of the branch: `git checkout hotfix/issue3205`

Compile it and let us know if the issues still arise for you, then we can merge it to master. None of us has MySQL 8 installed.

**Comment by bentheexo** [comment]
Using tradition configure/make and cmake3/make produce the same errors. cmake on RHEL is not updated to version 3.x.x and instead was released as a separate package

[ 40%] Built target common_base
[ 41%] Building CXX object src/common/CMakeFiles/common.dir/sql.cpp.o
/home/v1gro/rathena/src/common/sql.cpp: In function ‘int Sql_P_BindSqlDataType(MYSQL_BIND*, SqlDataType, void*, size_t, long unsigned int*, int8*)’:
/home/v1gro/rathena/src/common/sql.cpp:550:16: error: cannot convert ‘char*’ to ‘bool*’ in assignment
  bind->is_null = (my_bool*)out_is_null;
                ^
/home/v1gro/rathena/src/common/sql.cpp: In function ‘int SqlStmt_NextRow(SqlStmt*)’:
/home/v1gro/rathena/src/common/sql.cpp:892:18: error: cannot convert ‘char*’ to ‘bool*’ in assignment
    column->error = &truncated;
                  ^
make[2]: *** [src/common/CMakeFiles/common.dir/sql.cpp.o] Error 1
make[1]: *** [src/common/CMakeFiles/common.dir/all] Error 2
make: *** [all] Error 2

**Comment by bentheexo** [comment]
I would be happy to provide a development environment for those that would like to try it first hand.

**Comment by bentheexo** [comment]
instead of defining my_bool as char, why not just define it to bool as it appears to be responding to a true/false

**Comment by bentheexo** [comment]
Just warnings it seems now. It builds fine and here is the output. I will have further testing after a quick setup of config files.

[ 54%] Building CXX object src/char/CMakeFiles/char-server.dir/int_guild.cpp.o
/home/v1gro/rathena/src/char/int_guild.cpp:129:11: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
  ShowInfo("Save guild request ("CL_BOLD"%d"CL_RESET" - flag 0x%x).",g->guild_id, flag);
           ^
/home/v1gro/rathena/src/char/int_guild.cpp:129:40: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
  ShowInfo("Save guild request ("CL_BOLD"%d"CL_RESET" - flag 0x%x).",g->guild_id, flag);
                                        ^
[ 56%] Building CXX object src/char/CMakeFiles/char-server.dir/int_party.cpp.o
/home/v1gro/rathena/src/char/int_party.cpp:126:11: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
  ShowInfo("Save party request ("CL_BOLD"%d"CL_RESET" - %s).\n", party_id, p->name);
           ^
/home/v1gro/rathena/src/char/int_party.cpp:126:40: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
  ShowInfo("Save party request ("CL_BOLD"%d"CL_RESET" - %s).\n", party_id, p->name);
                                        ^
/home/v1gro/rathena/src/char/int_party.cpp:200:11: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
  ShowInfo("Load party request ("CL_BOLD"%d"CL_RESET")\n", party_id);
           ^
/home/v1gro/rathena/src/char/int_party.cpp:200:40: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
  ShowInfo("Load party request ("CL_BOLD"%d"CL_RESET")\n", party_id);
                                        ^
[100%] Built target mapcache

**Comment by bentheexo** [comment]
What is your libmysqlclient version

**Comment by laziem** [comment]
libmysql - mysqlnd 5.0.12-dev - 20150407

**Pull request merged**
