### PR TITLE
Effect State Update

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: None

* **Server Mode**: Both

* **Description of Pull Request**: 
Adding the latest EFSTs

### CODE REVIEW

**Comment by saya9200** [comment]
does this contain 
grafik
?

**Comment by aleos89** [comment]
@saya9200 Those effects are probably hard coded/managed by the client itself, not a status change. At least if it were to follow the previous auras we don't have them assigned to a status change.

**Review by aleos89 — APPROVED** [review]

**Comment by saya9200** [comment]
> 
> 
> @saya9200 Those effects are probably hard coded/managed by the client itself, not a status change. At least if it were to follow the previous auras we don't have them assigned to a status change.

I believe those are item effects. 
https://www.divine-pride.net/database/item/20556/costume-aura-of-night
this for example is the level 99 aura in black

**Comment by aleos89** [comment]
Then if that’s the case it will be listed as a HatEffect.

**Comment by saya9200** [comment]
> 
> 
> Then if that’s the case it will be listed as a HatEffect.

my bad, thank you for explaining. I mixed them up.

**Comment by Lemongrass3110** [comment]
@saya9200 the auras you are asking for are probably supported for a long time already:
```
	HAT_EF_99LV_RUNE_RED,
	HAT_EF_99LV_ROYAL_GUARD_BLUE,
	HAT_EF_99LV_WARLOCK_VIOLET,
	HAT_EF_99LV_SORCERER_LBLUE,
	HAT_EF_99LV_RANGER_GREEN,
	HAT_EF_99LV_MINSTREL_PINK,
	HAT_EF_99LV_ARCHBISHOP_WHITE,
	HAT_EF_99LV_GUILL_SILVER,
	HAT_EF_99LV_SHADOWC_BLACK,
	HAT_EF_99LV_MECHANIC_GOLD,
	HAT_EF_99LV_GENETIC_YGREEN,
	HAT_EF_160LV_RUNE_RED,
	HAT_EF_160LV_ROYAL_G_BLUE,
	HAT_EF_160LV_WARLOCK_VIOLET,
	HAT_EF_160LV_SORCERER_LBLUE,
	HAT_EF_160LV_RANGER_GREEN,
	HAT_EF_160LV_MINSTREL_PINK,
	HAT_EF_160LV_ARCHB_WHITE,
	HAT_EF_160LV_GUILL_SILVER,
	HAT_EF_160LV_SHADOWC_BLACK,
	HAT_EF_160LV_MECHANIC_GOLD,
	HAT_EF_160LV_GENETIC_YGREEN,
```
But I did not check it in detail, but from the names it sounds like what you are looking for.

**Comment by attackjom** [comment]
These hateffect are hardcoded in JRO client. so it won't show anything in KRO client.

**Comment by Lemongrass3110** [comment]
> 
> 
> These hateffect are hardcoded in JRO client. so it won't show anything in KRO client.

@attackjom well maybe they will merge it over sooner or later again. Has happened a few times already. But I can only say from server side it would be supported. Client is a different topic - I agree with you!

**Pull request merged**
