### PR TITLE
RED_PILLAR to cards

### PR DESCRIPTION
**Pull request by Atemo**
* **Addressed Issue(s)**: ?

* **Server Mode**: renewal

* **Description of Pull Request**: 

Added RED_PILLAR drop effect to cards with location on renewal.

### CODE REVIEW

**Comment by idk-whoami** [comment]
i think Darklord Essence series IDs 4908 to 4925 contained in boxes
https://www.divine-pride.net/database/item/22567

**Comment by Balferian** [comment]
@Atemo cards should be use Pink_pillar effect.
As i know it can be used only from client side (iteminfo).
Red pillar and Pink pillar are different.
https://github.com/rathena/rathena/issues/5547

**Comment by Daegaladh** [comment]
> 
> 
> @Atemo cards should be use Pink_pillar effect.
> As i know pink pillar can be used only from client side (iteminfo).
> Red pillar and Pink pillar are different.
> #5547

I think Gravity changed all cards to use RED_PILLAR in latest updates

**Comment by aleos89** [comment]
Correct, it is now the red pillar:
image

**Review by Lemongrass3110 — APPROVED** [review]

**Comment by Lemongrass3110** [comment]
Should be:
`Dropeffect: Client`

The actual effect id is defined inside the LUA file. The positive thing about this is, that we can parse the items that have it from there. :-)

**Pull request merged**
