### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cydh**
### **Description of Pull Request**: 

* Correcting the markdown
* Rearrange
  * Removed 'Helpful Links', moved to 'What is rAthena?' and installation section
  * Moved the license statement

imho
even so, this README structure is kinda *not fancy enough*
* [x] Just need to remove that installation guide, just add guide to clone
* [x] Make clear the requirements with minimum specs
* [x] Still about requirement, add minimum memory requirement, disk space, and core maybe
* [x] Remove the troubleshooting, don't like it so much there :expressionless: Maybe FAQ or common-issue-occured-by-starters.md
* [ ] ...

### CODE REVIEW

**Comment by cydh** [comment]
# rAthena
[Build Status](https://travis-ci.org/rathena/rathena) [Build status](https://ci.appveyor.com/project/rAthenaAPI/rathena/branch/master)
> rAthena is a collaborative software development project revolving around the creation of a robust massively multiplayer online role playing game (MMORPG) server package. Written in C, the program is very versatile and provides NPCs, warps and modifications. The project is jointly managed by a group of volunteers located around the world as well as a tremendous community providing QA and support. rAthena is a continuation of the eAthena project.

[Forum](https://rathena.org/board)|[Discord server](https://rathena.org/discord)|[Wiki](https://github.com/rathena/rathena/wiki)|[Fork and Pull Request Q&A](https://rathena.org/board/topic/86913-pull-request-qa/)|[FluxCP](https://github.com/rathena/FluxCP)
--------|--------|--------|--------|--------






# rAthena
[Build Status](https://travis-ci.org/rathena/rathena) [Build status](https://ci.appveyor.com/project/rAthenaAPI/rathena/branch/master)
> rAthena is a collaborative software development project revolving around the creation of a robust massively multiplayer online role playing game (MMORPG) server package. Written in C, the program is very versatile and provides NPCs, warps and modifications. The project is jointly managed by a group of volunteers located around the world as well as a tremendous community providing QA and support. rAthena is a continuation of the eAthena project.

[Forum](https://rathena.org/board)|[Discord server](https://rathena.org/discord)|[Wiki](https://github.com/rathena/rathena/wiki)|[Fork and Pull Request Q&A](https://rathena.org/board/topic/86913-pull-request-qa/)|[FluxCP](https://github.com/rathena/FluxCP)
--------|--------|--------|--------|--------

**Comment by cydh** [comment]
# rAthena
[Build Status](https://travis-ci.org/rathena/rathena) [Build status](https://ci.appveyor.com/project/rAthenaAPI/rathena/branch/master)
> rAthena is a collaborative software development project revolving around the creation of a robust massively multiplayer online role playing game (MMORPG) server package. Written in C, the program is very versatile and provides NPCs, warps and modifications. The project is jointly managed by a group of volunteers located around the world as well as a tremendous community providing QA and support. rAthena is a continuation of the eAthena project.

[Forum](https://rathena.org/board)|[Discord server](https://rathena.org/discord)|[Wiki](https://github.com/rathena/rathena/wiki)|[Fork and Pull Request Q&A](https://rathena.org/board/topic/86913-pull-request-qa/)|[FluxCP](https://github.com/rathena/FluxCP)
--------|--------|--------|--------|--------






# rAthena
[Build Status](https://travis-ci.org/rathena/rathena) [Build status](https://ci.appveyor.com/project/rAthenaAPI/rathena/branch/master)
> rAthena is a collaborative software development project revolving around the creation of a robust massively multiplayer online role playing game (MMORPG) server package. Written in C, the program is very versatile and provides NPCs, warps and modifications. The project is jointly managed by a group of volunteers located around the world as well as a tremendous community providing QA and support. rAthena is a continuation of the eAthena project.

[Forum](https://rathena.org/board)|[Discord server](https://rathena.org/discord)|[Wiki](https://github.com/rathena/rathena/wiki)|[Fork and Pull Request Q&A](https://rathena.org/board/topic/86913-pull-request-qa/)|[FluxCP](https://github.com/rathena/FluxCP)
--------|--------|--------|--------|--------

**Comment by cydh** [comment]
## Requirements
### Hardware
<span></span> | Minimum | Recommendation
------|------|------
**Disk Space** | 300 MB | 500 MB
**RAM** | 768 MB | 1.5 GB
**CPU** | 1 Core | 2 Cores

### Operating System & Preferred Compiler
OS Name | Compiler
------|------
CentOS 5  | gcc-x
CentOS 6  | gcc-x
CentOS 7  | gcc-x
Debian 6  | &nbsp;
FreeBSD | &nbsp;
Ubuntu | &nbsp;
Windows 7 | [MS Visual Studio 2013, 2015, 2017](https://www.visualstudio.com/downloads/) _**Debug & Development Only**_
Windows Server 2008, 2012 | [MS Visual Studio 2013, 2015, 2017](https://www.visualstudio.com/downloads/) _**Debug & Development Only**_

### Application
Application Name | &nbsp; | &nbsp;
------|------|------
**Database** | MySQL 5.\*<br />MySQL 8 <br />[Download](https://www.mysql.com/downloads/)| MariaDB 5.\*<br />MariaDB 10 <br />[Download](https://downloads.mariadb.org/)
**Git** | Git For Windows <br />[Download](https://gitforwindows.org/) | [See instructions](#)
_MySQL Workbench_ | 5.7 <br />[Download](http://www.mysql.com/downloads/workbench/) | &nbsp;


## DISCLAIMER
Good in Markdown, unreadable in raw LOL

**Comment by aleos89** [comment]
## Requirements
### Hardware
Hardware Type | Minimum | Recommended
------|------|------
CPU | 1 Core | 2 Cores
RAM | 1 GB | 2 GB
Disk Space | 300 MB | 500 MB

### Operating System & Preferred Compiler
Operating System | Compiler
------|------
Linux  | [gcc-5 or newer](https://www.gnu.org/software/gcc/gcc-5/)
Windows | [MS Visual Studio 2013, 2015, 2017](https://www.visualstudio.com/downloads/) _**Debug & Development Only**_

### Application
Application | Name
------|------
Database | [MySQL 5 or newer](https://www.mysql.com/downloads/) / [MariaDB 5 or newer](https://downloads.mariadb.org/)
Git | [Windows](https://gitforwindows.org/) / [Linux](https://git-scm.com/download/linux)
### Optional Application
Application | Name
------|------
Database | [MySQL Workbench 5 or newer](http://www.mysql.com/downloads/workbench/)

Some small cleanups/suggestions.

**Comment by cydh** [comment]
looks cleaner

**Comment by cydh** [comment]
Build Status | [Build Status](https://travis-ci.org/rathena/rathena) [Build status](https://ci.appveyor.com/project/rAthenaAPI/rathena/branch/master) [Total alerts](https://lgtm.com/projects/g/rathena/rathena/alerts/) [Language grade: C/C++](https://lgtm.com/projects/g/rathena/rathena/context:cpp)
------- | -------

[Build Status](https://travis-ci.org/rathena/rathena) [Build status](https://ci.appveyor.com/project/rAthenaAPI/rathena/branch/master) [Total alerts](https://lgtm.com/projects/g/rathena/rathena/alerts/) [Language grade: C/C++](https://lgtm.com/projects/g/rathena/rathena/context:cpp)|
------- |


[Forum](https://rathena.org/board)|[Discord](https://rathena.org/discord)|[Wiki](https://github.com/rathena/rathena/wiki)|[FluxCP](https://github.com/rathena/FluxCP)|[Fork and Pull Request Q&A](https://rathena.org/board/topic/86913-pull-request-qa/)|[Crowdfunding](https://rathena.org/board/crowdfunding/)
--------|--------|--------|--------|--------|--------

**Comment by cydh** [comment]
## 6. License
Copyright (c) rAthena Development Team - Licensed under [GNU General Public License v3.0](https://github.com/rathena/rathena/blob/master/LICENSE)

**Pull request merged**
