### PR TITLE
Fixed monster messages not loading

### PR DESCRIPTION
**Pull request by Daegaladh**
* **Addressed Issue(s)**:  #4901 

* **Server Mode**: Both

* **Description of Pull Request**: Fixes monster messages not loading because mob_skill_db parser requires mob_chat_db to be parsed before.

### CODE REVIEW

**Comment by Kreustoo** [comment]
Sorry to be that guy, but did you try that modification with use_sql_db: yes in inter_athena.conf?

I did it :
test
And the modification only works with no sql, if you use sql, I still don't have chat. But yeah, without use the sql db it works.

To be clear :
--compile with your modification--

=> use_sql_db: no
=> launch server => SM is talking

=> close the server
=> use_sql_db: yes
=> launch serve => SM is muted

And as I said in the issue my weird modification:
wtf
It works in both sql and no sql on my side

It makes no sense to me.

**Comment by Daegaladh** [comment]
@Kreustoo try the lastest fix, it should work now for both modes

**Comment by Kreustoo** [comment]
Oh right moving **mob_read_sqlskilldb** to the same level as **mob_readskilldb** and putting the parsing of **chat_db** before it seems to work.

_But it stills make no sense to me why it needs that while in earlier version of rathena it worked ^^._

**Comment by Daegaladh** [comment]
> _But it stills make no sense to me why it needs that while in earlier version of rathena it worked ^^._
Because mob_skill_db now checks if the index on mob_chat_db exists before asigning it to a skill, so the latest needs to be parsed first.

**Pull request merged**
