### PR TITLE
Converts combo databases to yaml

### PR DESCRIPTION
**Pull request by Atemo**
* **Addressed Issue(s)**: -

* **Server Mode**: both

* **Description of Pull Request**: 

This PR is a suggestion of format to convert item_combo_db txt to yaml.

### CODE REVIEW

**Comment by llchrisll** [comment]
Long files again xD, but wouldn't something like this also work? or is that not possible/hard to do?
```
  - Base: Spectral_Spear
	Alternates:
		- Spectral_Spear_
	Combo:
		- Red_Silk_Seal
	Script: |
	  bonus2 bResEff,Eff_Confusion,9500;
```

**Comment by Atemo** [comment]
I made another version in an another branch which is close to your idea
```
Body:
  - Combo:
      - Set:
          - Dragon_Slayer
          - Dragon_Breath
      - Set:
          - Dragon_Slayer_
          - Dragon_Breath
      - Set:
          - Gae_Bolg
          - Dragon_Breath
      - Set:
          - Gae_Bolg_
          - Dragon_Breath
      - Set:
          - Dragon_Breath
          - Dragon_Killer
      - Set:
          - Dragon_Breath
          - Dragon_Killer_
    Script: |
      bonus2 bAddRace,RC_Dragon,5;
```
The final format has not been decided

**Comment by llchrisll** [comment]
> I made another version in an another branch which is close to your idea
> 
> ```
> Body:
>   - Combo:
>       - Set:
>           - Dragon_Slayer
>           - Dragon_Breath
>       - Set:
>           - Dragon_Slayer_
>           - Dragon_Breath
>       - Set:
>           - Gae_Bolg
>           - Dragon_Breath
>       - Set:
>           - Gae_Bolg_
>           - Dragon_Breath
>       - Set:
>           - Dragon_Breath
>           - Dragon_Killer
>       - Set:
>           - Dragon_Breath
>           - Dragon_Killer_
>     Script: |
>       bonus2 bAddRace,RC_Dragon,5;
> ```
> 
> The final format has not been decided, but which one do you prefer?

Looks much cleaner than the current one xD
Maybe some addition regarding values, like if certain combos give a different value for that effect:
```
Body:
  - Combo:
      - Set:
          - Dragon_Slayer
          - Dragon_Breath
		Value1: 5
      - Set:
          - Dragon_Slayer_
          - Dragon_Breath
		Value1: 15
      - Set:
          - Gae_Bolg
          - Dragon_Breath
		Value1: 30
      - Set:
          - Gae_Bolg_
          - Dragon_Breath
      - Set:
          - Dragon_Breath
          - Dragon_Killer
      - Set:
          - Dragon_Breath
          - Dragon_Killer_
    Script: |
      bonus2 bAddRace,RC_Dragon,<Value1>;
```
But that's optional and just a side idea xD.

**Comment by Everade** [comment]
@Atemo 
Will this conversion fix the current issues with the import file overwriting the existing index on load?

**Comment by Atemo** [comment]
Yes this conversion fix this issue. Also the combos are added to item_data after that the files are loaded which fix the second know bug on import.

**Pull request closed without merging**
