### PR TITLE
JobMaster: Added MC_CARTDECORATE

### PR DESCRIPTION
**Pull request by mazvi**
Added MC_CARTDECORATE for Merchant Class with PACKETVER check

with reference: https://github.com/rathena/rathena/pull/2521

* **Addressed Issue(s)**: 

* **Server Mode**: 

* **Description of Pull Request**:

### CODE REVIEW

**Comment by Jeybla** [comment]
@mazvi can you add a `Get_Platinum_Skills` function to the globals function file and just add this function, where it's needed? Thanks in advance!

https://github.com/rathena/rathena/blob/master/npc/other/Global_Functions.txt

**Comment by mazvi** [comment]
okay so i add function with name Get_Platinum_Skills or F_GetPlatinumSkills ? what the best name?

**Comment by aleos89** [comment]
Your second name is the best. All functions should start with `F_` and we try to follow camel case.

**Comment by mazvi** [comment]
Okay i will try add this day after i back to home..

**Comment by mazvi** [comment]
Close and Merge to https://github.com/rathena/rathena/pull/2545

**Pull request closed without merging**
