### PR TITLE
pcblockall command.

### PR DESCRIPTION
**Pull request by crazystorm2017**
Block players action same like opening a mes box.

* **Addressed Issue(s)**: 
None.

* **Server Mode**: 
Both.

* **Description of Pull Request**: 
A script command for simulating the mes box.
I believe this is useful for the upcoming episode updates.
Credits mainly to joecalis of rathena, just added some parts to it.

### CODE REVIEW

**Comment by crazystorm2017** [comment]
okie, just got the idea when I tested the recent morse cave instance.

**Comment by anacondaqq** [comment]
@secretdataz 

@crazystorm2017 made a good job, why not implement it? And what will do flags?

**Comment by hurtsky** [comment]
@anacondaqq i believe sir @secretdataz wanted to do something like hercules do
```
PCBLOCK_NONE 
PCBLOCK_MOVE 
PCBLOCK_ATTACK
PCBLOCK_SKILL
PCBLOCK_USEITEM 
PCBLOCK_CHAT
PCBLOCK_IMMUNE
PCBLOCK_SITSTAND
PCBLOCK_COMMANDS 
PCBLOCK_NPCCLICK
PCBLOCK_ALL
```

**Comment by Atemo** [comment]
>Block players action same like opening a mes box.

Additionnally this action could be enabled by default when a player is attached to a script, like in official server (with battle config for disclaimer).

**Comment by cydh** [comment]
> Additionnally this action could be enabled by default when a player is attached to a script, like in official server (with battle config for disclaimer).

I'll prefer will another calling/naming and how it works, just like `disable_items`, `enable_items` and its config. to avoid overlap from this `pcblockall` actual purpose (even idk the implementation, maybe for some games to freeze everyone?)

**Comment by crazystorm2017** [comment]
Recently in the jRO's episode updates it completely stops the players action when activating an event. I'm not sure if kRO is the same since i don't have access to it. I think it's good temporarily and improve it later on for more versatility.

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/pull/3951 since the branch has been deleted.

**Pull request closed without merging**
