### PR TITLE
WIP fix configure script for MariaDB

### PR DESCRIPTION
**Pull request by secretdataz**
* **Description of Pull Request**: 
Since MariaDB still has my_bool typedef, our recent MySQL 8.0 hotfix broke compilation with LibMariaDBClient.

### CODE REVIEW

**Comment by Haikenz** [comment]
still continues with the error.
```
        CXX     sql.cpp
sql.cpp: In function 'int Sql_P_BindSqlDataType(MYSQL_BIND*, SqlDataType, void*, size_t, long unsigned int*, int8*
)':
sql.cpp:549:28: error: cannot convert 'bool*' to 'my_bool* {aka char*}' in assignment
  bind->is_null = (my_bool*)out_is_null;
                            ^~~~~~~~~~~
sql.cpp: In function 'int SqlStmt_NextRow(SqlStmt*)':
sql.cpp:891:21: error: cannot convert 'bool*' to 'my_bool* {aka char*}' in assignment
    column->error = &truncated;
                     ^~~~~~~~~
make[1]: *** [obj/sql.o] Error 1
make[1]: Leaving directory `/root/rAthena/src/common'
make: *** [common] Error 2
```

**Comment by laziem** [comment]
mine still error too
```
        CXX     sql.cpp
sql.cpp: In function ‘int Sql_P_BindSqlDataType(MYSQL_BIND*, SqlDataType, void*, size_t, long unsigned int*, int8*)’:
sql.cpp:549:28: error: cannot convert ‘bool*’ to ‘my_bool* {aka char*}’ in assignment
  bind->is_null = (my_bool*)out_is_null;
                            ^~~~~~~~~~~
sql.cpp: In function ‘int SqlStmt_NextRow(SqlStmt*)’:
sql.cpp:891:21: error: cannot convert ‘bool*’ to ‘my_bool* {aka char*}’ in assignment
    column->error = &truncated;
                     ^~~~~~~~~
Makefile:64: recipe for target 'obj/sql.o' failed
make[1]: *** [obj/sql.o] Error 1
make[1]: Leaving directory '/root/rAthena/src/common'
Makefile:41: recipe for target 'common' failed
make: *** [common] Error 2
```

**Comment by mazvi** [comment]
please merge in to master

**Comment by mazvi** [comment]
iam sorry, i was test this hotfix but still error

sql.cpp: In function ‘int Sql_P_BindSqlDataType(MYSQL_BIND*, SqlDataType, void*, size_t, long unsigned int*, int8*)’:
sql.cpp:550:16: error: cannot convert ‘bool*’ to ‘my_bool* {aka char*}’ in assignment
  bind->is_null = (my_bool*)out_is_null;
                ^
sql.cpp: In function ‘int SqlStmt_NextRow(SqlStmt*)’:
sql.cpp:892:18: error: cannot convert ‘bool*’ to ‘my_bool* {aka char*}’ in assignment
    column->error = &truncated;
                  ^
make[1]: *** [obj/sql.o] Error 1
make[1]: Leaving directory `/root/rathena/src/common'
make: *** [common] Error 2

**Comment by mazvi** [comment]
i was tested after "detect MariaDB lib with AC_CHECK_LIB" d52efb8 

but still error

sql.cpp: In function ‘int Sql_P_BindSqlDataType(MYSQL_BIND*, SqlDataType, void*, size_t, long unsigned int*, int8*)’:
sql.cpp:550:16: error: cannot convert ‘bool*’ to ‘my_bool* {aka char*}’ in assignment
  bind->is_null = (my_bool*)out_is_null;
                ^
sql.cpp: In function ‘int SqlStmt_NextRow(SqlStmt*)’:
sql.cpp:892:18: error: cannot convert ‘bool*’ to ‘my_bool* {aka char*}’ in assignment
    column->error = &truncated;
                  ^
make[1]: *** [obj/sql.o] Error 1
make[1]: Leaving directory `/root/rathena/src/common'
make: *** [common] Error 2

**Comment by mazvi** [comment]
Still error after d803d57 

i think the problem is from diferent OS 

my OS is

centos-release-7-4.1708.el7.centos.x86_64

**Comment by Lemongrass3110** [comment]
@mazvi stop commenting please. we know that it is still broken.

**Comment by bentheexo** [comment]
The reported version to check for mariadb would be 10000. The way it's
written for MySQL 8 check is greater than or equal to 8000 thereby
rendering the mariadb check invalid.

**Comment by mazvi** [comment]
amazing it solved, no error apear after i using @bentheexo method 

#if MYSQL_VERSION_ID >= 80000 && MYSQL_VERSION_ID <=100000

tested 100% work on my server

ao the problem is only this? MYSQL_VERSION_ID <=100000?

**Comment by Haikenz** [comment]
`#if MYSQL_VERSION_ID >= 80000 && MYSQL_VERSION_ID <=100000

100% Work for me in CentOS 7.4 64bits MariaDB 10.1.32`

**Comment by mazvi** [comment]
@ilfan14 are you fix using? `#if MYSQL_VERSION_ID >= 80000 && MYSQL_VERSION_ID <=100000`

**Comment by Lemongrass3110** [comment]
@mazvi @laziem could you try if the fix i just pushed works for you? @Haikenz already confirmed it working for him.
Thanks a lot.

**Comment by Lemongrass3110** [comment]
We are still waiting for a reply from travis support.
Basically the options you see are:
use renewal
disable vip system
enable build bot checks(will throw errors if warnings or errors are logged)

This is just used because it is irrelevant for the MariaDB build check what kind of configuration you use(renewal or pre-renewal). We just want to use any build configuration to check if it is working in the future.

If you use renewal & vip you would do like:
./configure --enable-vip=yes ... additional arguments(for example --with-MYSQL_LIBS) ...

**Comment by mazvi** [comment]
iam setting the VIP on src, not in travis can it?

so the travis is only tester checker on this github?

**Comment by secretdataz** [comment]
The component we are testing in this case is not related to the VIP system or renewal mode so if it works, it will work on every setting.

**Comment by secretdataz** [comment]
```
sudo apt install mariadb-server libmariadb-dev libmariadb-dev-compat
```
seems to work with our configure script.

**Pull request closed without merging**
