### PR TITLE
Resolves Cross Impact and bNoKnockback

### LINKED ISSUE #5707: Problem with animation: GC_CROSSIMPACT + bNoKnockback
* **rAthena Hash**: e1e48f7
* **Client Date**: 2020-04-01

* **Server Mode**: Re

* **Description of Issue**: 
  * Result: player don't see **animation** that charachter jump to target if he have knockback immune (like RSX card).
  * Expected Result: character should jump to monster.
  * How to Reproduce: equip armor with RSX card or something else with bonus (bNoKnockback) and use GC_CROSSIMPACT.
  https://github.com/rathena/rathena/blob/master/src/map/skill.cpp#L5679
Maybe need change **BLOWN_NONE** to **BLOWN_IGNORE_NO_KNOCKBACK**.
https://youtu.be/OO7_RIVzB7k

  * Official Information: 
* **Modifications that may affect results**:

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #5707

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Fixes Cross Impact and items with bNoKnockback causing a desync in the player's position on the client.
Thanks to @Balferian!

### CODE REVIEW

**Comment by eppc0330** [comment]
CrossImpact
CrossImpact02

There's still some other problem. If obstacle exists between character and target, a character doesn't jump in to the target.

As a quick fix I am using below, which is just a bit modified code of skill "GC_DARKILLUSION".
But I'm afraid if this jump is different as official...


	case GC_CROSSIMPACT: {
		short x, y;
		short dir = map_calc_dir(src, bl->x, bl->y);

		if (dir > 0 && dir < 4) x = 1;
		else if (dir > 4) x = -1;
		else x = 0;
		if (dir > 2 && dir < 6) y = 1;
		else if (dir == 7 || dir < 2) y = -1;
		else y = 0;

		if (unit_movepos(src, bl->x+x, bl->y+y, 1, 1)) {
			clif_blown(src);
			skill_attack(BF_WEAPON, src, src, bl, skill_id, skill_lv, tick, flag);
			}
		}
		break;

**Comment by aleos89** [comment]
Is this a test done on kRO or did you just not translate the client?

**Comment by eppc0330** [comment]
> Is this a test done on kRO or did you just not translate the client?

Im Korean. I dont need translate the client. I tested on Rathena.

**Comment by Balferian** [comment]
@aleos89 Test from kRo.
Skill should check walkpath if it false, skill will be failed.
Новый проект
```
	case GC_CROSSIMPACT: {
			uint8 dir = map_calc_dir(bl, src->x, src->y);
			
			if (skill_check_unit_movepos(5, src, bl->x, bl->y, 1, 1)) {
				skill_blown(src, src, 1, (dir + 4) % 8, BLOWN_IGNORE_NO_KNOCKBACK); // Target position is actually one cell next to the target
				skill_attack(BF_WEAPON, src, src, bl, skill_id, skill_lv, tick, flag);
			} else {
				clif_skill_fail(sd, skill_id, USESKILL_FAIL, 0);
			}
		}
		break;
```

**Comment by eppc0330** [comment]
> @aleos89 Test from kRo.
> Skill should check walkpath if it false, skill will be failed.
> Новый проект
> 
> ```
> 	case GC_CROSSIMPACT: {
> 			uint8 dir = map_calc_dir(bl, src->x, src->y);
> 			
> 			if (skill_check_unit_movepos(5, src, bl->x, bl->y, 1, 1)) {
> 				skill_blown(src, src, 1, (dir + 4) % 8, BLOWN_IGNORE_NO_KNOCKBACK); // Target position is actually one cell next to the target
> 				skill_attack(BF_WEAPON, src, src, bl, skill_id, skill_lv, tick, flag);
> 			} else {
> 				clif_skill_fail(sd, skill_id, USESKILL_FAIL, 0);
> 			}
> 		}
> 		break;
> ```
> 
> And this is from rA.
> Новый проект2

Then I think my code is more 

> @aleos89 Test from kRo.
> Skill should check walkpath if it false, skill will be failed.
> Новый проект
> 
> ```
> 	case GC_CROSSIMPACT: {
> 			uint8 dir = map_calc_dir(bl, src->x, src->y);
> 			
> 			if (skill_check_unit_movepos(5, src, bl->x, bl->y, 1, 1)) {
> 				skill_blown(src, src, 1, (dir + 4) % 8, BLOWN_IGNORE_NO_KNOCKBACK); // Target position is actually one cell next to the target
> 				skill_attack(BF_WEAPON, src, src, bl, skill_id, skill_lv, tick, flag);
> 			} else {
> 				clif_skill_fail(sd, skill_id, USESKILL_FAIL, 0);
> 			}
> 		}
> 		break;
> ```
> 
> And this is from rA.
> Новый проект2

Nice test.

**Review by Lemongrass3110 — APPROVED** [review]

**Pull request merged**
