### PR TITLE
Added optional param (CharID/AccountID/Nick) for some script commands

### PR DESCRIPTION
**Pull request by cydh**
Just somehow `attachrid` and `addrid` (or else) are annoying in some cases. I prefer direct char_id, account_id, or nick assignment for script commands.

__Current list:__
* `setd "<variable name>",<value>{,<char_id>};`
* `set <var>,<value>{,<charid>}`
* `rentitem <item id>,<time>{,<account_id>};`
* `rentitem2 <item id>,<time>,<identify>,<refine>,<attribute>,<card1>,<card2>,<card3>,<card4>{,<account_id>};`
* `strcharinfo <type>{,<char_id>};`
* `getequipisequiped <equipment slot>{,<char_id>};`
* `repair <broken item number>{,<char_id>};`
* `repairall {<char_id>};`
* `getexp <base xp>,<job xp>{,<char_id>};`
* `equip <item id>{,<char_id>};`
* `unequip <equipment slot>{,<char_id>};`
* `delequip <equipment slot>{,<char_id>};`
* `breakequip <equipment slot>{,<char_id>};`
* `clearitem {,<char_id>};`
* `openmail {<char_id>};`
* `openauction {<char_id>};`
* `setquest <ID>{,<char_id>};`
* `completequest <ID>{,<char_id>};`
* `erasequest <ID>{,<char_id>};`
* `changequest <ID>,<ID2>{,<char_id>};`
* `checkquest <ID>{,PLAYTIME|HUNTING{,<char_id>}};`
* `isbegin_quest <ID>{,<char_id>};`
* `showevent <icon>{,<mark color>{,<char_id>}};`

__Question__
_"Anyone also think something like `getvariableofnpc` but for player is needed? As I said, `attachrid` in some ways are annoying"_

### CODE REVIEW

**Comment by cydh** [comment]
seems the macros are bit off. lol

**Comment by cydh** [comment]
so better use this https://github.com/cydh/rathena/commit/ee1866152f0bc2bdcc3f8a0c2597f0fe7de2a25d macro & static function instead of previous one?

**Comment by cydh** [comment]
I changed that method already.

**Comment by cawogeek** [comment]
I think some of script commands are not attaching rid automatically like this

[Error]: buildin_savepoint: Player with char id '186' is not found.<--- '186' is the maps y coordinate
[Debug]: Source (NPC): All in One Service#0 at prontera (159,192)
[Error]: buildin_dispbottom: Player with char id '65280' is not found.<--- whats that number? >.<
[Debug]: Source (NPC): All in One Service#0 at prontera (159,192)

**Pull request merged**
