### PR TITLE
roCORD implementation 

### PR DESCRIPTION
**Pull request by SapitoSucio**
* **Server Mode**: 

  Both 

* **Description of Pull Request**: 

Bringing back to life this amazing mod https://github.com/Normynator/roCORD to make it work with latest rAthena  [fa4666d](https://github.com/rathena/rathena/commit/fa4666d7af6f2bcc0dd7071e028ab54be60e82d4)

I'm using a Pi4 on Dietpi (Debian) to compile my code, and this are the steps I followed to make it run

# Installation for Debian.

### Requirements:
  - Using a supported rAthena version.
  - Debian Stretch or better.

### Installing dependencies and apply patches:
  - Run the following commands (they require sudo permissions):
  ```
    $ apt-get install libcurl4-openssl-dev
    $ apt-get install libboost-all-dev
    $ apt-get install libssl-dev
    $ apt-get install libicu-dev
  ```
### Compiling rAthena with roCORD
  - Go into your rAthena folder.
  - You should find a "build" directory. (If not thencreate it)
  - Go into the "build" directory.
  - use CMake:
    ```
      $ cmake -G"Unix Makefiles" -DINSTALL_TO_SOURCE=ON ..
    ```
  - finally run make:
    ```
      $ make install
    ```
# Important:
You need to change the config.json file located in /conf/discord/
You need to change the token value and the channel id to match yours

### Done
  - Now you can run your server as you normaly do.

### CODE REVIEW

**Comment by hnomkeng** [comment]
can guide on almalinux OS ?

**Review by Lemongrass3110 — CHANGES_REQUESTED** [review]
Please revert the changes in 3rdparty/rapidyaml.

**Comment by SapitoSucio** [comment]
> can guide on almalinux OS ?

I can't, I don't know that OS, sorry


> Please revert the changes in 3rdparty/rapidyaml.

I will as soon as I know how to make roCORD to include the rapidyaml src/header files on the compilation time, If i remove full path roCORD doesn't compile at all 😔

**Comment by hnomkeng** [comment]
> > can guide on almalinux OS ?
> 
> I can't, I don't know that OS, sorry
> 
> > Please revert the changes in 3rdparty/rapidyaml.
> 
> I will as soon as I know how to make roCORD to include the rapidyaml src/header files on the compilation time, If i remove full path roCORD doesn't compile at all 😔

ok, ref https://github.com/Normynator/roCORD/blob/development/docs/installation_centos.md

**Comment by Pokye** [comment]
Why are you using src/custom/**script.inc** and **script_def.inc** ? it would be better to implement in **script.cpp**. It would be nice to implement the Windows version as well, @Normynator did that.

**Comment by SapitoSucio** [comment]
> Why are you using src/custom/**script.inc** and **script_def.inc** ? it would be better to implement in **script.cpp**. It would be nice to implement the Windows version as well, @Normynator did that.

I think it's just a habit xD, If isn't 'official rathena code' I throw it on the custom folder, but I can move it to the script.cpp 😺
And yes, would be amazing to have this working on Windows too, and I hope to get it done soon.

The first thing I want to fix is the fact that roCORD don't find the rapidyaml files when compiling

It may take a while, I'm no expert / full time developer by any means, so please bear with me @Pokye 🐸

**Comment by Akkarinage** [comment]
As much as Norm's project is totally amazing, you should probably just fork his original repo - Discord integration is outside of the scope of rAthena.

**Comment by SapitoSucio** [comment]
> As much as Norm's project is totally amazing, you should probably just fork his original repo - Discord integration is outside of the scope of rAthena.

Well, I think you may be right, I'll create a fork from it

**Pull request closed without merging**
