### PR TITLE
Some item name fixes

### PR DESCRIPTION
**Pull request by Pokye**
* **Addressed Issue(s)**:  https://github.com/rathena/rathena/commit/4592ae6c09576bc634c3cb8302d2ca6005e39910

* **Server Mode**:  Renewal

* **Description of Pull Request**:  Some item name fixes

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
```
2022-04-09T23:03:46.6744167Z [Error]: Found duplicate item Aegis name for C_Demons_Familiar, skipping.
2022-04-09T23:03:46.6744441Z [Error]: Occurred in file 'db/re/item_db_equip.yml' on line 147531 and column 4.
```

**Comment by Daegaladh** [comment]
> ```
> 2022-04-09T23:03:46.6744167Z [Error]: Found duplicate item Aegis name for C_Demons_Familiar, skipping.
> 2022-04-09T23:03:46.6744441Z [Error]: Occurred in file 'db/re/item_db_equip.yml' on line 147531 and column 4.
> ```

Yeah 410087 should be C_Demons_Familiar_K instead

**Comment by Pokye** [comment]
Thanks @Lemongrass3110 @Daegaladh .

**Comment by Pokye** [comment]
> Source of the aegis name? The names you added/changed are currently unknown on divine pride

The ones I changed are already in divine-pride.

**Comment by Everade** [comment]
> Source of the aegis name? The names you added/changed are currently unknown on divine pride

RO-BR as it seems

**Review by Atemo — APPROVED** [review]

**Review by Everade — APPROVED** [review]

**Pull request merged**
