### PR TITLE
Initial release script commands for Item Random Options

### PR DESCRIPTION
**Pull request by cydh**
* `getitem3`
* `getitembound3`
* `makeitem3`
* `rentitem3`
* `countitem3`
* `delitem3`

Signed-off-by: Cydh Ramdh <cydh@pservero.com>

### CODE REVIEW

**Comment by cydh** [comment]
wrong base :v

**Comment by iubantot** [comment]
can this be used to check all options? for example the 1st~4th option of the item?

**Comment by cydh** [comment]
@iubantot for checking, see the doc https://github.com/rathena/rathena/blob/master/doc/script_commands.txt#L9393-L9401

**Comment by cydh** [comment]
Closed, renewed to #2066

**Pull request closed without merging**
