### PR TITLE
Fix to issue #2579: No error when setting MAX_MOB_DB too high

### PR DESCRIPTION
**Pull request by psychonaut04**
* **Addressed Issue(s)**: 

#2579

* **Server Mode**: 

Renewal(from issue), please check if it can apply to both.

* **Description of Pull Request**: 

struct mob_db *mob_db will return mob_dummy if **MAX_MOB_DB** is **51000** or more, plus compile will return error.

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
Having the ifdef check makes the other case unreachable code, since you will never be able to compile it like that.

**Comment by psychonaut04** [comment]
Like, could only change one file? I got that before but still changed the other case just to be sure, but don't need i guess.

**Comment by lighta** [comment]
The code look ok, but I don't really get, why does this have to be limited to 51k ?

**Comment by Jeybla** [comment]
The mobid is mostly declared as `unsigned short` (max. 65535) or `short` (max. 32767) in the src. For the current code base I'd suggest to raise the error already at 32767. @psychonaut04 why did you decide to raise the error at 51000? @lighta it should be better to have an error message instead of simply stopping execution.

I think we'd need to refactor that some time anyway.

**Comment by lighta** [comment]
well if it unsigned short, make the error when set over UINT16_MAX instead that would make more sens imo. (or INT16_MAX) if we worry about the wrap.

**Comment by psychonaut04** [comment]
Oh can change it so, i got no clue about the max value, just did it using the value that the user talked about in the issue.

**Comment by Jeybla** [comment]
@Lemongrass3110 is about to increase the maximum mobdb entries in #2604

**Comment by Lemongrass3110** [comment]
Thanks for your contribution!

Sadly this is not needed anymore as @Jeybla already mentioned. As of b2ab972 MAX_MOB_DB is only used for ID checks and should not be touched anymore.

Looking forward to your next contribution though!

**Pull request closed without merging**
